### PR TITLE
Opera comparison /new variation (Fixes #6130)

### LINKED ISSUE #6130: 2 /new variations for Opera visitors w. traffic cop
Success Criteria:
- [ ] 2 /new variations live
- [ ] Traffic is configured to route traffic according to spec in the bug

[FINAL copy ](https://docs.google.com/document/d/1AvqbqZHiyKpTauaGClf0RzbXfcWBZGOjocwzbOAZxEc/edit)

### PR DESCRIPTION
**Pull request by alexgibson**
## Description
- Adds two new browser comparison download pages for Opera:
  - `/firefox/new/?xv=opera`
  - `/firefox/new/?xv=opera&v=2`

~**Do not merge** until we get final copy approval & content links.~

## Issue / Bugzilla link
#6130

## Testing
Demo links:
- https://bedrock-demo-agibson.oregon-b.moz.works/en-US/firefox/new/?xv=opera
- https://bedrock-demo-agibson.oregon-b.moz.works/en-US/firefox/new/?xv=opera&v=2

You should be able to hit the experiment using a URL such as https://bedrock-demo-agibson.oregon-b.moz.works/en-US/firefox/new/?xv=opera&utm_source=google&utm_medium=cpc&utm_content=A144_A203_C001036&

Testing notes:
- [x] Ensure Traffic Cop experiment is firing correctly.
- [x] Check for copy pasta errors / typos.

### CODE REVIEW

**Comment by alexgibson** [comment]
Ok, content-wise this has [been approved](https://bugzilla.mozilla.org/show_bug.cgi?id=1489266#c14). Should be good for review / merge.

**Comment by stephaniehobson** [comment]
/me wonders idlly why we're still a/b testing. Shouldn't we have results from the first two by now?

**Comment by stephaniehobson** [comment]
Huh. There's a lot of technical jargon in this one. I could see how it might perform differently than the other ones.

**Comment by ejregithub** [comment]
Moreover the tests are geared at the specific competing browser users. Content vars/preference could well vary across that set of users.

**Pull request merged**
