### PR TITLE
Remove session-related settings and remind developers that Bedrock is stateless

### LINKED ISSUE #10872: Remove session-related code from Bedrock
## Description

Bedrock is stateless and we no longer support any session-based behaviour in Bedrock itself. There are some bits of stale code which should be cleaned up to make it easier to understand.

---

#### Success Criteria
- [ ] Settings should no longer reference the cache backend as session storage
- [ ] Session-related settings and middleware should be removed from the codebase

### PR DESCRIPTION
**Pull request by stevejalim**
## Description

Nano-sized papercut, tidied up while in the neighbourhood. #DeadCodeRemoval

## Issue / Bugzilla link

Resolves #10872

## Testing - not much to test

* All tests pass

### CODE REVIEW

**Comment by pmac** [comment]
This looks like a good change to me, but I wonder if we're not thinking of something that relies on the session engine to at least be configured. Perhaps we should do a `run-integration-tests` push of this branch just to be sure?

**Comment by stevejalim** [comment]
@pmac Yep, I agree. Will run the integration tests now

**Comment by stevejalim** [comment]
@pmac Integration tests came back all green - see Pipeline #435460320

**Comment by stevejalim** [comment]
> pmac: I wonder if we're not thinking of something that relies on the session engine to at least be configured. 

Good call - been thinking about that, in case we're shooting ourseleves in the foot.

*Thinking aloud...* 

Because we're removing the config here, we'll end up using the default of `django.contrib.sessions.backends.db`, so there will at least be _something_ ticking over in the background ([source](https://docs.djangoproject.com/en/2.2/ref/settings/#session-engine)) if we did need it.

However, because we don't have `SessionMiddleware` or `'django.contrib.sessions'` included in our settings, there should be no session management taking place at all. As per [the docs](https://docs.djangoproject.com/en/2.2/topics/http/sessions/#enabling-sessions): 

> If you don’t want to use sessions, you might as well remove the `SessionMiddleware` line from MIDDLEWARE and `'django.contrib.sessions'` from your `INSTALLED_APPS`. It’ll save you a small bit of overhead.

However, let's assume _somehow_ we haven't disabled them... because each web pod has its own copy of the DB, _if_ it somehow/surprisingly we aren't 100% stateless and we ended up writing to a sessions table, we might a) get write contention on sqlite and b) end up with a lack of session consistency (unless the k8s service is using using sticky sessions for consistently routing to the same pod). 

So, to check this, I've hit my local build directly a few times (ie, no CDN to drop session cookies etc) and there are no sessions in the sqlite DB - indeed, there's not even a `django_session` table and `manage.py migrate` doesn't try to add one:

```
sqlite> .tables
auth_group                          pocketfeed_pocketarticle
auth_group_permissions              product_details_productdetailsfile
auth_permission                     releasenotes_productrelease
auth_user                           rna_note
auth_user_groups                    rna_note_releases
auth_user_user_permissions          rna_release
base_configvalue                    security_halloffamer
careers_position                    security_mitrecve
contentcards_contentcard            security_product
contentful_contentfulentry          security_securityadvisory
django_content_type                 security_securityadvisory_fixed_in
django_migrations                   sitemaps_sitemapurl
externalfiles_externalfile          utils_gitrepostate
legal_docs_legaldoc                 wordpress_blogpost
newsletter_newsletter
```

So, I think we're good, but def open to some more angles on this

**Review by pmac — APPROVED** [review]
🎄

**Comment by pmac** [comment]
Fantastic research and testing. Thanks for being so thorough!

**Pull request merged**
