### PR TITLE
Lint mozilla-accordion.js files

### PR DESCRIPTION
**Pull request by alexgibson**

### CODE REVIEW

**Comment by schalkneethling** [comment]
@alexgibson Here are two var changes I think you missed:
https://github.com/alexgibson/bedrock/blob/lint-mozilla-accordion/media/js/base/mozilla-accordion.js#L313

And also in the docs here:
https://github.com/alexgibson/bedrock/blob/lint-mozilla-accordion/docs/mozilla-accordion.rst#global-settings

**Comment by alexgibson** [comment]
Great catch, thanks @schalkneethling

**Comment by alexgibson** [comment]
@schalkneethling updated thanks

**Comment by schalkneethling** [comment]
r+ :tangerine:

**Pull request merged**
