### PR TITLE
Disable locale volume mount in test container

### PR DESCRIPTION
**Pull request by jgmize**
## Description

Temporarily disable locale volume mount

## Issue / Bugzilla link

#8051

## Testing

`make test` on Docker for Mac passes with these changes

### CODE REVIEW

**Comment by jgmize** [comment]
I restored the volume mount on the app container in 700a444  and the tests are still passing locally.

**Comment by jgmize** [comment]
I also tried replacing `delegated` with `consistent` and `cached` [configurations](https://docs.docker.com/docker-for-mac/osxfs-caching/) but got the same errors.

**Comment by jgmize** [comment]
The [line triggering the errors](https://github.com/mozilla/bedrock/blob/master/bedrock/base/tests/test_accepted_locales.py#L45) is attempting to move the whole directory as part of the setup for each test. It may make more sense to remove this mount permanently given what the test setup is doing.

**Comment by pmac** [comment]
Oh wow. Those tests are a bit crazy. I think maybe the right answer in this case is to just remove that test file as we'll be phasing out the old l10n system soon which this is testing.

**Pull request merged**
