### PR TITLE
Fix external /firefox/channel redirect tests

### PR DESCRIPTION
**Pull request by alexgibson**
@pmac - I'm guessing whomever owns these domains updated the external redirects to point to the new channel pages?

Failing in master: https://ci.us-west.moz.works/blue/organizations/jenkins/bedrock_multibranch_pipeline/detail/master/190/pipeline/

### CODE REVIEW

**Comment by pmac** [comment]
Huh. I didn't realize (or remember) that we tested these. Doesn't seem like something we should be testing since we have no control over them and they're not part of bedrock. Perhaps we should just remove them?

**Comment by alexgibson** [comment]
> Huh. I didn't realize (or remember) that we tested these. Doesn't seem like something we should be testing since we have no control over them and they're not part of bedrock. Perhaps we should just remove them?

Fine by me - assume these are legacy things from the mcom-test repo?

**Comment by alexgibson** [comment]
@pmac updated

**Comment by alexgibson** [comment]
@pmac fixed the error caught by circle 👍

**Pull request merged**
