### PR TITLE
Updates to FF100 home page promo (#11539)

### PR DESCRIPTION
**Pull request by alexgibson**
## One-line summary

- Adds a couple of line breaks to the DE/FR versions requested by the EU team.
- Adds GA data attributes and utm params to promo links for all versions.

## Issue / Bugzilla link

#11539

### CODE REVIEW

**Review by maureenlholland — CHANGES_REQUESTED** [review]
Looks good on GA attributes and UTM params ✅ 

Line breaks are good on desktop but the text is very off-center on tablet. I'm not sure what the best fix is here - make the breaks display none until over tablet size or center the text so it's not all off to the side on the medium size screens. Would request we make some style adjustment here to make the text and button line up better.

Screen Shot 2022-05-05 at 12 06 02 PM

**Comment by alexgibson** [comment]
@maureenlholland thanks for the review! I think centering the layout on medium viewports will improve things hopefully. Updated

**Comment by alexgibson** [comment]
@maureenlholland also made the promo title an `h2`, since there's already an `h1` in each template.

**Review by maureenlholland — APPROVED** [review]
LGTM 💯

**Pull request merged**
