### PR TITLE
Make running locally in prod mode easier

### PR DESCRIPTION
**Pull request by pmac**
This will give us some commands to more easily build and run the prod Docker image locally. It will run using your local version of the Django app, but not the media, which must be built separately.

## Using

If you want to run things locally as if they're prod and see changes in templates or Python files you can simply:

```
make pull run-prod
```

That will pull the latest prod image and run it in prod mode locally. If you need to build new static assets (images, CSS, JS, etc.) then you can do:

```
make build-prod run-prod
```

Let me know what you think.

Re #8636

### CODE REVIEW

**Comment by pmac** [comment]
This obviously still needs docs, but I wanted you to try it first before we document it and merge this. It may well not be that useful since you have to build the image every time you want to view it with changed CSS...

**Comment by alexgibson** [comment]
Thanks for this @pmac!

I ran both of the above commands and they worked OK 👍 

One thing I didn't expect was still needing to set `Dev=False` and `Debug=False` in my `.env`. If we still need to do this manually then I think that's fine, but let's document it and explain what the commands do / don't handle.

I think this will be very useful for thing like checking locale activation (template fallbacks), as well as debugging errors that don't happen when `Dev=True`.

**Comment by pmac** [comment]
Good point. It does still use your `.env` file. I could have it use a hard coded `prod.env` file instead but I'm guessing that setting env vars will be a thing you will want to do for this at some point. I'm honestly not sure which way is best to go for this. I'm leaning toward leaving it as-is and documenting that you have to update your `.env` file with what you want. Thoughts?

**Comment by alexgibson** [comment]
> Thoughts?

I can picture someone wanting to set `Dev=False` but also `Debug=True` for some error tracing, so I think leaving things as-is and documenting it may be fine?

**Comment by pmac** [comment]
Added docs. Ready for review.

**Pull request merged**
