### PR TITLE
Bug 1220883 - Update address and map marker of Beijing office

### PR DESCRIPTION
**Pull request by l-hedgehog**

### CODE REVIEW

**Comment by alexgibson** [comment]
I believe the co-ordinates here may also need updating? https://github.com/mozilla/bedrock/blob/master/media/js/mozorg/contact-data.js#L67

**Comment by l-hedgehog** [comment]
@alexgibson, yes, I updated it. It looks like GitHub somehow decides to not show it in the diff view by default.

**Comment by alexgibson** [comment]
Thanks @l-hedgehog, I totally missed that! This change looks fine to me, r+

I'll merge this a bit later, once fall campaign has launched and things calm down a little.

**Comment by l-hedgehog** [comment]
@alexgibson, thanks.

**Pull request merged**
