### PR TITLE
Bug 1305661 functional tests for home / technology page

### PR DESCRIPTION
**Pull request by alexgibson**
Updated functional tests for the new home page. This also required creating a page object for the Technology page in order to test the main site navigation, so I added a test for the technology page blog feed as a separate commit.

### CODE REVIEW

**Comment by jpetto** [comment]
Code looks good and tests are passing. 👍

Just to confirm, if the blog feed job were to fail for some reason, thereby sending no articles to the template (and causing the 2 technology page tests to fail), we wouldn't be blocked on a push, correct?

**Comment by alexgibson** [comment]
Yes correct, any test failures will block a push.

**Comment by alexgibson** [comment]
I should add, the test run has to fail 3 times consecutively for the push not to go through.

**Comment by jpetto** [comment]
Hm, do we want to be blocked on a push based on external services? I know it's not very likely for all the blog feeds to go down/be inaccessible, but it's not something entirely under our control.

**Comment by alexgibson** [comment]
We already have several test scores of this nature for various pages. I think we cache things pretty heavily, so if something fails it's more likely a failure on our side than a reliance on external data.

**Comment by jpetto** [comment]
Good enough for me. 😁

**Pull request merged**
