### PR TITLE
[fix bug 1385566] Revert "First version of new Global Mission Partner…

### PR DESCRIPTION
**Pull request by craigcook**
## Description
This reverts commit ebb9ceff12d313caa49e1d5c4eee196acd29cc3c.

I'll file a follow-up PR to restore the changes for later merging.

## Issue / Bugzilla link
https://bugzilla.mozilla.org/show_bug.cgi?id=1385566

### CODE REVIEW

**Comment by craigcook** [comment]
I should add that I did start down a path of wrapping all the changes in a switch but soon found it would entail some butchering of templates and incurring debt to remove all those conditionals post-launch. It just seems simpler to undo the changes in master and redo them in another branch that we'll merge on the day.

**Comment by alexgibson** [comment]
@flodolo - before I merge this, just checking that reverting this commit would not cause any issues for .lang files?

**Comment by flodolo** [comment]
No consequences, since the process of extraction is manual.

**Comment by alexgibson** [comment]
Thanks @craigcook 👍

**Pull request merged**
