### PR TITLE
Add GitHub pull request template

### PR DESCRIPTION
**Pull request by alexgibson**
See: https://github.com/blog/2111-issue-and-pull-request-templates

### CODE REVIEW

**Comment by alexgibson** [comment]
What we include here is totally up for discussion, but could be really useful?

r from everyone? :smile:

**Comment by kyoshino** [comment]
We could put these new files under the `.github` subdir :file_folder:  along with `CONTRIBUTING.md`, as per the GitHub blog post.

**Comment by alexgibson** [comment]
@kyoshino - good suggestion, done :+1:

**Comment by pmclanahan** [comment]
r+ Nice work Alex!

**Comment by alexgibson** [comment]
I'm going to go ahead and merge this as-is. We can always re-iterate and improve this as time goes on. Thanks @pmclanahan and @kyoshino!

**Pull request merged**
