### PR TITLE
Update Reps Council on Leadership Page accoding to latest Council Ele…

### PR DESCRIPTION
**Pull request by MichaelKohler**
…ctions

## Description

Update the Reps Council according to the latest elections: https://discourse.mozilla.org/t/important-council-elections-autumn-2018-results-and-next-steps/32600?u=mkohler

Additionally I've replaced Edoardo's and Ruben's images on their own wish.

## Issue / Bugzilla link
-

## Testing
Open the leadership page and notice the new faces/names

### CODE REVIEW

**Comment by MichaelKohler** [comment]
@pmac @alexgibson r?

**Comment by pmac** [comment]
Looks fine to me. I'll let Alex see if any of the images need to be run through optimization tomorrow. Thanks for the PR!

**Comment by MichaelKohler** [comment]
I've run the new images through ImageOptim and pushed again:

screenshot 2018-11-01 at 18 02 11

**Comment by MichaelKohler** [comment]
Oh, that should not have happened. I wonder how..

**Comment by MichaelKohler** [comment]
> They have just been optimized 👍

Yep, also changed, but the diff is confusing there indeed. Thanks!

**Pull request merged**
