### PR TITLE
Fix Bug 1126417, made content updates for shape of the web

### PR DESCRIPTION
**Pull request by schalkneethling**
@pmclanahan @ckprice r?

### CODE REVIEW

**Comment by ckprice** [comment]
@schalkneethling thanks! Does this include all the content updates from the spreadsheet?

https://docs.google.com/a/mozilla.com/spreadsheets/d/1m_nYN0ZNkq8CqZjkxk__7d0qppKP9w11pxFu-NotNnM/edit

**Comment by schalkneethling** [comment]
@ckprice I believe so, went through both the tabs in the spreadsheet. Let me know if I missed anything.

**Comment by schalkneethling** [comment]
@ckprice so the other things is, I assumed this document is the final content and all inclusive so, what was not in the spreadsheet I removed from the JSON.

**Comment by ckprice** [comment]
@schalkneethling ran through JSON validator successfully. Added some comments from Greg. r+wc!

**Comment by ckprice** [comment]
r+ @pmclanahan can we merge?

**Comment by pmclanahan** [comment]
Yeah. Let's just squash the typo fixes commit into the main one and we can merge.

**Comment by schalkneethling** [comment]
@ckprice squashed

**Pull request merged**
