### PR TITLE
Fix Bug 1238458 - Decommission iOS newsletter sign up page

### PR DESCRIPTION
**Pull request by kyoshino**
Redirect [/newsletter/ios/](https://www.mozilla.org/en-US/newsletter/ios/) to [/firefox/ios/](https://www.mozilla.org/en-US/firefox/ios/).

### CODE REVIEW

**Comment by kyoshino** [comment]
Cc @flodolo for the removed strings

**Comment by flodolo** [comment]
Is this confirmed? It's unclear from the bug.

**Comment by kyoshino** [comment]
I don't know who can make the final decision but the page is obviously obsolete. Other sign-up forms have been removed, so there should be no problem here IMO.

**Comment by alexgibson** [comment]
I agree this change is likely fine - @kyoshino perhaps just needsinfo malexis in the bug for confirmation?

**Comment by kyoshino** [comment]
Okay.

**Comment by alexgibson** [comment]
r+ on the code changes. Good to merge once bug is confirmed thanks @kyoshino :cake:

**Comment by alexgibson** [comment]
We're good to merge, thanks @kyoshino!

**Pull request merged**
