### PR TITLE
[fix bug 1187821] Removed unused Lightbeam pages and assets

### PR DESCRIPTION
**Pull request by alexgibson**
Removing code that was added in [Bug 926629](https://bugzilla.mozilla.org/show_bug.cgi?id=926629) but never used. These pages never went live and have been sitting here for a long time. I think it's about time we remove them from the repo.

### CODE REVIEW

**Comment by schalkneethling** [comment]
This looks all good and, seeing you did the PR to add these, no one better to remove them ;p r+

**Comment by schalkneethling** [comment]
Not merging yet, as I am not sure whether there is something @flodolo needs to review before so, once @flodolo gives the all clear, I will merge. Thanks! :fish_cake:

**Comment by flodolo** [comment]
No need to wait for me, just marked the PR as a reminder to clean up the lang file.

**Comment by schalkneethling** [comment]
:candy:

**Comment by alexgibson** [comment]
> This looks all good and, seeing you did the PR to add these, no one better to remove them

Not me whom added them, that was someone from the foundation.

**Pull request merged**
