### PR TITLE
Fix Bug 1153351 - Move Firefox for Android release notes to /firefox/android/

### PR DESCRIPTION
**Pull request by kyoshino**

### CODE REVIEW

**Comment by kyoshino** [comment]
As per today's meeting, I'll keep the desktop relnotes URLs.

**Comment by kyoshino** [comment]
Updated and tested locally.

**Comment by jgmize** [comment]
Thanks @kyoshino this is looking good so far, but I'd like to get this on a demo environment and run mcom-tests against it before merging-- I expect this will break mcom-tests, and I'm especially wanting to test out the changes to global.conf.

**Comment by jgmize** [comment]
I [pushed this to demo4 and did some testing](https://people.mozilla.org/~jmize/mobile-to-android-release-notes.html), but we are lacking coverage on mcom-tests for this. Things are looking good as far as the code in this PR goes, but I'll need to do some more manual testing before I'm ready to merge, and ideally we'd have coverage in mcom-tests that validate the new behavior. @kyoshino would you be interested in taking on a PR to mcom-tests to cover the expected behavior?

**Comment by kyoshino** [comment]
I think the tests on Bedrock (in this PR) cover most cases. Do we still need another ones in mcom-tests?

**Comment by jgmize** [comment]
The tests in bedrock do cover most cases, but they don't validate the changes in global.conf, for example. I can take that on if you're not interested, no worries.

**Comment by kyoshino** [comment]
Oh I see. Then I'll send a PR later!

**Comment by jgmize** [comment]
thanks @kyoshino!

**Comment by kyoshino** [comment]
Sent a PR for mcom-tests.

**Comment by jgmize** [comment]
Thanks @kyoshino!

**Comment by kyoshino** [comment]
Awesome, thanks!

**Pull request merged**
