### PR TITLE
Remove Sidebar Menu JS from /all Fix #13236

### LINKED ISSUE #13236: Remove Sidebar Menu JS from /all
## Description

In the recent Protocol upgrade the JavaScript to support the side bar menu component was added to /all. That makes sense, there's a side bar. However, it's only displayed to visitors who do not meet modern browser requirements and the JavaScript itself only takes effect on mobile browsers (because this sidebar menu does not have any nested menu items). 

I believe collapsing the menu on mobile makes the page harder to navigate, since if the user misses the menu (because it is collapsed) they have to scroll through all the language options for desktop browsers before getting to the mobile download links.

The better user experience for everyone is to remove the javascript IMHO.

---

#### Success Criteria
- [ ] Sidebar menu JS is removed from all-downloads-unified-init.es6.js

### PR DESCRIPTION
**Pull request by stephaniehobson**
## One-line summary

Remove Sidebar Menu JS from /all

## Issue / Bugzilla link

Fix #13236 

## Testing

http://localhost:8000/en-US/firefox/all/

- [ ] no JS errors

### CODE REVIEW

**Review by alexgibson — COMMENTED** [review]
I tried testing this, but when viewed on a smaller screen the menu seems to no longer be accessible? It remains collapsed, but because we then no longer load the JS it can't expand.

**Comment by stephaniehobson** [comment]
Note to myself about reproducing this: small screen, javascript enabled, but not a modern browser.

**Comment by stephaniehobson** [comment]
Updated.

**Review by alexgibson — APPROVED** [review]
r+

**Pull request merged**
