### PR TITLE
Fix #13613: Have Sentry ignore common but non-actionable errors

### LINKED ISSUE #13613: Bedrock generates far too many incidents in Sentry
Some of the exceptions that end up in Sentry are common and unavoidable. We should filter them.

## Common Culprits
 
* [ConnectionResetError](https://mozilla.sentry.io/issues/3183739325/?environment=production&project=6249535&query=&referrer=project-issue-stream&statsPeriod=7d)
* [BrokenPipeError](https://mozilla.sentry.io/issues/3183740776/?environment=production&project=6249535&query=&referrer=project-issue-stream&statsPeriod=7d)

## Sentry Filtering

[Sentry provides docs](https://docs.sentry.io/platforms/python/guides/django/configuration/filtering/) for filtering these kinds of things at the app layer.

### PR DESCRIPTION
**Pull request by pmac**

### CODE REVIEW

**Comment by pmac** [comment]
Hmmm... I found references to the `ignore_errors` method, and inspection of the code of the version we use does show it there, but this thread suggests it's maybe not really supported and may be removed https://github.com/getsentry/sentry-python/issues/149

**Comment by pmac** [comment]
I'll update this to use the `before_send` function instead.

**Review by stevejalim — APPROVED** [review]
Not test driven but lgtm

**Review by robhudson — APPROVED** [review]
🪨

**Comment by bkochendorfer** [comment]
:+1: LGTM

**Pull request merged**
