### PR TITLE
Localized /firefox/67.0.1/whatsnew/ URLs redirect to /en-US/ (Fixes #7246)

### LINKED ISSUE #7246: Localized /firefox/67.0.5/whatsnew/ URLs redirect to /en-US/
## Description

Locales outside of `[en, de, fr]` are currently redirected to a non-localized whatsnew page for 67.0.5.

### Steps to reproduce

Visit: https://www.mozilla.org/es-ES/firefox/67.0.5/whatsnew/

### Expected result

It should display the localized content visible at this URL: https://www.mozilla.org/es-ES/firefox/67.0/whatsnew/

### Actual result

It redirects to https://www.mozilla.org/en-US/firefox/67.0.5/whatsnew/

### Environment

Any Firefox browser

### PR DESCRIPTION
**Pull request by alexgibson**
Fixes https://github.com/mozilla/bedrock/issues/7246

### CODE REVIEW

**Comment by sylvestre** [comment]
As @jcristau noted, this will conflict with https://github.com/mozilla/bedrock/pull/7250
@alexgibson could you please merge my change into yours ? :)

**Comment by alexgibson** [comment]
Thanks @sylvestre and @jcristau. I pushed a commit that changes our logic to show the trailhead WNP for any 67.0.x release. Does that make things more flexible?

**Comment by sylvestre** [comment]
To be clear, there is what we probably want:
* Updating from 67.0 or earlier => 67.0.1 _what's new page_
* Updating from 67.0 or earlier => 67.0.2 (if any) = _what's new page_
* 67.0.1 => 67.0.2 (if any) = **NO** _what's new page_

**Comment by alexgibson** [comment]
> 67.0.1 => 67.0.2 (if any) = NO what's new page

Bedrock doesn't control when to show a whatsnew page, it only deals with the logic for what template to show for a given URL. Triggering whatsnew is done by releng.

**Comment by sylvestre** [comment]
OK, thanks!

Hopefully, we won't have a chemspill forcing us to burn the 67.0.1 version code :)

**Comment by alexgibson** [comment]
Ok great, I think we're all set. I'll try and get someone to review this ASAP.

**Comment by nthomas-mozilla** [comment]
> > 67.0.1 => 67.0.2 (if any) = NO what's new page
> 
> Bedrock doesn't control when to show a whatsnew page, it only deals with the logic for what template to show for a given URL. Triggering whatsnew is done by releng.

@sylvestre, we have implemented the opposite in the [release automation configuration](https://hg.mozilla.org/releases/mozilla-release/rev/e219b566bff653cc9c69534d85f53bc1c5e25940#l1.46) because there's no version restriction there. Could you discuss with marketing and determine if we need a change before any 67.0.2+ ?

**Pull request merged**
