### PR TITLE
Fixes bug 1323417 - Update the number of languages on firefox/all to 90

### PR DESCRIPTION
**Pull request by TheoChevalier**
## Description
We now have more locales, let’s be proud of it :) We’re still not localizing this page, so I’m not adding a l10n tag.

## Bugzilla link
https://bugzilla.mozilla.org/show_bug.cgi?id=1323417

## Testing
Description & Tweet on https://www.mozilla.org/en-US/firefox/all/ are updated.

## Checklist
- [ ] Requires l10n changes.
- [ ] Related functional & integration tests passing.

### CODE REVIEW

**Comment by flodolo** [comment]
(CC @kyoshino for Japanese)

**Comment by kyoshino** [comment]
I just checked [all.lang](https://github.com/mozilla-l10n/www.mozilla.org/blob/master/ja/firefox/all.lang) and found a placeholder `%s` which is apparently not used at this time. I guess the number should be retrieved from the [settings](https://github.com/mozilla/bedrock/blob/master/bedrock/settings/base.py#L538).

**Comment by flodolo** [comment]
Given that languages use different plural forms based on the number, better not to use a placeholder in case we start localizing this page.

**Comment by kyoshino** [comment]
And, yeah, there's only the Japanese l10n for this page, I'm happy to update the translation shortly.

**Pull request merged**
