### PR TITLE
Bug 1282494: Please use https://product-details.mozilla.org/1.0/ inst…

### PR DESCRIPTION
**Pull request by pascalchevrel**
## Description
Use Ship It generated data for product-details

## Bugzilla link
https://bugzilla.mozilla.org/show_bug.cgi?id=1282494
## Testing
Manual testing on https://bedrock-demo-new-product-details.us-west.moz.works/

## Checklist
- [ ] Requires l10n changes.
- [ ] Related functional & integration tests passing.

### CODE REVIEW

**Comment by jgmize** [comment]
ran `deis-usw config:set PROD_DETAILS_URL=https://product-details.mozilla.org/1.0/ -a bedrock-stage` and then kicked off https://ci.us-west.moz.works/job/bedrock_test_stage_us_west/1077 which passed, but @kyoshino reported errors locally. Waiting to merge pending further info.

**Comment by kyoshino** [comment]
I'm testing the new source locally, and still getting an error on /firefox/channel/. 

> TypeError at /firefox/channel/
> Exception Value: 'NoneType' object is not iterable
> Exception Location: /Users/Kohei/Documents/Mozilla/GitHub/bedrock/bedrock/firefox/helpers.py in download_firefox, line 127

Other pages look good so far.

**Comment by kyoshino** [comment]
[firefox_versions.json](https://product-details.mozilla.org/1.0/firefox_versions.json) says `"FIREFOX_AURORA": "49.0a2"` in while [firefox_primary_builds.json](https://product-details.mozilla.org/1.0/firefox_primary_builds.json) says `50.0a2`. Clearing the cache solved the issue.

**Comment by kyoshino** [comment]
Everything looks good to me now 😸

**Comment by jgmize** [comment]
Thanks @pascalc and @kyoshino

As a reminder, this changes the default but we explicitly set this to the old svn URL in most environments when we ran into issues the last time around, so we will need to "unset" the setting for each environment in order for this to take effect.

**Pull request merged**
