### PR TITLE
Fix #11610: Move Firefox OS privacy policy to archive

### LINKED ISSUE #11610: Move the Firefox OS privacy policy to the archive
In https://github.com/mozilla/legal-docs/issues/1746 the legal team has asked us to archive the Firefox OS privacy policy. This means removing the link to the document from the sidebar of the main privacy page, and adding a link to the archive page (https://www.mozilla.org/en-US/privacy/archive/). We can keep the URL of the policy unchanged if we'd like and keep it hooked up to the legal-docs repo if it's easier.

### PR DESCRIPTION
**Pull request by pmac**
We could move it to a `privacy/archive/` URL, but there doesn't seem like much point to doing that and adding the redirect to me. I could be persuaded though if we really want to.

### CODE REVIEW

**Review by alexgibson — CHANGES_REQUESTED** [review]
Seeing as there's only one Firefox OS notice to archive (versus Firefox that has had multiple over the years), I think I'm OK with not moving this into the `/archive/` directory, although doing it would be more consistent?

However I do think we should still add the archived notice / badge to the policy page itself, else if someone views the URL directly, there's no way to tell that the notice is outdated?

image

Archived policies also seem to have an archived date in the `page_title`.

**Comment by pmac** [comment]
Good points. Perhaps we should just go ahead and make it static and fully archive it.

**Comment by pmac** [comment]
Updated with doc made static and moved fully to archive and old URL redirected.

**Review by alexgibson — APPROVED** [review]
r+ 💯

**Pull request merged**
