### PR TITLE
106 release notes illustrations

### PR DESCRIPTION
**Pull request by pascalchevrel**
PNG optimized with tiny.png, animated GIF optimized with ezgif.com

106 release notes illustrations, go live is October 18.

### CODE REVIEW

**Comment by stevejalim** [comment]
@pascalchevrel Could you rebase your branch on `main` please? That'll make sure it contains a fixup that will make CI pass again

**Comment by pascalchevrel** [comment]
@stevejalim should be rebased now

**Comment by pmac** [comment]
> note to self: why is the difference in `circleci/config.yml` not showing in the PR diff, I wonder...?

Just not how git works. Merging this would not change that file since Pascal didn't change that file, so it doesn't show in the diff.

**Comment by stevejalim** [comment]
@pmac thanks, yeah - the penny dropped a moment ago. There's value in how SteveGit would work ;)

**Review by stevejalim — APPROVED** [review]

**Pull request merged**
