### PR TITLE
bug-1189121-remove-moz-prefixed-gradient -expressions -from -bedrock

### PR DESCRIPTION
**Pull request by TheJJ100100**
@alexgibson Here you go.

Bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1189121

Old Pull Request: https://github.com/mozilla/bedrock/pull/3231/

### CODE REVIEW

**Comment by TheJJ100100** [comment]
@alexgibson I've screwed it up again, when trying to get rid of an unwanted change....

**Comment by TheJJ100100** [comment]
@alexgibson Are YOU able to pick a single commit to merge? If so, it will be fine.

**Comment by alexgibson** [comment]
@TheJJ100100 - when you opened this PR it was fine with just one commit? What happened? :cry: 

I'll see if I can cherry pick this commit and merge it for you if the code changes look good.

**Comment by TheJJ100100** [comment]
@alexgibson In that one commit, there were changes I didn't make and I was trying to remove them, but I must have gone wrong.

**Comment by alexgibson** [comment]
@TheJJ100100 - I have cherry picked your commit and opened a new PR for you. We can take care of merging it once someone reviews the code. I'll make sure your commit remains intact so you get credit for the bug. Thanks for this work, I know how difficult learning git can be - it gets easier, keep at it :smile:  :clap:

**Comment by alexgibson** [comment]
Closing in favor of #3240

**Comment by TheJJ100100** [comment]
Thank You @alexgibson

**Pull request closed without merging**
