### PR TITLE
Bug 1143626 - Copy rules — Mozilla Style Guide — Mozilla has broken link...

### PR DESCRIPTION
**Pull request by anaran**
... for Open Web

### CODE REVIEW

**Comment by kyoshino** [comment]
Thanks @anaran!

**Comment by anaran** [comment]
@kyoshino thanks for the link, this pull request should be better :-)

**Comment by cargoworker** [comment]
Can one of the admins verify this patch?

**Comment by alexgibson** [comment]
Thanks for the PR @anaran!

**Pull request merged**
