### PR TITLE
[fix bug 1187829] Update waypoints JS lib.

### PR DESCRIPTION
**Pull request by jpetto**
- Remove orphaned 'products' bundle & JS file.

### CODE REVIEW

**Comment by schalkneethling** [comment]
I saw the Alex mentioned that we should switch to using the waypoints version that is not dependent on jQuery but, also saw you mentioned the sticky.waypoints part does still require jQuery. Is this the reason why you stuck with the jQuery dependent version of the base waypoints library?

**Comment by jpetto** [comment]
Yep, I stuck with the jQuery build of Waypoints to support the sticky plugin/shortcut.

**Comment by schalkneethling** [comment]
All good r+ :spaghetti:

**Comment by alexgibson** [comment]
Missed one here: https://github.com/mozilla/bedrock/blob/master/media/js/firefox/australis/common.js#L24

Doesn't break anything on the page, but I'll open a quick PR to tidy it up.

**Pull request merged**
