### PR TITLE
bug id=1149550  Update advisories.html

### PR DESCRIPTION
**Pull request by pemmasanikrishna**
The typo error in the page title tag is corrected.

### CODE REVIEW

**Comment by cargoworker** [comment]
Can one of the admins verify this patch?

**Comment by craigcook** [comment]
r+ 
Would you mind amending the commit message to include the bug number?

**Comment by pemmasanikrishna** [comment]
Can you explain me how to modify it. I am not able to find edit option.

**Comment by craigcook** [comment]
Do you have a local copy of the repository or did you edit this file on github? If you're new to git, <a href="https://help.github.com/articles/changing-a-commit-message/">this article is a good introduction to amending commits</a>, but it does require you to have a local repository. If you used the online editor on github.com I don't think it's possible, so in that case you don't need to worry about it. We'll either edit the message when we merge it or we might just not bother since this is such a small change.

Ideal commit messages should be concisely descriptive of the code change and should reference a bug number (for those changes that directly address a specific bug in bugzilla). It helps future coders to understand the history of each file because they can look up the bug for more detail. It also helps us track changes in bugzilla since the bug can be automatically updated with a reference to the git commit.

**Comment by pemmasanikrishna** [comment]
I have edited it directly on github and I don't have a local copy of that.

**Comment by craigcook** [comment]
This was merged in f760c982f5. Many thanks, and congratulations on your first merged pull request and your first fixed bug! :rocket:

I changed the commit message by first checking out your branch into my local repository and used the <code>git commit --amend</code> command to revise the previous commit with a new message. The update will go to our production servers with our next code push.

**Comment by pemmasanikrishna** [comment]
but its not reflecting in bugzilla that I have solved the issue. How to do that?

**Comment by alexgibson** [comment]
@pemmasanikrishna - Bug 1149550 is marked as `resolved`, `fixed`. Which is correct, so everything is ok :)

It can be updated later as `verified` once it moves to production. Thanks for checking!

**Comment by pemmasanikrishna** [comment]
Thanks :)

**Pull request closed without merging**
