### PR TITLE
[fix #6337] Add FxA benefits CTAs to home page

### LINKED ISSUE #6337: Homepage Banners CTA - Account Benefits Page
| Estimates |  |
| ------------- | ------------- | 
| TL | 1|
| PM | 4|
| ENG | 10|
| SEO | 0|
| ANA | 1|
| DES | 10|
| COPY | 4|

Change Download CTA on homepage for FF users to an Accounts Benefits CTA

---

#### :yellow_heart: Success Criteria :yellow_heart:

- [ ] Replace Fx download CTA for Fx users w. FxAccount CTA
- [ ] Analytics QA
- [ ] Inform stakeholders
- [ ] Reuse design & copy from benefits page
- [ ] Replace secondary download CTA for Fx Users
- [ ] Internal Design QA
- [ ] Stakeholder Design QA
- [ ] Internal coded component QA
- [ ] Stakeholder Design QA
- [ ] Stakeholder coded page QA

### PR DESCRIPTION
**Pull request by craigcook**
## Description
Adds primary, secondary, and sticky CTA banners promoting Firefox Accounts visible to users of Firefox. All other browsers get the standard Firefox download promos, which is also the default when browser can't be detected if JS isn't available. 

This also updates the primary Firefox download promo for the Firefox Fights For You campaign (new image and headline).

Because of the duplication of these elements I made some effort to follow the Protocol naming convention and treat them like reusable organisms, but they're also just different enough that each one needed custom styling and in the end the CSS is a little all-over-the-place. I'm not proud, and I apologize to the reviewer.

## Issue / Bugzilla link
#6337 
#6490

## Testing
https://bedrock-demo-craigcook.oregon-b.moz.works/en-US/

I've removed the fundraising banner on demo so you can see the sticky banners. Otherwise the sticky banners are disabled as long as the fundraising banner is active.

### CODE REVIEW

**Comment by craigcook** [comment]
Hrm... there's a quick flash of the download promo before the JS kicks in to hide it and show FxA instead. I'll see if I can fix that.

**Comment by alexgibson** [comment]
This is likely to break home page functional tests. We should probably update them to test that the download button is visible to non-Firefox browsers, and the FxA CTA visible to Firefox.

**Comment by craigcook** [comment]
I still want to try to fix the content flash but don't want to block this merging. I'll try to work on that later with a follow-up PR, but gotta finish LiveNation first.

**Comment by craigcook** [comment]
Also, although this isn't technically blocked by the new accounts page (#6503) I'd like to try to make sure they go into the same prod push, so may hold off merging this until the other PR gets an r+.

**Comment by craigcook** [comment]
Integration tests are green!

**Pull request merged**
