### PR TITLE
Indicate next steps and give feedback when cancelling

### PR DESCRIPTION
**Pull request by stephaniehobson**
- Script now suggests a letter to press to back out
- Script only requires a single character of input before progressing
- Script outputs "Cancelled." if the tag is cancelled

### CODE REVIEW

**Comment by stephaniehobson** [comment]
Yeah, I want to make that improvement too :) I've already got the command to find the commit hash for stage head:`git ls-remote git://github.com/mozilla/bedrock.git refs/heads/stage | cut -f 1`

I don't know how to check if all the tests have passed though so I still want to prompt with the "are you sure?"

**Comment by stephaniehobson** [comment]
Also, I think it would be worth double checking that local master HEAD matches the remote master HEAD.

**Comment by stephaniehobson** [comment]
Or rather, we can check tests have passed but I don't know how to check if stage deployment succeeded.

**Comment by pmac** [comment]
yeah. that would be a lot more work. Maybe it's actually already at the point of diminishing returns and we should just keep the prompt for every prod push to make sure people are thinking about it?

**Pull request merged**
