### PR TITLE
Bug 1233665 - Menu links on redesigned release notes are hard to click

### PR DESCRIPTION
**Pull request by TheoChevalier**
Fixing menu links click area + cursor state, and removing trailing spaces in the file.

### CODE REVIEW

**Comment by alexgibson** [comment]
Thanks for the fix @TheoChevalier, works well r+ :ice_cream:

**Comment by alexgibson** [comment]
Wait, I notice one regression here - on small viewports the menu is misaligned and much bigger than before. So changing this to an r+wc.

mobile-nav

**Comment by TheoChevalier** [comment]
Ah, thanks @alexgibson, I forgot to check the smallest view… 
Rebased and pushed, should be fixed now

**Comment by alexgibson** [comment]
Looks good, thanks again! r+ :christmas_tree:

**Pull request merged**
