### PR TITLE
[fix bug 1199738] Update FxOS devices features.

### PR DESCRIPTION
**Pull request by jpetto**

### CODE REVIEW

**Comment by alexgibson** [comment]
For the ZTE Open the features tab says `Up to 9 h`, but the specs tab says `Up to 9 h 20 m`

**Comment by alexgibson** [comment]
Other than the one inconsistency this looks ok to me

It does seem a little confusing to be using decimals for talk time in some places, and hour/minutes in other places. But we already have a mix of different specs in the template already, so not a blocker.

r+wc :iphone:

**Comment by alexgibson** [comment]
We're holding off merging this until l10n catches up, so keeping the do-not-merge label for now.

**Comment by jpetto** [comment]
Good catch on the ZTE Open @alexgibson. I have updated the specs tab to just read "Up to 9 h" to match the features. Will at least give L10n one less string to localize/change.

**Comment by flodolo** [comment]
We have 21 locales complete by now, which covers about 75% of our population. Given the missing locales, I think we're good to merge here.

**Pull request merged**
