### PR TITLE
Run firefox pre-download experiment for de and fr locales (Fixes #6456)

### LINKED ISSUE #6456: Re-launch pre-download experiment
This probably means reverting #6224 so we can run experiment #5944 once again. 

Aim is to launch experiment early next week with a new cohort size and duration that xluo is going to provide details about. 

Success Criteria:
- [ ] page is made available to x% (test parameters TBD) DE locale with [this localized content](https://docs.google.com/document/d/1jcytuc-QMV-onPuE6zpxbU_v2BBmt15cWGC5oRnnHGM/edit#)
- [ ] page is made available to x% (test parameters TBD) FR locale with [this localized content](https://docs.google.com/document/d/1RCWsZLFQzVFVcEXba6SU13CQDn5Q3ucolQaC02dcqRs/edit?ts=5bedee6b)

### PR DESCRIPTION
**Pull request by alexgibson**
## Description
- Enables pre-download experiment on `/firefox/` for `de` and `fr` locales at 25% of traffic.

**Do not merge** until https://www.mozilla.org/en-US/privacy/email/ is localized in French and German.

## Issue / Bugzilla link
#6456

## Testing
Demo URLs:

https://bedrock-demo-agibson.oregon-b.moz.works/fr/firefox/
https://bedrock-demo-agibson.oregon-b.moz.works/de/firefox/

Note: test in a non-Firefox browser on Windows with DNT disabled.

### CODE REVIEW

**Comment by alexgibson** [comment]
Ok, some last minute updates to the configuration of this experiment:

- We now append the locale to the end of `utm_content` so we can track retention for these locales easier.
- Link to `/privacy/websites/` instead of `/privacy/email/` since we can't get the page translated at present (I'm less than happy about this, but from a legal point of view it's considered a non blocker).

**Comment by alexgibson** [comment]
@stephaniehobson one last round of review?

**Comment by alexgibson** [comment]
Ok, we now have German and French translations for `/privacy/email/`. This is now unblocked and good for review / merge. The hope is to get this experiment live tomorrow (Thursday).

**Comment by stephaniehobson** [comment]
R+

**Pull request merged**
