### PR TITLE
remove the download col for esr52

### PR DESCRIPTION
**Pull request by sylvestre**

### CODE REVIEW

**Comment by pmac** [comment]
Looks like we should turn off the `esr` switch first?

**Comment by pmac** [comment]
We can actually remove the entire surrounding if statement for the ESR switch. Both code-blocks are the same after this change.

**Comment by sylvestre** [comment]
ok, I will update my PR
(I was asking what was the switch for, now, I know :p)

**Comment by pmac** [comment]
Actually I think we need to do something else. Now that the switch has been flipped the page title doesn't make much sense as there is no choice to be made. I'll file an issue to update the page and remove the switch unless you really want to update this PR. Thanks for the help!

**Comment by stephaniehobson** [comment]
@amychurchwell Do you want to take this review? We can address the page title separately but let's get this merged since @sylvestre was nice enough to save us the work.

**Comment by stephaniehobson** [comment]
Yeah, we should remove the switch over there too.

**Pull request merged**
