### PR TITLE
[fix bug 1234263] Prevent New Relic JS for IE 6.

### PR DESCRIPTION
**Pull request by jpetto**

### CODE REVIEW

**Comment by jpetto** [comment]
Switched from `userAgent` check to conditional comment.

**Comment by jpetto** [comment]
@alexgibson r?

**Comment by alexgibson** [comment]
Code-wise this gets an r+ from me. Should we merge this and test against stage, or push to a demo?

**Comment by alexgibson** [comment]
Fwiw, I tried replicating the error locally on IE6 but couldn't seem to hit it.

**Pull request merged**
