### PR TITLE
Remove virginia

### PR DESCRIPTION
**Pull request by jgmize**

### CODE REVIEW

**Comment by jgmize** [comment]
cc @metadave

**Comment by metadave** [comment]
was the removal of  `jenkins/branches/regional-integration-tests.yml` intentional?

**Comment by pmac** [comment]
Just waiting on an answer to @metadave's question @jgmize.

**Comment by jgmize** [comment]
Yes, the regional-integration-tests.yml file was intentionally deleted as that config & code was merged into master.

**Comment by jgmize** [comment]
Yes, the virginia cluster is in the process of being permanently decommissioned. I plan on specifically avoiding that AWS region in the future.

**Pull request merged**
