### PR TITLE
Ensure the slug on a particular VPN page is all lowercase

### LINKED ISSUE #15386: Change VPN resource center article URL to lowercase
## Description

The following resource center article contains an uppercase character in the URL, which Wagtail won't accept when we migrate the page over. We should update this URL to use lowercase, so the wagtail version can fallback to the django page without a 404.

https://www.mozilla.org/en-US/products/vpn/resource-center/no-Logging-vpn-from-mozilla/

---

#### Success Criteria
- [ ] URL is updated to lowercase e.g. `/no-logging-vpn-from-mozilla/`

### PR DESCRIPTION
**Pull request by stevejalim**
## Issue / Bugzilla link

Resolves #15386

## Testing

* Run migrations
* Confirm that http://localhost:8000/en-US/products/vpn/resource-center/no-logging-vpn-from-mozilla/ works 
* Note that http://localhost:8000/en-US/products/vpn/resource-center/no-Logging-vpn-from-mozilla/  now 404s

### CODE REVIEW

**Comment by stevejalim** [comment]
Ah yeah, this is failing cos the DB export need tweaking to not include redirects. Will do that now.

**Review by alexgibson — CHANGES_REQUESTED** [review]
Migration LGTM, but it would be nice to add a redirect for the old URL, just to stop it 404'ing 👍

**Comment by alexgibson** [comment]
@stevejalim looks like we're getting an odd error here: `django.db.utils.IntegrityError: The row in table 'products_vpnresourcecenterindexpage' with primary key '7' has an invalid foreign key: products_vpnresourcecenterindexpage.page_ptr_id contains a value '7' that does not have a corresponding value in wagtailcore_page.id.`

**Comment by stevejalim** [comment]
Thanks @alexgibson - that was fixed by https://github.com/mozilla/bedrock/pull/15389

I've done fresh DB exports across "the estate" and will rerun the tests now. (These tests pull from the prod DB bucket)

**Review by alexgibson — APPROVED** [review]
r+

**Pull request merged**
