### PR TITLE
[fix bug 1118211] Re-enable Firefox Desktop landing animation on OSX

### PR DESCRIPTION
**Pull request by alexgibson**

### CODE REVIEW

**Comment by alexgibson** [comment]
Marking as do not merge for now, as the waiting on Bug 1083079 being uplifted to FF 36.

**Comment by jpetto** [comment]
Confirmed still broken in 36.0a2, but code is good. r+, waiting for uplift.

**Comment by alexgibson** [comment]
This is now fixed in 36.0a2 (2015-01-12) :+1:

**Comment by jpetto** [comment]
Confirmed working in Dev Edition 36.0a2 (2015-01-12). Ready to merge?

**Comment by alexgibson** [comment]
Go for it :D

**Pull request merged**
