### PR TITLE
Update docs with info for creating on-demand demo deployments

### PR DESCRIPTION
**Pull request by alexgibson**

### CODE REVIEW

**Comment by alexgibson** [comment]
Took a stab at updating things. @pmclanahan r?

**Comment by schalkneethling** [comment]
r+ :dolls:

**Comment by pmclanahan** [comment]
DOH! Sorry I missed the ping Alex. The branch name isn't `feature__demo`, it's `demo__feature`. We should also mention that it should almost always be `demo__<your_username>` to keep them from piling up.

**Comment by alexgibson** [comment]
Thanks @pmclanahan - let me open a new PR and try again 😄

**Pull request merged**
