### PR TITLE
bug-1189121-remove-moz-expressions-from-bedrock

### PR DESCRIPTION
**Pull request by TheJJ100100**
Bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1189121

Removed: background: -moz-linear-gradient(top, #43a6e2 0%, #247ac1 100%);

@alexgibson

### CODE REVIEW

**Comment by TheJJ100100** [comment]
@schalkneethling 

Bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1189121

Removed: background: -moz-linear-gradient(top, #43a6e2 0%, #247ac1 100%);

**Comment by TheJJ100100** [comment]
Is @alexgibson busy?

**Comment by craigcook** [comment]
> Is @alexgibson busy?

Alex is on holiday right now and will return soon, but I can review this in the meantime.

**Comment by TheJJ100100** [comment]
Ok @craigcook

**Comment by alexgibson** [comment]
Hi @TheJJ100100 - thanks for taking on this bug!

This change seems fine as-is, but to complete the bug and mark it as fixed we need to remove all occurrences of -moz prefixed gradient expressions in the code base. There are several more, as linked to in this [comment on the bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1189121#c1).

**Comment by TheJJ100100** [comment]
Oh, I didn't see that comment @alexgibson !

**Comment by TheJJ100100** [comment]
@alexgibson I made a commit with all the changes needed, and I did a rebase to squash the changes to one commit, however, when I do "git push" or "git push --force" the changes are not coming through.

**Comment by TheJJ100100** [comment]
I see why now, I accidentally made TWO branches for the same bug (I don't know how!) is it possible to merge this branch and the other branch?

**Comment by TheJJ100100** [comment]
@alexgibson Fixed, it's working now.

**Comment by TheJJ100100** [comment]
@alexgibson Done, now. I didn't add 27 lines, by the way. It's some random commit that I got by accident when doing a rebase and I don't know how to get rid of it! :(

**Comment by schalkneethling** [comment]
@TheJJ100100 what do you get if you do `git log` on this branch?

**Comment by TheJJ100100** [comment]
@alexgibson @schalkneethling  I pasted the output here: https://gist.github.com/TheJJ100100/813a7a452ea7b8c7a2c8

**Comment by alexgibson** [comment]
@TheJJ100100 - I'm not clear on what has happened there, but it looks like you may have accidentally squashed some other [commits](https://github.com/mozilla/bedrock/commit/c252326ef602a1c8675c1434830460fe3ab12032) into your change. It may be worthwhile opening a new PR here on a clean branch, as something looks a bit odd with the history here?

**Comment by TheJJ100100** [comment]
@alexgibson I don't know what's happened, either. Also, how do I bring across the changes I have made?

**Comment by TheJJ100100** [comment]
@alexgibson @schalkneethling If you want to know, this is my master branch's git log: https://gist.github.com/TheJJ100100/60070033036aa6e34473

**Comment by alexgibson** [comment]
You could try git cherry-pick, but I'm not sure on what would happen taking across the unintended changes. Git might be smart there, but failing that it may mean you need to re-make your code changes and create a new commit on the fresh branch :(

**Comment by TheJJ100100** [comment]
@alexgibson @schalkneethling Ok

**Comment by TheJJ100100** [comment]
@alexgibson Looks like I'm going to have to redo my changes. :( Oh well. I'll reference this pull request on the new pull request.

**Comment by alexgibson** [comment]
@TheJJ100100 - sorry to hear that. Interactive rebase is certainly fiddly, and needs careful attention when picking what to squash. :cry:

**Comment by TheJJ100100** [comment]
@alexgibson Yes, I'm still new to git :+1:

**Comment by alexgibson** [comment]
You may have already taken a look through them, but we have some docs to help with squashing commits here: http://bedrock.readthedocs.org/en/latest/contribute.html#squashing-your-commits

**Pull request closed without merging**
