### PR TITLE
Sticky navigation demo (#8600)

### PR DESCRIPTION
**Pull request by amychurchwell**
## Description
Rough draft of sticky navigation.

## Issue / Bugzilla link
#8600

## Testing
https://www-demo-demo-nav-sdavucfmzlyu.herokuapp.com/en-US/exp/firefox/

### CODE REVIEW

**Comment by alexgibson** [comment]
I was excited to tes this out - hope you don't mind some feedback on a couple of UX issues I noteced:

1. On mobile I couldn't scroll the nav content or the screen when open:

nav-mobile

2. On desktop, if the user's screen is small then the nav can (sometimes accidentally) cover the entire screen, preventing scroll and making the nav hard to close. If the nav content is also longer than the screen height, that content is also inaccessible.

Screenshot 2020-02-28 at 10 23 20

**Comment by amychurchwell** [comment]
@alexgibson -- thanks for the feedback, Alex! This isn't quite ready for review yet. Current state is a super quick rough draft to make sure I was in the right direction.

**Comment by amychurchwell** [comment]
On UX issues:

> 1. On mobile I couldn't scroll the nav content or the screen when open:

I think for this test we should make the sticky nav desktop only. There is no CTA in the nav on mobile, so it wouldn't help out the experiment imo.

> 2. On desktop, if the user's screen is small then the nav can (sometimes accidentally) cover the entire screen, preventing scroll and making the nav hard to close. If the nav content is also taller than the screen height, that content is then inaccessible.

When the nav covers the entire screen, it seems like it doesn't prevent scroll but you can't see where you are scrolling & a user might not realize. Perhaps we should prevent scrolling if the nav covers the entire view? 

If the nav covering the entire screen makes it trickier to close- maybe we should move the 'x' to the left instead? Or maybe make the nav narrower so you can see the page to the left and right that would allow a user to click off the nav to close?

Also, I am going to tinker with making the nav container vertically responsive so it does not break out of screen height.

**Comment by justinkropp** [comment]
@amychurchwell This LGTM. 

I agree with the following:

> I think for this test we should make the sticky nav desktop only. There is no CTA in the nav on mobile, so it wouldn't help out the experiment imo.

The default behavior on mobile/small viewports in the demo feels right. Users on mobile are more than willing to scroll, so letting them scroll through the expanded nav _and_ the page is ideal. I would also keep the "X" as is. The majority of users are right-handed and moving the "X" to the left could present some possible usability issues (harder for them to reach with their thumbs if operating the one-handed).

Hope that helps :)

**Comment by amychurchwell** [comment]
Thank you for the feedback everyone. Closing this pull request and moving conversation to the issue. 👍

**Pull request closed without merging**
