### PR TITLE
Bug 1309050: Update Twitter API to use one app credentials

### PR DESCRIPTION
**Pull request by pmac**
No need for support for multiple accounts and keys.

### CODE REVIEW

**Comment by pmac** [comment]
@glogiotatidis r?

**Comment by pmac** [comment]
I've already created a new twitter account (so that if the credentials are ever compromised it won't matter since no one will be following the account) and added the new credential keys to the dev, stage, and prod apps in deis.

**Comment by glogiotatidis** [comment]
Please also update example `local.py` https://github.com/mozilla/bedrock/blob/2fb16c05fbb847b57e0fbbea8a5b51d51d554e43/bedrock/settings/local.py-dist#L15

**Comment by glogiotatidis** [comment]
💯  nice work @pmac! r+wc

**Comment by pmac** [comment]
Ah yes! Good catch. We should actually just remove `local.py-dist` I think. The docs now recommend using a `.env` file.

**Pull request merged**
