### PR TITLE
Fix Bug 1226476 - Convert android/all/ to the same format as desktop uses

### PR DESCRIPTION
**Pull request by kyoshino**
Screenshot: https://bugzilla.mozilla.org/attachment.cgi?id=8703553

### CODE REVIEW

**Comment by kyoshino** [comment]
@jgmize @pmclanahan r?

**Comment by kyoshino** [comment]
These column labels are from [nightly.mozilla.org](https://nightly.mozilla.org/). Honeycomb (Android 3.x) is no longer supported so **Modern devices (Android 4.0+)** is correct.

**Comment by kyoshino** [comment]
Oh wait, the support version is changing with Firefox 46. So we still have to say **Android 3.0+**. Will update the label and icon.

**Comment by craigcook** [comment]
Page looks good to me. r+ on the front-end. :zap:

**Comment by kyoshino** [comment]
Thanks @craigcook!

**Comment by kyoshino** [comment]
@flodolo There are a couple of new strings here as well.

**Comment by flodolo** [comment]
We don't localize the download pages, so good for us ;-)

**Comment by kyoshino** [comment]
https://www.mozilla.org/en-US/firefox/all/ is localized, but only in Japanese.

**Comment by flodolo** [comment]
Because they decided to localize it on their own. It's not tracked, not exposed to any other locale and not updated (there's also no en-US version).

**Comment by jgmize** [comment]
@kyoshino would you mind rebasing this?

**Comment by kyoshino** [comment]
Rebased!

**Comment by jgmize** [comment]
Thanks again, @kyoshino!

**Comment by kyoshino** [comment]
:smile_cat:

**Pull request merged**
