### PR TITLE
CSP: Remove `'unsafe-inline'` from `style-src` (Fix #14840)

### LINKED ISSUE #14840: Remove `unsafe-inline` from `style-src`

### PR DESCRIPTION
**Pull request by robhudson**
## One-line summary

Remove `'unsafe-inline'` from `style-src`

- [ ] I used an AI to write some of this code.

## Issue / Bugzilla link

#14840

### CODE REVIEW

**Review by alexgibson — COMMENTED** [review]
One gotcha here is this will visually effect pages where we embed inline SVGs that have embedded `<style>` tags. You can see an example at http://localhost:8000/de/firefox/welcome/9/

Before:

image

After:

image

A few possible options I can think of to avoid this:

1. Is there a way to make a CSP exception for embedded SVGs? I'm not aware of one, but perhaps worth checking?
2. We stop in-lining SVG images and load them as ``'s instead. Sometimes we inline things for performance, but this is mostly a nice to have. Other times, we inline to change CSS styles based on dark/light mode preferences, but that can also be accomplished using `<picture>`.
3. We update SVGs not to use embedded `<style>` tags, and use properties instead (this seems like the most time consuming / unrealistic option).

It might be a little tricky / time consuming to figure out what needs fixing throughout the site. But I think it could be worth it still. Thoughts?

**Comment by robhudson** [comment]
1. There's no way to specifically allow `unsafe-inline` just for SVGs.

I don't fully understand option 2, but option 3 makes sense to me. But I also agree it would be time consuming if there are lots of SVGs. And not all inlined styles map to attributes so you'd still have some styles that need to be ... un-inlined? outlined? :)

**Comment by alexgibson** [comment]
I think option 2 is probably the most realistic solution in terms of time / effort if 1 is not do-able. It would basically involve:

1. An audit of inline `<svg>` element in templates throughout the site.
2. Identify which are problematic.
3. Replace the problematic images with loading via `` or `<picture>`.

**Comment by janbrasna** [comment]
Oh shoot, the problematic ones are inlined via includes, so it's super tricky to quickly distinguish which .svg files are only being used as imgs, and which ones end up being {%include%}d :/

Just quickly glancing e.g. the vpn lock, it can be further svgoptimised to get rid of most of the styles, but the dealbreaker is the group: `style="isolation:isolate"` has probably no attribute equivalent:/

So that kinda makes 3) and 1) impossible. However:
a) these particular images could perhaps benefit from being lazy anyways as they're below the fold,
b) don't seem to be loading this way in Safari, without any obvious error for some reason 🤷

**Comment by alexgibson** [comment]
I did a search in VSCode for `<style ` (excluding `/media/`) and it didn't actually come up with many results, so this issue might not be as large as it first seems:

- bedrock/bedrock/base/templates/cron-health-check.html
- bedrock/bedrock/firefox/templates/firefox/welcome/includes/page9/illo-vpn-lock.svg
- bedrock/bedrock/firefox/templates/firefox/welcome/includes/page9/illo-vpn-speed.svg
- bedrock/bedrock/firefox/templates/firefox/welcome/includes/page10/laptop.svg
- bedrock/bedrock/firefox/templates/firefox/welcome/includes/page10/mobile.svg
- bedrock/bedrock/firefox/templates/firefox/welcome/includes/page11/lock.svg
- bedrock/bedrock/firefox/templates/firefox/whatsnew/includes/fx119/addons.svg

Saying that, it's possible I have missed something so might require for further checks.

**Comment by janbrasna** [comment]
I've raised the cron-healthz in https://github.com/mozilla/bedrock/issues/14840#issuecomment-2239232206 specifically, and tried to multipass the hell out of svgo to try to get rid of all the style definitions in bulk, but with not much success; there are a few complicated SVG styles that have no attribute counterpart unfortunately.

Maybe it could be fixed with some manual rework of the svgs, trying to overcome some of the group blending and whatnot in a different way, but if un-inlining and loading them lazy (performance-wise it's just a bunch of older welcomes and wnps from yeasteryear(s)) is also an option, that could be the easiest.

**Comment by alexgibson** [comment]
I think we're fine to load these SVGs via `` or `<picture>` with lazy loading as needed.

As for the cron-healthz page, we could always just remove the inline SVGs and let good old browser default styles do their work. As long as it's readable, it's functional.

**Comment by janbrasna** [comment]
OK I've drafted PRs for both of the issues to hopefully unblock this change eventually, but even then I'd say it'd be safer to test-drive such a change in REPORT_ONLY.

If I read it correctly, this PR removes `_csp_style_src = [UNSAFE_INLINE]` straight from the enforced policy _(which is probably not reported at all?)_, whereas I'd say let's remove it just from RO for now and push it, letting is soak for a while to see the ingested reports for anything that causal browsing about doesn't show…?

**Comment by robhudson** [comment]
Yeah, I agree, we can move this to the report-only policy first. I was under the impression that we knew we were sure we were no longer using unsafe-inlines for styles so I jumped the gun. I'll update the code to reflect this.

**Comment by janbrasna** [comment]
I guess we will never know 100% for sure for any rule until it hits the prod traffic with some reasonable %% reporting for enforced failures over there, and even though most of the violations will be addons and similar tinkering, the general public is nonetheless the best spelunker to hit all the wee nooks and crannies at scale;)

**Comment by robhudson** [comment]
I opened https://github.com/mozilla/bedrock/pull/14869 which encompasses the fix here, but also fixes some things @stevejalim reported and we need to fix. There were too many differences to reconcile between these two so that PR can supersede this one. But I'll leave this open for now for comparison.

**Comment by janbrasna** [comment]
@robhudson Then also check the overlap with #14831 where it seems both changesets are touching the same code, going different directions…

**Comment by robhudson** [comment]
Yeah, if/when this is merged, I'll go update my other branches. It doesn't look like different directions. I just know I've updated a couple branches in a similar way and this one feels the best so far. I'm trying to make the adjustments to the CSP concise and understandable.

**Comment by robhudson** [comment]
Closing this PR now that #14869 merged. We removed `style-src 'unsafe-inline'` from the report-only policy to see where we need to make fixes.

**Pull request closed without merging**
