### PR TITLE
Upgrade pipeline, less, and replace yuglify with cssmin and uglify-js.

### PR DESCRIPTION
**Pull request by pmclanahan**
This should (may) speed up local dev, and should speed up deployment.
Newer pipeline works better with less and will let us use babel-js for
es6 should we choose to do so as an interim step.

### CODE REVIEW

**Comment by pmclanahan** [comment]
@alexgibson mind pulling this down and seeing if there is any improvement? 

@jgmize r?

**Comment by alexgibson** [comment]
I pulled this down locally and tested a few pages. Seems to be a slight improvement in page loading speed (although still not as fast as it used to be).

**Comment by pmclanahan** [comment]
I'll keep trying :(

**Comment by pmclanahan** [comment]
Or we'll just deal with it long enough to fully move to gulp etc.

**Comment by jgmize** [comment]
r+, but remind me again why checking in node_modules is better than checking in the compiled artifacts produced on developer machines?

**Comment by pmclanahan** [comment]
Because node_modules is just source? It's similar to vendor. If we had compiled node dependencies it wouldn't work either.

**Comment by pmclanahan** [comment]
@jgmize did you see something in `node_modules` that won't work on the server that I missed?

**Comment by pmclanahan** [comment]
Oh... I misread earlier... We can have this debate again if you'd like.

1. Checking in compiled bundles means a lot more churn in the repo since the compiled files will change with every chage of the source.
2. It introduces possibilities of uncompiled changes if people forget they need to do another thing.
3. Since we use the immutable file names and unless we figured out a way to do only that step on the server we'd have a new full bundle file every time a source file changed, increasing the size of the repo by potentially a lot.
4. The build dependencies change far less often, and we already have node on the server.
5. It gives us the opportunity to build the media in CI to double check for problems.

That's the few things off the top of my head. If you feel like switching it all around and training all of the front-enders to correctly set their settings for production static files and generate the files only checking in the right ones, then go for it. I'm happy with what we're doing.

**Comment by jgmize** [comment]
No, that's a good explanation, I had honestly forgotten, thanks for reminding me :)

**Pull request merged**
