### PR TITLE
Migrate SEM download pages from /new to /campaign (#6894)

### PR DESCRIPTION
**Pull request by alexgibson**
## Description
- Migrates existing SEM campaign pages from /new to /campaign.
- Leaves URLs at /new live for a short-time period, during which the SEM team can migrate their ad traffic to point to the new URLs.
- Once ads are all pointing to the new place, I'll file a follow up PR to remove the old URLs from /new.

## Issue / Bugzilla link
#6894

## Testing

- [x] Templates below should be visible at both `/new/` and `/campaign/` with no visual differences.

`/new` URLs:

- https://www-demo1.allizom.org/en-US/firefox/new/?xv=betterbrowser
- https://www-demo1.allizom.org/en-US/firefox/new/?xv=safari
- https://www-demo1.allizom.org/en-US/firefox/new/?xv=edge
- https://www-demo1.allizom.org/de/firefox/new/?xv=berlin
- https://www-demo1.allizom.org/de/firefox/new/?xv=aus-gruenden
- https://www-demo1.allizom.org/de/firefox/new/?xv=herz
- https://www-demo1.allizom.org/de/firefox/new/?xv=geschwindigkeit
- https://www-demo1.allizom.org/de/firefox/new/?xv=privatsphare
- https://www-demo1.allizom.org/de/firefox/new/?xv=auf-deiner-seite

`/campaign` URLs:

- https://www-demo1.allizom.org/en-US/firefox/campaign/?xv=betterbrowser
- https://www-demo1.allizom.org/en-US/firefox/campaign/?xv=safari
- https://www-demo1.allizom.org/en-US/firefox/campaign/?xv=edge
- https://www-demo1.allizom.org/de/firefox/campaign/?xv=berlin
- https://www-demo1.allizom.org/de/firefox/campaign/?xv=aus-gruenden
- https://www-demo1.allizom.org/de/firefox/campaign/?xv=herz
- https://www-demo1.allizom.org/de/firefox/campaign/?xv=geschwindigkeit
- https://www-demo1.allizom.org/de/firefox/campaign/?xv=privatsphare
- https://www-demo1.allizom.org/de/firefox/campaign/?xv=auf-deiner-seite

### CODE REVIEW

**Comment by alexgibson** [comment]
Depends on https://github.com/mozilla/bedrock/pull/6976

**Comment by alexgibson** [comment]
Ok, this is ready for code review.

**Comment by stephaniehobson** [comment]
#6976 merged and this needs a rebase

**Comment by stephaniehobson** [comment]
`media/img/firefox/new/berlin/ads.png` is being blocked by my ad blocker 😂

**Comment by alexgibson** [comment]
Thanks @stephaniehobson, rebased!

**Pull request merged**
