### PR TITLE
WIP: Add simple dict cache for more speed.

### PR DESCRIPTION
**Pull request by pmclanahan**
This I think will help. Going ahead and submitting the PR for a sanity check.

### CODE REVIEW

**Comment by pmclanahan** [comment]
@jgmize let me know what you think of this direction. Just copied methods from `LocMemCache` that used pickle and removed pickle. Have to be careful of mutating the values, but with p-d and translations that isn't an issue.

**Comment by jgmize** [comment]
@pmclanahan this seems reasonable to me. Slap some unit tests on that and let's ship it :)

**Comment by pmclanahan** [comment]
Added tests from Django. Overkill, but definitely thorough :)

**Comment by jgmize** [comment]
thorough. yes. I think we're covered now.

**Comment by pmclanahan** [comment]
`WIP` tag removed. I think we're good. I did wonder about adding the cleanup to this PR, but I kept them as separate commits and figured that would be good enough :smile_cat:

**Comment by jgmize** [comment]
good enough for me :)

**Pull request merged**
