### PR TITLE
Create reusable macros for Protocol components (#6107)

### PR DESCRIPTION
**Pull request by alexgibson**
## Description
- Creates reusable Jinja macros for protocol components and updates all Protocol bedrock pages to use the shared components.
- This PR does not yet create a macro for the page hero organism (see https://github.com/mozilla/protocol/issues/222).

## Issue / Bugzilla link
#6107

## Testing
Demo: https://bedrock-demo-agibson.oregon-b.moz.works/

Individual pages:

- https://bedrock-demo-agibson.oregon-b.moz.works/en-US/
- https://bedrock-demo-agibson.oregon-b.moz.works/en-US/about/
- https://bedrock-demo-agibson.oregon-b.moz.works/en-US/firefox/pocket/
- https://bedrock-demo-agibson.oregon-b.moz.works/en-US/firefox/features/adblocker/
- https://bedrock-demo-agibson.oregon-b.moz.works/en-US/firefox/new/?xv=chrome
- https://bedrock-demo-agibson.oregon-b.moz.works/en-US/firefox/new/?xv=chrome&v=2
- https://bedrock-demo-agibson.oregon-b.moz.works/en-US/firefox/new/?xv=safari
- https://bedrock-demo-agibson.oregon-b.moz.works/en-US/firefox/new/?xv=safari&v=2
- https://bedrock-demo-agibson.oregon-b.moz.works/en-US/firefox/new/?xv=edge
- https://bedrock-demo-agibson.oregon-b.moz.works/en-US/firefox/new/?xv=edge&v=2
- https://bedrock-demo-agibson.oregon-b.moz.works/en-US/firefox/new/?xv=opera
- https://bedrock-demo-agibson.oregon-b.moz.works/en-US/firefox/new/?xv=opera&v=2
- https://bedrock-demo-agibson.oregon-b.moz.works/en-US/firefox/62.0/whatsnew/
- https://bedrock-demo-agibson.oregon-b.moz.works/en-US/firefox/63.0/whatsnew/
- https://bedrock-demo-agibson.oregon-b.moz.works/en-US/firefox/this-browser-comes-highly-recommended/

Testing:

- [ ] Pages should have no visual difference to production

### CODE REVIEW

**Comment by alexgibson** [comment]
There are pages coming up that will be creating more of these components, so it would be great to try and get this reviewed soon.

**Comment by alexgibson** [comment]
Ok, this PR is already out-of-date :(

I think I may have to put a do-not-merge back on this one, and then try and revisit this again later in the future when review isn't so much of a bottleneck.

**Comment by craigcook** [comment]
Sorry, every time I start to take a look at it I get distracted by something else.

One possible drawback to using macros is that it dictates what elements get used. I'm thinking especially of headings, e.g. the macro has an `h2` but the context in which it's used might call for an `h3` or `h4` instead. Also some are using `section`s but in some cases an `aside` might be preferable. 

I wonder if we can make some elements variable in some cases, at least for headings. Worth discussing at least.

**Comment by alexgibson** [comment]
Yeah, I need to find time to come back to this. I think making heading levels definable should be do-able.

**Comment by alexgibson** [comment]
@craigcook ok this is now rebased and ready for review again.

I've added the ability to set custom heading levels if desired. I've also pushed this to demo, and added a full set of URLs for easier testing.

**Pull request merged**
