### PR TITLE
Fix Issue 7344: Update l10n bedrock docs

### PR DESCRIPTION
**Pull request by aniruddha2000**
## Description
Add the documentation of extracting strings for |10n in the
docs/l10n.rst file.
## Issue / Bugzilla link
https://github.com/mozilla/bedrock/issues/7344

### CODE REVIEW

**Comment by aniruddha2000** [comment]
@amychurchwell @alexgibson have a look.

**Comment by alexgibson** [comment]
@amychurchwell is this something you still see value in having?

**Comment by amychurchwell** [comment]
@alexgibson I think the convo got buried in slack a while back, but I wanted to get your opinion because we are switching to the Fluent system. I think this has a very short shelf-life of being helpful? I'd like to defer to your judgement, because I'm not sure.

**Comment by alexgibson** [comment]
@amychurchwell if you find this content helpful whilst the legacy system is still around, then by all means let's add it. I would expect in the next few months the legacy system will be frozen however, so it's up to you.

**Comment by amychurchwell** [comment]
@alexgibson okay, I'm going to close the issue & PR because our internal doc should suffice in the meantime. 

@aniruddha2000 apologies for the confusion. Thank you very much for the pull request, unfortunately this issue is going to be closed as a WONTFIX.

**Pull request closed without merging**
