### PR TITLE
Use mozmeao dockerhub repo.

### PR DESCRIPTION
**Pull request by glogiotatidis**
See https://github.com/mozmeao/infra/issues/1284

### CODE REVIEW

**Comment by pmac** [comment]
Also these new repos in `mozmeao` don't yet exist. We should do that first right? Or can they be moved?

**Comment by glogiotatidis** [comment]
> The changes look good. But I found more mentions of `mozorg/bedrock` in `.gitlab-ci.yml`.

TIL `rg` requires `--hidden` to search hidden files.

**Comment by glogiotatidis** [comment]
> Also these new repos in `mozmeao` don't yet exist. We should do that first right? Or can they be moved?

`docker push` will create them, no prior action needed.

**Comment by glogiotatidis** [comment]
> > Also these new repos in `mozmeao` don't yet exist. We should do that first right? Or can they be moved?
> 
> `docker push` will create them, no prior action needed.

We can move existing tags from `mozorg` to `mozmeao` if that's valuable?

**Comment by pmac** [comment]
> `docker push` will create them, no prior action needed.

I had no idea it would do that. Neat.

> We can move existing tags from `mozorg` to `mozmeao` if that's valuable?

Nah. No need that I can think of.

**Comment by pmac** [comment]
> TIL `rg` requires `--hidden` to search hidden files.

I used this tip I found in the ripgrep help:

```
Tip: to disable all smart filtering and make ripgrep behave a bit more like classical grep, use 'rg -uuu'.
```

**Comment by glogiotatidis** [comment]
@pmac updated.

**Pull request merged**
