### PR TITLE
Fix Bug 1309692 - Unique page title is missing on the refreshed Foundation pages

### PR DESCRIPTION
**Pull request by kyoshino**
Simply use the page title for `<h1>` on each Foundation page.

### CODE REVIEW

**Comment by alanmoo** [comment]
I think we might want to take a different approach to this. See https://bugzilla.mozilla.org/show_bug.cgi?id=1309692

**Comment by craigcook** [comment]
Putting a DNM on this for the moment while we sort things in the bug. I agree each page should have some kind of sensible title, probably in an h2, and they can all share the common header.

**Comment by craigcook** [comment]
Seems like consensus in the bug is to add `h2`s for each page. 

@kyoshino Do you want to update this PR, or if you're otherwise occupied I can close this and do a new PR to add those headings.

**Comment by alexgibson** [comment]
Closing this as it's stale, and it seems like we want a slightly different approach in the bug.

**Pull request closed without merging**
