### PR TITLE
access policy: Update some old content

### PR DESCRIPTION
**Pull request by sylvestre**

### CODE REVIEW

**Review by stevejalim — APPROVED** [review]
LGTM and works locally. r+ and thanks for the update!

**Comment by stevejalim** [comment]
Note to self/team: this template uses deprecated translation mechanics (we use Fluent rather than Django's gettext-based translation framework now), so will also tag this page for cleanup

Nano-nit that isn't worth fixing, given the above. The following would be nicer as a single line
```
{% trans try='https://wiki.mozilla.org/Build:TryServer'
%}
```

**Comment by sylvestre** [comment]
@stevejalim thanks. could you please also land https://github.com/mozilla/bedrock/pull/11134 ? :)
thanks

**Comment by stevejalim** [comment]
@sylvestre Done - thanks for the poke. Both will be on Dev soon and we'll likely ship to prod after the weekend. Hope that's cool

**Comment by sylvestre** [comment]
perfect, thanks :)

**Pull request merged**
