### PR TITLE
Dockerize bedrock for production

### PR DESCRIPTION
**Pull request by glogiotatidis**
* ~~I'm waiting for #3107 to get merged. Then I will rebase.~~ Rebased of #3107.
* There is a jenkins job that builds against my repository atm https://ci.masterfirefoxos.com/view/www.mozilla.org/job/mozilla_bedrock_docker/ and automatically deploys to
* http://bedrock.masterfirefoxos.com demo
* Everything docker related is under `docker` directory except `Dockerfile`, which we can move when we upgrade to recent docker engine versions 
* Bedrock weights a lot due to static media and locales. Multiple optimizations to bring the image size down to ~550mb. See https://github.com/mozilla/bedrock/pull/3119/files#diff-3254677a7917c6c01f55212f86c57fbfR35

### CODE REVIEW

**Comment by glogiotatidis** [comment]
Rebased of the latest #3107 commit. This run on the new cephless cluster at http://bedrock.masterfirefoxos.com

This is a working solution but not an ideal one, there are still optimizations to be done. Still it is a good base to start our Deis / Docker based deployment workflow and thus I'm removing the WIP flag. @jgmize r?

**Comment by glogiotatidis** [comment]
* Now rebased of master. 
* Build pass https://ci.masterfirefoxos.com/view/www.mozilla.org/job/mozilla_bedrock_docker/41/console

@jgmize r?

**Comment by glogiotatidis** [comment]
I'll be offline this week but feel free to comment / suggest and I'll update on aug 3st.

**Comment by jgmize** [comment]
> I'll be offline this week but feel free to comment / suggest and I'll update on aug 3st.

@glogiotatidis I ran into some issues while testing this that I didn't want to bother you with while you were busy conferencing and vacationing. The main issue revealed itself on https://bedrock.masterfirefoxos.com/en-US/firefox/new/.  The 502 we get from nginx is due to a network error coming from the gunicorn backend-- I traced it down with sysdig to an EAGAIN error, and after diving down that rabbit hole for a while I decided to try an alternate backend.  Due to time constraints I took an alternate approach based on a combination of the work you did in this PR and my [mozorg-env](https://github.com/jgmize/mozorg-env) development repo to deploy apache with mod_wsgi and mod_php to Deis. I don't see us deploying that to Deis in production, but it did provide a good baseline for testing against for the Deis/Nubis evaluation and may prove useful for testing apache config changes outside of our current deployments in PHX1 and SCL3. 

I was wanting to try this PR rebased against master and replacing gunicorn with uWSGI, but I haven't had a chance to do that myself. If you get a chance to try that out I'd be interested in the results.

**Comment by glogiotatidis** [comment]
The problem finally was the aggressive deleting of files, including the media directory, to reduce the resulting docker image size. I don't delete the media directory and the problem is gone now.

I also rebased of the latest bedrock master.

I gunicorn a better server because it's pythonic, simple but not simplistic and fast enough.  uwsgi has given us cryptic errors in the past with masterfirefoxos, see https://bugzilla.mozilla.org/show_bug.cgi?id=1160001

**Comment by glogiotatidis** [comment]
Updates per yesterday's discussion:
 - Added uswgi support with environment variable in `run-prod.sh`
 - Created https://bedrock-uwsgi.masterfirefoxos.org app
 - Created [jenkins job](https://ci.masterfirefoxos.com/view/www.mozilla.org/job/mozilla_bedrock_push_dev_uwsgi/) to autodeploy to the new app 
 - Moved docker requirements to `requiments/docker.txt` to make the separation clear.

I believe that this can be merged as is in bedrock since all the docker changes are clear and do not affect the rest of bedrock.

**Comment by jgmize** [comment]
Awesome work, @glogiotatidis! 

The gunicorn deployment is working well now, and while (as you predicted) we're seeing errors on the uwsgi deployment, I'd like to merge this as-is without blocking on that because the default works well and we now have a good example for evaluating deployment options such as uwsgi.

Thanks again!

**Pull request merged**
