### PR TITLE
Add browser comparison page for Brave (fixes #8807)

### LINKED ISSUE #8807: Code - Update Edge comparison page

### PR DESCRIPTION
**Pull request by sgarrity**
## Description

Add browser comparison page for Brave.

Please note:
1. The browser comparison pages are turned off (redirected) in https://github.com/mozilla/bedrock/pull/8766 — they'll likely all be back on along with this PR going into production.
1. This PR does NOT add Brave to the tables on the main /firefox/browsers/compare/
1. There's a link to the Edge comparison page that I've left out for now, as that page was removed. @craigcook is adding that page back in https://github.com/mozilla/bedrock/issues/8807 — I'll add the link when that PR is merged.

## Issue / Bugzilla link

Fixes: https://github.com/mozilla/bedrock/issues/8616

## Testing

- [ ] compare to the design on https://github.com/mozilla/bedrock/issues/8615
- [ ] compare to the copy here: https://docs.google.com/document/d/1Hy8BHIyCEmyyhJ6V71Y-vyh1_V0vWCkR13-7_5Hbd4s/edit?usp=sharing

### CODE REVIEW

**Comment by craigcook** [comment]
So this could get tricky... we changed over to a different l10n system called Fluent as of last week, so we now mark up and process text strings in a very different format ([docs here](https://bedrock.readthedocs.io/en/latest/l10n.html#fluent)). We'll have to make a bunch of changes to convert this page to Fluent, but I don't know if you want to take on that burden right now. 

I'm in the midst of migrating the other comparison pages to Fluent as well as making the copy updates so it's taking a bit more time to finish. Some of those copy updates include adding Brave to the main page... but the Brave page relies on the Edge page being restored... so we're kind of blocking each other at the moment. I think the smoothest path might be for me to take over the PR once again and bundle the Brave page in with the other pages so they can all go live at the same time. 

That said, if you want to take a stab at converting this page to Fluent first you're welcome to it. But if that looks like a big time-sink and you don't want to burn up the hours I can do that part as I'm converting all the others. Maybe read through [the Fluent docs](https://bedrock.readthedocs.io/en/latest/l10n.html#fluent) and try to guestimate if it's worth your time?

**Comment by sgarrity** [comment]
I think we could circumvent the dependency of the Brave page on the Edge page by just omitting that one Edge link for now. I did wonder about merging these into a shared branch of some kind.

I'll take a look at the Fluent docs. I wouldn't mind getting familiar with working around Fluent for the longer term anyhow. @craigcook Do you have an examples of PRs the converted existing pages to Fluent that you could point me to? Thanks.

**Comment by sgarrity** [comment]
> Do you have an examples of PRs the converted existing pages to Fluent that you could point me to?

Replying to myself already - but I'll take a look at https://github.com/mozilla/bedrock/pull/8939/files as an example

**Comment by craigcook** [comment]
Sorry for the silence. I didn't find any issues initially, and I was leaving this open in case I came across anything while converting it to Fluent. But it's all good and now it's been folded into https://github.com/mozilla/bedrock/pull/8958 so we can close this PR. Nice work!

**Pull request closed without merging**
