### PR TITLE
(no bug) Update legal-docs

### PR DESCRIPTION
**Pull request by kyoshino**
Pick up https://github.com/mozilla/legal-docs/pull/958 and https://github.com/mozilla/legal-docs/pull/959 to update German privacy notices reviewed by a local attorney. I've already checked the changes locally.

### CODE REVIEW

**Comment by peiying2** [comment]
@pmac could you help check on this so we can push it to production?

**Comment by kyoshino** [comment]
@peiying2 can you merge @MikkCZ's latest pull requests on legal-docs? We can push them as well.

**Comment by pmac** [comment]
Everything looks good. Ping me again when the update is done and I'll get it merged. Thanks!

**Comment by kyoshino** [comment]
As per https://github.com/mozilla/legal-docs/pull/962#issuecomment-337335818 the Czech and other changes can be pushed with the next batch. @pmac can you merge this then?

**Pull request merged**
