### PR TITLE
Remove pre-download experiment code from /firefox/ (#6457)

### PR DESCRIPTION
**Pull request by alexgibson**
## Description
- All pre-download experiments have now finished. This PR removes the experiment code from bedrock.

## Issue / Bugzilla link
#6457
#6669

## Testing
- [ ] Make sure I didn't miss any stray references?

### CODE REVIEW

**Comment by alexgibson** [comment]
Do not merge until I get the ok to remove this code.

**Comment by alexgibson** [comment]
@hoosteeno any objection to removing this experiment code?

**Comment by hoosteeno** [comment]
If the experiment were to graduate, would we want this code? If so, please don't remove. If not, go ahead.

**Comment by alexgibson** [comment]
> If the experiment were to graduate, would we want this code? If so, please don't remove. If not, go ahead.

This experiment was written fast and to only ever target a single page. There are also many UX problems it presents, that weren't solved in the experiment. If we want to graduate it, it would need pretty much rewriting from scratch. I think we're OK to remove it 👍

**Pull request merged**
