### PR TITLE
fix #10145:Stop importing forums data

### LINKED ISSUE #10145: Remove import of forums data from community-data repo
With  #10091 we no longer use the forums data from the [community-data repo](https://github.com/mozilla/community-data). We can stop importing it into the database.

### PR DESCRIPTION
**Pull request by Abhra303**
## Description
The forums data will no longer be imported with this PR.
## Issue / Bugzilla link
#10145

### CODE REVIEW

**Comment by stephaniehobson** [comment]
@pmac Can you have a look at this once since you filed the issue?

**Comment by pmac** [comment]
This is looking great. I think there's just one more thing to remove, and that's this section from the `settings/base.py` file:

https://github.com/mozilla/bedrock/blob/56e689ffb64a101d0a3078f7054e536c352f65a9/bedrock/settings/base.py#L692-L695

**Comment by Abhra303** [comment]
Oh yeah thanks!

**Review by pmac — APPROVED** [review]
🥇 Thanks!!

**Pull request merged**
