### PR TITLE
[fix bug 1259552] Add space-themed FxA firstrun page.

### PR DESCRIPTION
**Pull request by jpetto**
## Description
Implement a version of `/firstrun/` with new space theme for A/B testing. Currently en-US only.

## Bugzilla
[bug 1259552](https://bugzilla.mozilla.org/show_bug.cgi?id=1259552)

## Testing
Using latest Fx, navigate to `/en-US/firefox/45.0/firstrun/?v=1` to view new theme.

## Checklist
- [x] Related functional & integration tests passing.

### CODE REVIEW

**Comment by schalkneethling** [comment]
Not introduced here but observed whilst reviewing. Even though these pages are aimed at desktop only, we do, do some responsive styling, and the form container seems just a bit to tight on 480px and less.

screen shot 2016-04-04 at 14 49 44

**Comment by schalkneethling** [comment]
Other than my one comment above, this is an r+ :space_invader:

**Comment by jpetto** [comment]
@schalkneethling - Added some improvements for the mobile views. Will squash if you think it's ready to go!

**Comment by schalkneethling** [comment]
Looks great! Feel free to squash.

**Comment by jpetto** [comment]
Squarshed!

**Pull request merged**
