### PR TITLE
Bug 1130565. Add more localized videos to Hello page.

### PR DESCRIPTION
**Pull request by jpetto**

### CODE REVIEW

**Comment by jpetto** [comment]
[Waiting for verification from ckprice](https://bugzilla.mozilla.org/show_bug.cgi?id=1130565#c3) that PR intent is correct.

Pretty confident intent is indeed correct, so should be good to review.

**Comment by ckprice** [comment]
Mapping of URL's to locales is good. Default to en-US is good. Ready for a review.

**Comment by alexgibson** [comment]
Tested all the new additions locally and they play as expected, en-US fallback for locales not in the list works fine too.

Haven't merged this yet as there's still a label on the PR, but otherwise it's an r+

**Comment by jpetto** [comment]
@ckprice - According to [the bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1119046#c70), it looks like all videos are complete. Can you confirm? Is this change good to merge and push?

**Comment by ckprice** [comment]
Thanks for checking Jon. Confirming with Spencer and Rainer that the CDN
versions are good to go, will have an answer today.

On Wednesday, February 18, 2015, Jon Petto <notifications@github.com> wrote:

> @ckprice <https://github.com/ckprice> - According to the bug
> <https://bugzilla.mozilla.org/show_bug.cgi?id=1119046#c70>, it looks like
> all videos are complete. Can you confirm? Is this change good to merge and
> push?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/bedrock/pull/2746#issuecomment-74872404>.
>


-- 
Cory Price
/ckprice

**Comment by ckprice** [comment]
CDN cache has cleared - you're GTG!

**Comment by jpetto** [comment]
@alexgibson - Merge when ready!

**Comment by alexgibson** [comment]
Arrrrr + :anchor:

**Pull request merged**
