### PR TITLE
Add Code of Conduct notice

### PR DESCRIPTION
**Pull request by pmac**
Copied from:
https://github.com/mozilla/addons-server/blob/master/CODE_OF_CONDUCT.md

Thanks to @andymckay

### CODE REVIEW

**Comment by pmac** [comment]
@mozilla/webdev-bedrock andym posted about this in #webdev and it seemed like a good idea to me. Probably also belongs in [sugardough](https://github.com/mozilla/sugardough). Thoughts?

**Comment by pmac** [comment]
Could also just be an addition to the README I guess.

**Comment by alexgibson** [comment]
I like this. Even though GitHub doesn't do anything with the file in particular, I agree it's useful to have around. Another place for it to live could be in CONTRIBUTING.md?

**Comment by pmac** [comment]
CONTRIBUTING.md does make a lot of sense. I think posting it to both README and CONTRIBUTING might be fine. I'll update and see how it looks.

**Comment by alexgibson** [comment]
LGTM, r+

**Pull request merged**
