### PR TITLE
Fix Bug 1221826, update header and footer donate urls en-US only

### PR DESCRIPTION
**Pull request by schalkneethling**
@jpetto r?

### CODE REVIEW

**Comment by schalkneethling** [comment]
Need to wait for bug 1221736 to be resolved before merging this. Just to avoid the links ending up in production before.

**Comment by jpetto** [comment]
Code looks good. r+

From the bug and local testing, it appears the `donate.mozilla.org` links seamlessly redirect to `sendto.mozilla.org`. We sure we need to wait to merge?

**Comment by schalkneethling** [comment]
@jpetto if it redirects with no problem, then let's merge this. The reason I was holding off was because one of the comments said the links do not work. I assume the person actually meant, they are still being redirected.

**Comment by jpetto** [comment]
Verified links are redirecting properly. When redirect is removed, link will correctly send user to `donate.mozilla.org`. Merge time!

**Pull request merged**
