### PR TITLE
Remove Enterprise download "packages"

### LINKED ISSUE #8424: Find a better hosting solution for /enterprise package downloads
## Description

See: https://bugzilla.mozilla.org/show_bug.cgi?id=1608659

TL:DR: box.com does not work in legacy browsers.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Box.com links are replaced by a self-hosted solution.

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] The /enterprise team need to be able to update the URL autonomously.

### PR DESCRIPTION
**Pull request by devinreams**
## Description

⏰ URGENT: these box.com links are now removed and outdated and should be removed from the website ASAP.

- This PR removes the download links/buttons for the packages that were manually created and hosted at box.com.

- It also adds direct links to the various items that Enterprise/ESR folks may want to quickly access (this keeps everything in one useful location).

- ⚠️ I don't know if we have a best practice for hosting a static (PDF) file? If so then the "Deployment guide" should go there and link there. Otherwise, this PR comments those out so as to not block deploying the page change.

## Issue / Bugzilla link

Resolves #8424 

## Testing

Before:

Screen Shot 2020-02-06 at 10 11 21 AM

After:

Screen Shot 2020-02-06 at 10 08 07 AM

### CODE REVIEW

**Comment by craigcook** [comment]
> I don't know if we have a best practice for hosting a static (PDF) file? If so then the "Deployment guide" should go there and link there. Otherwise, this PR comments those out so as to not block deploying the page change.

We can put PDFs on assets.mozilla.net and link there. If you can send me the files I can upload them and give you the final URLs. Or, given the urgency, we can merge this as-is and get it live then add the PDFs links in a follow-up.

**Comment by devinreams** [comment]
Thanks, @craigcook!

Here's the "Deployment guide" file to host on `assets.mozilla.net`:
- https://drive.google.com/file/d/1sbF9ghhFa2fZek7NFAjXJabak3R02Enl/view
- [Firefox for Enterprise Browser Deployment Guide.pdf](https://github.com/mozilla/bedrock/files/4166873/Firefox.for.Enterprise.Browser.Deployment.Guide.pdf)

Once it's hosted can you please un-comment the bullets and add the link accordingly? I really appreciate it. 🙇

**Comment by craigcook** [comment]
> Once it's hosted can you please un-comment the bullets and add the link accordingly? I really appreciate it. 🙇

https://assets.mozilla.net/pdf/Firefox.for.Enterprise.Browser.Deployment.Guide.pdf

Evidently it was already uploaded some time ago, but I've re-uploaded just to make sure this is the latest version.

**Comment by craigcook** [comment]
Closing this PR in favor of https://github.com/mozilla/bedrock/pull/8492 which adds the PDF links and updates functional tests.

**Pull request closed without merging**
