### PR TITLE
[fix bug 1398278] Update to the Websites Privacy Notice

### PR DESCRIPTION
**Pull request by alexgibson**
https://bugzilla.mozilla.org/show_bug.cgi?id=1398278

### CODE REVIEW

**Comment by flodolo** [comment]
Ugh, dead link to https://gecko.readthedocs.io/ :-\

**Comment by alexgibson** [comment]
I can't fix the dead link here, but I'll open an issue on the legal-docs repo

**Comment by alexgibson** [comment]
Filed issue https://github.com/mozilla/legal-docs/issues/886

**Comment by alexgibson** [comment]
Fwiw, it looks like the link is 404 already even before this pull request :(

**Comment by flodolo** [comment]
Yes, it's been down for at least one week, maybe two. I didn't realize we were linking to it in legal docs.

**Pull request merged**
