### PR TITLE
Add functional tests for contact pages

### PR DESCRIPTION
**Pull request by davehunt**
Here are the functional tests for the contact pages, to replace those currently in https://github.com/mozilla/mcom-tests/blob/master/tests/test_contact.py, excluding the link checks. Note that this contains the changes from (and is therefore blocked by) https://github.com/mozilla/bedrock/pull/3625.

@alexgibson r? and please let me know which of these (if any) should be sanity tests.

### CODE REVIEW

**Comment by alexgibson** [comment]
@davehunt can you please rebase this branch now that I've merged #3625, thanks!

**Comment by davehunt** [comment]
@alexgibson done!

**Comment by alexgibson** [comment]
Let's remove the relevant casper tests as part of this PR: https://github.com/mozilla/bedrock/blob/master/tests/functional/contact.js

**Comment by davehunt** [comment]
> Let's remove the relevant casper tests as part of this PR: https://github.com/mozilla/bedrock/blob/master/tests/functional/contact.js

Done. I've also updated the documentation with regards to running the tests in parallel.

**Comment by alexgibson** [comment]
LGTM, care to squash? r+

**Comment by davehunt** [comment]
@alexgibson squashed!

**Pull request merged**
