### PR TITLE
Fix token server uri for testing

### PR DESCRIPTION
**Pull request by vladikoff**

### CODE REVIEW

**Comment by alexgibson** [comment]
Thanks @vladikoff! I tested this on our demo environment, but this still does not seem to work :(

**Comment by alexgibson** [comment]
Not sure if this is expected or not, but if I search for `services.sync.tokenServerURI` in `about:config` the pref does not seem to be listed?

**Comment by vladikoff** [comment]
Works for me with our fxa-local-dev configuration:

**Comment by alexgibson** [comment]
Hmm... will give this another try

**Comment by vladikoff** [comment]
> Not sure if this is expected or not, but if I search for services.sync.tokenServerURI in about:config the pref does not seem to be listed?

Here's what I got:

**Comment by vladikoff** [comment]
@alexgibson try adding the identity one as well and make sure it is modified like the screenshot above https://github.com/mozilla/fxa-local-dev/blob/master/_scripts/profile.js#L105

**Comment by alexgibson** [comment]
This still doesn't seem to be working quite right, even with a new profile. There must be another difference between our config and the one you link to. I'll try and see if I can figure it out.

**Comment by alexgibson** [comment]
Together with #3835 we now have the issue fixed. Thanks @vladikoff :beer:

**Pull request merged**
