### PR TITLE
Redirect windows-10 welcome: fix bug 1187343

### PR DESCRIPTION
**Pull request by jgmize**

### CODE REVIEW

**Comment by jgmize** [comment]
@pmclanahan or @alexgibson r?

**Comment by alexgibson** [comment]
Do we still need a pass-though redirect in global.conf for it to get to this redirect?

**Comment by jgmize** [comment]
> Do we still need a pass-though redirect in global.conf for it to get to this redirect?

Good catch, yes we do. Updating.

**Comment by jgmize** [comment]
Updated to include global.conf PT

**Comment by alexgibson** [comment]
r+ :speedboat:

**Pull request merged**
