### PR TITLE
Replace obsolete tests for vary: user-agent

### PR DESCRIPTION
**Pull request by jgmize**
@pmclanahan r?

### CODE REVIEW

**Comment by pmclanahan** [comment]
To get those tests passing you have to have the custom vary header management middleware enabled. The issue is that we're now using these tests in multiple contexts. Maybe we should just enable said middleware at all times now? At the very least we need to change travis to have that middleware enabled so that these tests pass.

**Comment by jgmize** [comment]
Thanks @pmclanahan, I added a commit to enable VaryNoCacheMiddleware by default.

**Comment by jgmize** [comment]
> Thanks @pmclanahan, I added a commit to enable VaryNoCacheMiddleware by default.

... which naturally broke a couple of other tests that are expecting the previous default behavior. Working on a fix for that now.

**Comment by pmclanahan** [comment]
LGTM. r+

Feel free to merge after tests pass and commits are squarshed.

:beers:

**Comment by jgmize** [comment]
Tests finally pass; squashing.

**Pull request merged**
