### PR TITLE
Remove pre-download experiment code (#5944)

### PR DESCRIPTION
**Pull request by alexgibson**
## Description
- Removes experiment code added in https://github.com/mozilla/bedrock/pull/5999

DNM until I get the OK to remove this.

## Issue / Bugzilla link
#5944

## Testing
- Double check I didn't miss any stray references?

### CODE REVIEW

**Comment by alexgibson** [comment]
@ejregithub are we ok to remove the experiment code here? This would never be reusable for anything past just an experiment, so if we're satisfied that the test is over, I see no real benefit in keeping it around.

**Comment by djst** [comment]
Results suggest the experiment was fairly successful. No drop in downloads, increase in signups (though poor opt-in clicks from confirmation email). I think the next step is to iterate on the experiment rather than removing the code.

**Comment by alexgibson** [comment]
> Results suggest the experiment was fairly successful. No drop in downloads, increase in signups (though poor opt-in clicks from confirmation email). I think the next step is to iterate on the experiment rather than removing the code.

Before we start to iterate on this, It would be good to see a throough analysis of the results before we draw any solid conclusions. The data I've seen suggests that there was a drop in downloads, which others have also commented on - so there may be some ambiguity here in how people interpret the data. We should also survey the quality of emails entered, to wokr out if there we're a high number of bugus emails entered (the high drop off in confirmations may be a clue to this).

**Comment by alexgibson** [comment]
@djst just checking in on the status here. Now that the data has been more thoroughly analysed, are we good to go ahead and remove this left-over code?

**Comment by alexgibson** [comment]
> If we'll iterate on pre-download experiments, will the new test be so different that we'll not need this code? If so, I'm fine with removing this.

Everything is in Git history, so nothing is lost even if we did decide to reuse any of this.

**Comment by alexgibson** [comment]
> If we'll iterate on pre-download experiments, will the new test be so different that we'll not need this code? If so, I'm fine with removing this.

Everything is in Git history, so nothing is lost even if we did decide to reuse any of this.

**Comment by alexgibson** [comment]
> If we'll iterate on pre-download experiments, will the new test be so different that we'll not need this code? If so, I'm fine with removing this.

Everything is in Git history, so nothing is lost even if we did decide to reuse any of this.

**Comment by alexgibson** [comment]
> If we'll iterate on pre-download experiments, will the new test be so different that we'll not need this code? If so, I'm fine with removing this.

Everything is in Git history, so nothing is lost even if we did decide to reuse any of this

**Comment by alexgibson** [comment]
Ok, this is rebased and ready for review.

**Comment by stephaniehobson** [comment]
R+ ✨

**Comment by stephaniehobson** [comment]
Waiting for master to turn green so I can do a push. I'll leave this unmerged for now.

**Pull request merged**
