### PR TITLE
Update l10n.rst

### PR DESCRIPTION
**Pull request by Shivansh2407**
## Description
Update l10n bedrock docs #7344

### CODE REVIEW

**Comment by Shivansh2407** [comment]
What should be done here next?

**Comment by amychurchwell** [comment]
@Shivansh2407 thank you for the PR, it will be reviewed as soon as someone as the bandwidth. We review pull requests by priority level. 🙂

**Comment by alexgibson** [comment]
@Shivansh2407 hi, are you still working on this PR?

**Comment by Shivansh2407** [comment]
Yes but can you clearly explain me what to do next?

**Comment by alexgibson** [comment]
> Yes but can you clearly explain me what to do next?

You need to format the documentation in the correct format. See comment above for link to the relevant documentation. You'll need to read the docs, implement the changes, test them locally - and once they are rendering correctly, update the pull request here.

**Comment by alexgibson** [comment]
@Shivansh2407 hi, are you still working on this issue?

**Comment by alexgibson** [comment]
Closing due to inactivity, as another contributor may wish to work on this. Please feel free to reopen if you're still working on it. Thanks

**Pull request closed without merging**
