### PR TITLE
Fix bug 1014823 redirect

### PR DESCRIPTION
**Pull request by jgmize**
Fix pushed to demo4: https://www-demo4.allizom.org/firefox/releases/whatsnew/

### CODE REVIEW

**Comment by jpetto** [comment]
r+ on the change, but still a bit confused as to why the pass-through was causing errors for this rewrite and not, say, the rewrite on line 221:

`RewriteRule ^/(\w{2,3}(?:-\w{2})?/)?projects(/?)$ /b/$1projects$2 [PT]`

Was it due to the [regex handling of `/whatsnew/` URLs in `firefox/urls.py`](https://github.com/mozilla/bedrock/blob/master/bedrock/firefox/urls.py#L67)?

**Comment by jpetto** [comment]
Also, should this PR remove the rewrite rule (that was added earlier today) on line 879?

`RewriteRule ^/en-US/firefox/en-US/firefox/whatsnew/$ /en-US/firefox/whatsnew/ [L,R=301]`

**Comment by jgmize** [comment]
@jpetto yes, I've updated this PR to remove the now-redundant rule since this fixes the root cause, but no, I don't think the whatsnew regex in firefox/urls.py is sufficient to explain the redirect from /firefox/releases/whatsnew/ to /firefox//en-US/firefox/whatsnew/ -- I think the explanation is somewhere in the interaction between the 41 whatsnew redirects still in the [.htaccess file in svn](http://viewvc.svn.mozilla.org/vc/projects/mozilla.com/trunk/.htaccess?view=markup) and possibly [this other .htaccess file in svn](http://viewvc.svn.mozilla.org/vc/projects/mozilla.org/trunk/projects/firefox/.htaccess?view=markup#l59), but I'm not sure *exactly* where at this point.

**Comment by jpetto** [comment]
Forty-one! :see_no_evil:

**Pull request merged**
