### PR TITLE
Fix Bug 1209708 - [traceback] exceptions:UnicodeEncodeError: 'ascii' codec can't encode character u'\u2211' in position 10: ordinal not in range(128)

### PR DESCRIPTION
**Pull request by kyoshino**

### CODE REVIEW

**Comment by stephendonner** [comment]
@jgmize @pmclanahan r?

**Comment by pmclanahan** [comment]
@kyoshino mind adding a test with the problem URL to the `test_redirects` suite?

**Comment by jgmize** [comment]
> @kyoshino mind adding a test with the problem URL to the test_redirects suite?

@pmclanahan I don't think @kyoshino has that information, b/c it isn't in the bug. Looking at the info about the error in New Relic, I see the escaped version of the malformed URL:
`/it/thunderbird/2.0.0.23/start/NBVC%e2%88%91BNM` but a proper test would include the the original junk data instead of the escaped equivalent, and I'm not sure if that should necessarily be a blocker for this PR.

**Comment by kyoshino** [comment]
I guess new tests are not necessary here, because it's caught by a recently added test :smiley_cat:

**Comment by pmclanahan** [comment]
@jgmize when I paste the url you included in your comment into my browser on `www.mozilla.org` I get a 500. So I think it'd be a good test to add to the suite to make sure that's a 404 instead.

**Comment by pmclanahan** [comment]
@kyoshino well that's why I asked. Our tests are currently passing but this URL is throwing a 500.

**Comment by kyoshino** [comment]
Hmm, will take a look tomorrow.

**Comment by jgmize** [comment]
> @jgmize when I paste the url you included in your comment into my browser on www.mozilla.org I get a 500. So I think it'd be a good test to add to the suite to make sure that's a 404 instead.

I should have realized that copying and pasting it into the URL bar would unescape it automatically and render as /it/thunderbird/2.0.0.23/start/NBVC∑BNM. Thanks for pointing that out, @pmclanahan. I can understand the desire for a specific test case for this junk URL, I just want to make sure we don't start "enumerating badness"-- there are many possible urls that may throw unicode errors similar to the one we saw in this bug that are out of scope of this PR.

**Comment by pmclanahan** [comment]
Agreed. But it'd be nice to have one to verify this I think, and should cover the full range of errors of this type for this URL. It's not really a big deal, it just seemed like the kind of thing that'd be easy to reintroduce later.

**Comment by kyoshino** [comment]
I cannot reproduce 500 locally. It just says 404.

**Comment by pmclanahan** [comment]
Cool. We'll just get this in then.

**Pull request merged**
