### PR TITLE
[fix bug 1205282] Enable auto-downloads for IE 9 and above on scene 2 of /firefox/new/

### PR DESCRIPTION
**Pull request by alexgibson**
Still need to push this to a demo for testing, so marking as do-not-merge for now.

### CODE REVIEW

**Comment by jpetto** [comment]
A rebased version of this branch (to fix the demo deploy issues) is now on demo4. I created a new branch (named `bug-1205282-enable-auto-downloads-ie9-and-above-firefox-new-REBASED`) just in case you had local changes that hadn't been pushed yet. This is the branch on demo4.

Code and tests are looking good. Tested in IE 7, 8, and 9, clicking downloadbutton from the home page and from `/firefox/new/`. Download behavior was as expected in each test.

r+ from me, but should be tested by others to verify all is well.

**Comment by alexgibson** [comment]
Thanks for putting this up on a demo, Jon! I'm going to test this on my VM's & Windows machine soon (just been caught up in other things) - great to hear it looks good :+1:

**Comment by alexgibson** [comment]
@jpetto - I've rebased this branch against the latest master and pushed to demo4. All seems well to me on IE6-11, plus Edge :+1:

**Comment by alexgibson** [comment]
Going to get some QA help on double-checking this one before we merge.

**Comment by alexgibson** [comment]
Rebecca has tested both IE 9 & 10 for auto-download on scene2 and verified things are looking good [in the bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1205282#c6) :+1:

**Comment by jpetto** [comment]
It's time! :fire:

**Pull request merged**
