### PR TITLE
Bug 1261810 - Bring back the system requirements link

### PR DESCRIPTION
**Pull request by sylvestre**

### CODE REVIEW

**Comment by sylvestre** [comment]
@jgmize Can you review this patch or should it be someone else?

**Comment by sylvestre** [comment]
@pmclanahan Paul, do you have some bandwidth to review this? Thanks

**Comment by pmclanahan** [comment]
We've been talking about it. We're trying to figure out how best to get this done.

**Comment by sylvestre** [comment]
@pmclanahan any news?

**Comment by pmclanahan** [comment]
@sylvestre sorry for the delay. I know we can't merge this as is, but I'm not sure what we need to do to accomplish what you want. @jgmize may have more info.

**Comment by jgmize** [comment]
Hi @sylvestre, this will cause *all* of the release notes to lose the link to the sumo article, and only newer releases currently have actual system requirements text. Are you planning on adding historical system requirements, or would you like to add a version check and continue linking older releases to the sumo article?

**Comment by jgmize** [comment]
@sylvestre I'm going to go ahead and close this out due to inactivity; if you want to pursue this feel free to reopen and let's make sure it has the behavior you want.

**Comment by sylvestre** [comment]
Sorry for dropping the ball here. 
Maybe I can try to improve it @jgmize 
If I check if the content of the system requirement system is not null, I use the content, otherwise, I fallback on the SUMO URL. Who that work?
Thanks

**Pull request closed without merging**
