### PR TITLE
Add WNP 66 l10n copy

### PR DESCRIPTION
**Pull request by amychurchwell**
## Description
Contains [final copy](https://docs.google.com/document/d/1vuNn8ct1ub0DAwz2YivEmNIDwP2yR4NtAmo8FSR6LnA/edit?usp=sharing) for translation.

## Issue / Bugzilla link
#6736

### CODE REVIEW

**Comment by amychurchwell** [comment]
@ejregithub final copy for WNP66 ready for l10n. 🙂

**Comment by ejregithub** [comment]
@peiying2 - flagging this one for string extraction, please. This is final copy for the /whatsnew page intended for the Firefox 66 release on 3/19.

**Comment by peiying2** [comment]
Once we have the demo URL (pending design finalization), I will prep the strings for l10n.

**Comment by peiying2** [comment]
Localization targets 3/7 to complete as many locales as possible in order to prepare the locale list for the rel eng group.

**Comment by peiying2** [comment]
@amychurchwell We need to check with the copyrwriter for this one. 

A comment from one of our l10n contributor questions the use of some of the common phrases and they appear different from the past. Has the style changed?

"...and when you’re signed into your Account," should be  "... signed in to ..." instead?
"One log-in. Power and security everywhere", shouldn't it be "One login..." - there are two instances in this file

Of course the strings are leveraged from the firefox/accounts-2018 template. So both files need to be reviewed. 

In checking on how they were used before here: https://transvision.mozfr.org/, the common expressions are "login" and "sign in to...".

We have extracted strings from this one so any revision will require a tag. If we make changes here, are we going firefox/accounts-2018 template too?

**Comment by amychurchwell** [comment]
@peiying2 I checked in with the copywriter, this is not an intentional style change. We are wanting to keep the original style of "login" and "sign in to..."
Seeing as the strings have been extracted, when I submit the final PR with design I will tag copy changes for these instances. Thank you for calling this out. :+1:

**Comment by alexgibson** [comment]
The WNP for FF 66 was merged in https://github.com/mozilla/bedrock/pull/6883, so I think we can close this one now.

**Pull request closed without merging**
