### PR TITLE
[fix bug 1231201] /firefox/new/ performance test v2/4.

### PR DESCRIPTION
**Pull request by jpetto**
- v2: Custom/slim sandstone & buttons CSS
- v4: Async fonts, custom sandstone, no optimizely

### CODE REVIEW

**Comment by jpetto** [comment]
Shortcut for reviewer - `new-v2.less` is nearly identical to pre-existing `new.less`. Only change is removing three unused selectors.

**Comment by schalkneethling** [comment]
Not introduced by this PR, but when the "Your system doesn't meet...." it is offset to the left. Seeing that everything else is centered, perhaps we should center this as well?

screen shot 2015-12-15 at 10 58 53

This uses the follow class values on the html element:
`oldmac armv7 js arm armv7up loaded`

Screen size is 320 x 533

**Comment by schalkneethling** [comment]
r+wc :speedboat:

**Comment by jpetto** [comment]
Opened #3660 to address unsupported platforms UX issue.

**Comment by schalkneethling** [comment]
r+ :chocolate_bar:

**Pull request merged**
