### PR TITLE
Migrate community-hotline CPG page to fluent. (#9666)

### PR DESCRIPTION
**Pull request by amychurchwell**
## Description
Migrates /about/governance/policies/participation/reporting/community-hotline/ to fluent.

## Issue / Bugzilla link
#9666 

## Testing
http://localhost:8000/en-US/about/governance/policies/participation/reporting/community-hotline/

### CODE REVIEW

**Comment by alexgibson** [comment]
@amychurchwell i would suggest running the migration for the existing translations, and submitting those for review in the L10n repo first before marking this as ready for review. If Peiying request any changes it’s much easier to re-run the migration here first, vs doing it again later.

**Comment by amychurchwell** [comment]
migrations for existing translations have been merged

**Review by alexgibson — CHANGES_REQUESTED** [review]
The migration looks good 👍 

As you have already done the migration manually, please amend your commit to end with `[skip l10n]` in order to avoid triggering the usual automation. See: https://bedrock.readthedocs.io/en/latest/fluent-conversion.html#commit

Also, I'm assuming you're tackling these pages one by pne (there seem to be a couple more mentioned in the issue that also need migrating?). That's fine if so, just making sure something hasn't slipped through the cracks.

**Comment by amychurchwell** [comment]
@alexgibson thanks for the review! updated the commit msg to end with [skip l10n]
I thought it would be easier for reviews (www-l10n and bedrock) to do each page separately. policies/participation is coming up next, which has more l10n tag complications to de-tangle.

**Review by alexgibson — APPROVED** [review]

**Pull request merged**
