### PR TITLE
Update browser-history.html

### PR DESCRIPTION
**Pull request by petercpg**
## Description
Just fixing typo "NSCA" -> "NCSA".

### CODE REVIEW

**Comment by petercpg** [comment]
Hi @amychurchwell and thanks for the reminder. :) See if this works.

**Comment by petercpg** [comment]
I can file another pull request to mozilla-l10n to fix this up too, if this helps:
```
cy/mozorg/browser-history.lang
en-GB/mozorg/browser-history.lang
de/mozorg/browser-history.lang
fr/mozorg/browser-history.lang
zh-TW/mozorg/browser-history.lang
en-CA/mozorg/browser-history.lang
en-US/mozorg/browser-history.lang
cs/mozorg/browser-history.lang
```

**Comment by amychurchwell** [comment]
@petercpg if you would like to update the lang files directly, we wouldn't even need a switch. 💡

**Comment by peiying2** [comment]
@petercpg if it is easy for you to do it here, feel free. Otherwise, I can make the changes in Pontoon directly. My question is, do you have a script to identify those that need to be updated? I can't imagine myself checking it locale by locale, :).

**Comment by amychurchwell** [comment]
@peiying2 the only locales for this file are:
```
cy/mozorg/browser-history.lang
en-GB/mozorg/browser-history.lang
de/mozorg/browser-history.lang
fr/mozorg/browser-history.lang
zh-TW/mozorg/browser-history.lang
en-CA/mozorg/browser-history.lang
en-US/mozorg/browser-history.lang
cs/mozorg/browser-history.lang
```

**Comment by petercpg** [comment]
@amychurchwell Here's a change to reduce change to NCSA only. Once it gets merged (maybe merge with squash?) I'll work with @peiying2 to fix the langfiles. 

@peiying2 the simple command is running `git grep -l "NSCA"` at the root folder of git repo. If you have ripgrep installed you can also use `rg "NSCA"` as it searches much faster.

**Pull request merged**
