### PR TITLE
Bug 1171763 - Delete two pages in research and remove from nav

### PR DESCRIPTION
**Pull request by malena**
https://bugzilla.mozilla.org/show_bug.cgi?id=1171763

### CODE REVIEW

**Comment by alexgibson** [comment]
This change looks good, thanks @malena! 

I noticed there are still a couple of links to the deleted pages here that also need removing: https://github.com/mozilla/bedrock/blob/master/bedrock/research/templates/research/research.html#L37-L44

Also, is it worth adding a redirect for the two removed URL's back to `/research`, should they be linked from anywhere else?

**Comment by alexgibson** [comment]
I think these four URL patterns can also be removed: https://github.com/mozilla/bedrock/blob/master/bedrock/research/urls.py#L10-L13

Looks like `research/collaborations` and `research/publications` are danglers that shouldn't be there, perhaps they can be tidied up in the redirect too?

**Comment by malena** [comment]
@alexgibson Cleaned up.

**Comment by alexgibson** [comment]
This looks great thanks @malena! r+ :tangerine:

**Pull request merged**
