### PR TITLE
Add a script for properly tagging a release

### PR DESCRIPTION
**Pull request by pmclanahan**

### CODE REVIEW

**Comment by jgmize** [comment]
Should this script include a `git fetch --tags`?

**Comment by pmclanahan** [comment]
I assumed that the instructions from #3961 had been followed, but that's not a bad idea. I'll add it. Can't hurt.

**Comment by pmclanahan** [comment]
@jgmize I added it, but it may not help since we can't know that the user has the master branch configured to fetch from the mozilla repo, and we can't know the name of the remote that points to mozilla :/ So I think this is as good as we get.

**Comment by jgmize** [comment]
Thanks @pmclanahan

**Pull request merged**
