### PR TITLE
Fix bug 1225907: alter robots.txt based on hostname from request

### PR DESCRIPTION
**Pull request by pmclanahan**

### CODE REVIEW

**Comment by pmclanahan** [comment]
My local tests are failing in an odd way seemingly unrelated to this change. Waiting to see what Travis says.

**Comment by pmclanahan** [comment]
Yeah. Very odd seemingly l10n related test failure. @jgmize any ideas here?

**Comment by pmclanahan** [comment]
I just had Travis rebuild master and it passed O_O

**Comment by jgmize** [comment]
I wanted to replicate this in a clean environment to try and troubleshoot, but I ended up with even more issues:

I get the following errors off master:
```
======================================================================
FAIL: test_format_identifier_mismatch (lib.l10n_utils.tests.test_dotlang.TestDotlang)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/test/utils.py", line 216, in inner
    return test_func(*args, **kwargs)
  File "/app/lib/l10n_utils/tests/test_dotlang.py", line 194, in test_format_identifier_mismatch
    eq_(len(mail.outbox), 1)
AssertionError: 0 != 1

======================================================================
FAIL: test_parse_utf8_error (lib.l10n_utils.tests.test_dotlang.TestDotlang)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/test/utils.py", line 216, in inner
    return test_func(*args, **kwargs)
  File "/app/lib/l10n_utils/tests/test_dotlang.py", line 162, in test_parse_utf8_error
    eq_(len(mail.outbox), 1)
AssertionError: 0 != 1

----------------------------------------------------------------------
Ran 719 tests in 26.179s

FAILED (SKIP=1, failures=2)
Destroying test database for alias 'default'...
```

This is *after* cloning the locale dir as specified in http://bedrock.readthedocs.org/en/latest/install.html#localization

With this branch, in the same environment, I get the following test failures:

```
======================================================================
FAIL: test_invalid_newsletter_is_error (bedrock.newsletter.tests.test_forms.TestNewsletterFooterForm)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/mock.py", line 1201, in patched
    return func(*args, **keywargs)
  File "/app/bedrock/newsletter/tests/test_forms.py", line 266, in test_invalid_newsletter_is_error
    self.assertEqual(form.errors['newsletters'], [u'This field is required.'])
AssertionError: [u'Este campo \xe9 obrigat\xf3rio.'] != [u'This field is required.']

======================================================================
FAIL: test_newsletter_no_order (bedrock.newsletter.tests.test_views.TestExistingNewsletterView)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/mock.py", line 1201, in patched
    return func(*args, **keywargs)
  File "/app/bedrock/newsletter/tests/test_views.py", line 425, in test_newsletter_no_order
    newsletters_in_order)
AssertionError: Lists differ: [u'mozilla-and-you', u'firefox... != [u'firefox-tips', u'mozilla-an...

First differing element 0:
mozilla-and-you
firefox-tips

- [u'mozilla-and-you', u'firefox-tips']
+ [u'firefox-tips', u'mozilla-and-you']

======================================================================
FAIL: test_returns_ajax_errors (bedrock.newsletter.tests.test_views.TestNewsletterSubscribe)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/mock.py", line 1201, in patched
    return func(*args, **keywargs)
  File "/app/bedrock/newsletter/tests/test_views.py", line 550, in test_returns_ajax_errors
    self.assertIn('privacy', resp_data['errors'][0])
AssertionError: 'privacy' not found in u'Voc\xea deve concordar com a pol\xedtica de privacidade'

======================================================================
FAIL: test_returns_failure (bedrock.newsletter.tests.test_views.TestNewsletterSubscribe)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/mock.py", line 1201, in patched
    return func(*args, **keywargs)
  File "/app/bedrock/newsletter/tests/test_views.py", line 661, in test_returns_failure
    self.assertIn('privacy', doc('#footer-email-errors .errorlist li').eq(0).text())
AssertionError: 'privacy' not found in u'Voc\xea deve concordar com a pol\xedtica de privacidade'

======================================================================
FAIL: test_format_identifier_mismatch (lib.l10n_utils.tests.test_dotlang.TestDotlang)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/test/utils.py", line 216, in inner
    return test_func(*args, **kwargs)
  File "/app/lib/l10n_utils/tests/test_dotlang.py", line 194, in test_format_identifier_mismatch
    eq_(len(mail.outbox), 1)
AssertionError: 0 != 1

======================================================================
FAIL: test_parse_utf8_error (lib.l10n_utils.tests.test_dotlang.TestDotlang)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/test/utils.py", line 216, in inner
    return test_func(*args, **kwargs)
  File "/app/lib/l10n_utils/tests/test_dotlang.py", line 162, in test_parse_utf8_error
    eq_(len(mail.outbox), 1)
AssertionError: 0 != 1

----------------------------------------------------------------------
Ran 718 tests in 24.065s

FAILED (SKIP=1, failures=6)
Destroying test database for alias 'default'...
```

**Comment by pmclanahan** [comment]
Those ones from your `master` run are I believe due to not having any `MANAGERS` or `ADMINS` defined in your settings. The others match what I'm seeing in my branch.

**Comment by jgmize** [comment]
You're right, running the tests with `ADMINS='["admin@example.com"]' ./manage.py test`, both of the `TestDotLang` tests pass. Assuming those tests are still worth keeping, we should follow up later to add an `override_settings` decorator for that.  The other four from my previous example output still fail in this branch-- you're saying that you get those exact same four failures locally? On the one hand, I'm getting the exact same failure on the `test_invalid_newsletter_is_error` failure, but on the other it's odd that travis isn't getting the other three failures. Regardless, I'm leaning towards this being an artifact of the unit tests themselves, and if you want to just remove the `TestRobots` class entirely with this PR, we can follow up with an integration test for robots.txt that would be more valuable anyway.

**Comment by pmclanahan** [comment]
Yup. Exact same set of failures. Those error messages come from Django itself and are translated unexpectedly, so my guess at this point is that altering the number of tests has affected test order and some other test is setting the active language. I'm still experimenting, but my guess is removing the robots.txt tests won't fix this.

**Comment by jgmize** [comment]
@pmclanahan how about we just change [this line](https://github.com/mozilla/bedrock/blob/89d1c68d64e970f37ecd9f17d9d136f11d9a23a9/bedrock/newsletter/tests/test_forms.py#L266) to
```python
self.assertTrue(form.errors['newsletters'])
```
for now? That fixed that particular test for me locally, and should hopefully give us a green run from travis-- you can probably even restore the `TestRobots` class if you like.

**Comment by flodolo** [comment]
Not sure if I'm going to contribute to the confusion: I get the same error Josh is getting with master and I have both ADMINS and MANAGERS settings like the [-dist file](https://github.com/mozilla/bedrock/blob/master/bedrock/settings/local.py-dist#L4). Same error if I run `ADMINS='["admin@example.com"]' ./manage.py test`.

They go away if I set `DEV = False`, which might make sense (all locales are available in DEV mode, regardless from the active status, so it fails for de and fr 'inactive').

**Comment by flodolo** [comment]
I'm kind of fascinated by test failures, even if I don't understand much about Django. One more weird note: this makes all tests pass locally, no clue why, but maybe it can help you figure it out
```
class TestRobots(TestCase):
    def test_robots_no_redirect(self):
        response = self.client.get('/robots.txt')
```

**Comment by pmclanahan** [comment]
Oh wow, that is fascinating @flodolo. I've no clue why simply using `self.client` would alter the test run. I'll keep digging.

**Comment by jgmize** [comment]
The actual non-test code lgtm, and while I agree that we need to do more digging on the test failures, I don't want that to block getting this fix into production, so if @flodolo's suggestion makes travis happy, that seems good enough to merge to me. r+wc

**Comment by pmclanahan** [comment]
I confirmed that adding back in a test that uses the test client fixes all tests locally :confounded: If the tests pass here I'll rebase and we can merge.

**Comment by pmclanahan** [comment]
Okay. Well. Nice work @flodolo. Tests are passing. I've rebased the primary work and added a fix for those email box tests so that the MANAGERS setting isn't required.

**Comment by pmclanahan** [comment]
@jgmize ready for final r? and merge when you are.

**Comment by jgmize** [comment]
thanks @pmclanahan and @flodolo!

**Pull request merged**
