### PR TITLE
Fix bug 1131738: Mark advisory reporter as safe.

### PR DESCRIPTION
**Pull request by pmclanahan**
Also remove transaction management from update
advisories command as it breaks things in dev
mode (sqlite) and isn't necessary for this.

### CODE REVIEW

**Comment by pmclanahan** [comment]
@jgmize r?

**Comment by pmclanahan** [comment]
@kyoshino since you saw it too, you want to r?  I know jgmize is busy.

**Comment by kyoshino** [comment]
LGTM on my local server and :+1:

**Comment by pmclanahan** [comment]
Thanks @kyoshino

**Comment by jgmize** [comment]
Thanks @kyoshino

**Pull request merged**
