### PR TITLE
repace expired PGP key

### PR DESCRIPTION
**Pull request by dveditz**
Adding a new PGP key for security@mozilla.org to replace the old one that expired in October

### CODE REVIEW

**Comment by dveditz** [comment]
@tomrittervg can you r+ this from the security team? Then we'll ask @pmac for the bedrock team review and merge.

**Review by stevejalim — APPROVED** [review]

**Comment by stevejalim** [comment]
Ahem, a little over-eager on the merge there by me - was on Github Mobile so didn't notice the request for eyes from Tom until too late. Can back it out or we just go with a retrospective r+ @dveditz?

**Comment by dveditz** [comment]
I'd still like the double-check, but I'm pretty confident. Seems fine to leave it, and if it does need a fix we can do a follow-up PR.
@mozfreddyb: If Tom's out, maybe you could check this and make sure this matches the key you now have

**Comment by dveditz** [comment]
@stevejalim Did you back it out? The site is still showing the old key. Or is there some later "push to prod" step? Not sure what to expect because the advisories go live quickly once we check in.

**Comment by mozfreddyb** [comment]
The key in this patch imports just fine here and the fingerprints match. Thanks @dveditz.

**Comment by pmac** [comment]
@dveditz it was not yet backed out, but it could be if you need us to. There is a separate prod push step that has not yet happened since this was merged. We'd be happy to hold off on pushing to prod if you want us to, or back it out for now if you need longer.

**Pull request merged**
