### PR TITLE
Second iterration of campaign page #9334

### PR DESCRIPTION
**Pull request by stephaniehobson**
## Description

- Update and re-order copy
- Remove campaign from URL
- Revert and remove "tell us" box and related scripts and styles
- Add animated hero
- Mobile layout tweaks

## Issue / Bugzilla link

#9334

### CODE REVIEW

**Comment by stephaniehobson** [comment]
@alexgibson Here's my day of work. Significant changes especially around the social sharing stuff. I'm glad they've dropped the "tell us" form field but I'm sorry it un-does a bunch of your work.

**Comment by stephaniehobson** [comment]
I'm not sure this is production ready code (tweet button/link isn't working for example) but you can change it from a draft to PR and merge if that's the easiest way for you to do your work.

The new goal for the GIFs is to make them into links to the Giphy page but I haven't started on that yet.

**Comment by alexgibson** [comment]
> I'm glad they've dropped the "tell us" form field but I'm sorry it un-does a bunch of your work.

I'm honestly not at all suprised here, I was expecting it either before or just after launch.

**Review by alexgibson — APPROVED** [review]
I pushed a commit to fix the flake8 errors.

Seeing as this page is only available on dev i think it's fine for not everything to be quite working yet. These will be useful foundational changes to rebase upon. Thanks

**Pull request merged**
