### PR TITLE
Update l10n docker image to use git l10n repo.

### PR DESCRIPTION
**Pull request by glogiotatidis**
Use https://github.com/mozilla-l10n/bedrock-l10n for locales. This code already runs on https://ci.us-west.moz.works/job/bedrock_l10n_image/

- [ ] Update l10n job to use this script when merged.
- [x] Add webhook

### CODE REVIEW

**Comment by glogiotatidis** [comment]
Pinged @pascalchevrel on IRC and he'll install a webhook from mozilla-l10n/bedrock-l10n later today

**Comment by pascalchevrel** [comment]
I put the webhook in place.

**Comment by glogiotatidis** [comment]
> Pinged @pascalchevrel on IRC and he'll install a webhook from mozilla-l10n/bedrock-l10n later today

done

**Comment by jgmize** [comment]
Updated https://ci.us-west.moz.works/job/bedrock_l10n_image/ to execute docker/jenkins/include_l10n.sh

**Pull request merged**
