### PR TITLE
Fix Bug 1229852 - Add Firefox Win64 download to /firefox/all/

### PR DESCRIPTION
**Pull request by kyoshino**

### CODE REVIEW

**Comment by kyoshino** [comment]
We have to push this to a demo server so someone in QA can quickly review it before Mozlando.

**Comment by jgmize** [comment]
I've deployed this PR to a Deis demo environment: https://bedrock-pr-3630.us-west.moz.works/en-US/firefox/all/

**Comment by kyoshino** [comment]
(Updated the bug ID)

**Comment by kyoshino** [comment]
No broken links found as per @davehunt :smiley_cat:

**Pull request merged**
