### PR TITLE
Redirect /firefox/os/notes to MDN: fix bug 1155870

### PR DESCRIPTION
**Pull request by jgmize**

### CODE REVIEW

**Comment by stephendonner** [comment]
Do we need mcom-tests or in-repo coverage for the redirect?

**Comment by jgmize** [comment]
@stephendonner yes, I'll work on that after I finish deleting some no-longer-needed unit tests and take another pass looking for more now-unnecessary code.

**Comment by jgmize** [comment]
I pushed b6a9b41 to demo4 and ran https://github.com/mozilla/mcom-tests/issues/415 against it successfully: https://ci.masterfirefoxos.com/view/www.mozilla.org/job/www-demo4.allizom.org-saucelabs/11/console

**Comment by jgmize** [comment]
@pmclanahan r?

**Comment by pmclanahan** [comment]
r+ :cake:

**Pull request merged**
