### PR TITLE
[fix bug 1174838] Update mozilla.org form tracking

### PR DESCRIPTION
**Pull request by alexgibson**
Marking as DNM for now, as needs testing on a demo server

### CODE REVIEW

**Comment by alexgibson** [comment]
GA data verified on demo2, so this is good for review: https://bugzilla.mozilla.org/show_bug.cgi?id=1174838#c6

**Comment by schalkneethling** [comment]
Code looks good to me but, someone with a more intimate knowledge of the analytics bits should probably also take a look.

**Comment by alexgibson** [comment]
Thanks @schalkneethling - @jpetto r?

**Comment by jpetto** [comment]
GA code looks good to me. r+

:ideograph_advantage:

**Pull request merged**
