### PR TITLE
Fix bug #13129

### LINKED ISSUE #13129: Prefer addEventListener('change') over addListener for media queries
## Description

We still have several occurrences of `addListener` in the code base when handling media queries in JS. This method is deprecated and may no longer be supported by browsers in the future. We should switch to `addEventListener` for browsers that support it, falling back to the old method like we do here:

 https://github.com/mozilla/bedrock/blob/main/media/js/pocket/mobile-nav.es6.js#L101-L115

### PR DESCRIPTION
**Pull request by amishk783**
## One-line summary

Replaced the addListener() function to addEventListener()  for media queries 

## Issue / Bugzilla link

Bug-Fix  #13129

## Checklist

If relevant:

- [ ] Tests added
- [ ] Feature flags added to www-config
- [ ] New secrets added to the secrets repository
- [ ] If new dependencies are added, I've checked their license is appropriate

### CODE REVIEW

**Comment by stevejalim** [comment]
@stephaniehobson No rush but could you review this one whenever you get time, please?

**Review by alexgibson — CHANGES_REQUESTED** [review]
Sorry, but this does not fix the issue. Simply doing a find/replace for `addListener` with `addEventListener` isn't providing a fallback for older browsers (this will actually cause an error in old browsers). The file you have touched here is the one place where we've already fixed this - it was provided as an example in the issue for how to tackle things elsewhere.

You need to look for other places in the codebase where this fallback does not yet exist.

**Comment by alexgibson** [comment]
Oops, sorry - mid-air comment collision @stevejalim

**Comment by amishk783** [comment]
@alexgibson I apologize for the oversight in my previous pull request. I understand that simply replacing **addListener** with **addEventListener** is not enough to provide a fallback for older browsers. I will review the codebase again to find other areas where the fallback is missing.

**Pull request closed without merging**
