### PR TITLE
Update lockwise.html

### PR DESCRIPTION
**Pull request by Shivansh2407**
## Description

Double counting events on lockwise page #7941

### CODE REVIEW

**Comment by Shivansh2407** [comment]
But from android part what should be removed @alexgibson 

See here 
        {{ google_play_button(href=lockwise_adjust_url('android', 'lockwise-page'), extra_data_attributes={'download-location': button_location, 'cta-type': 'lockwise-app-store', 'cta-text': 'google-play-store', 'cta-position': 'primary' } ) }}

**Comment by alexgibson** [comment]
The spec is linked in the issue: https://github.com/mozilla/bedrock/issues/7583#issuecomment-536762745

I'll paste it again here:

```
On App Store download buttons:
data-cta-type=“lockwise-app-store”
data-cta-text=“apple-app-store|google-play-store” // there are 2 of these buttons; use only one text option depending on the platform
data-cta-position=“primary”
```

**Comment by alexgibson** [comment]
It looks like the macro you may need to update is here:

https://github.com/mozilla/bedrock/blob/master/bedrock/base/templates/macros.html#L57-L63

On further inspection, I'm not sure this is so straight forward, as removing the default attributes is going to effect analytics on other pages. I'm going to mark this as do-not-merge until I can suggest a path forward. Thanks again

**Comment by Shivansh2407** [comment]
Made some changes in the lockwise.html file

**Comment by alexgibson** [comment]
> Made some changes in the lockwise.html file

Please hold while I can suggest a correct set of changes. Thanks

**Pull request closed without merging**
