### PR TITLE
Upgrade to Django2

### PR DESCRIPTION
**Pull request by NdagiStanley**
## Description
Upgrade the project to Django 2.

## Issue link
#5080

## Testing
Run `py.test lib bedrock` then start the server by running `python manage.py runserver`

### CODE REVIEW

**Comment by alexgibson** [comment]
Thank you for this PR @NdagiStanley - from the discussion in #5080 it seems like updating to Django 2 (and supporting Python 3) is still some way off our roadmap. Keeping this branch rebased and up-to-date over a long period of time seems an unlikely task, so we should probably consider closing this.

Thought @pmac ?

**Comment by pmac** [comment]
Agreed. Appreciate the effort @NdagiStanley! But I think there are several dependencies that need to be updated to work with Py3 or worked around as well as changes to bedrock itself. We should give it a good attempt again soon though.

**Comment by NdagiStanley** [comment]
Understood @alexgibson and @pmac.
So what are the next steps?

**Comment by pmac** [comment]
I think next is to go through our requirements files and see which do and do not support Python 3.6. The ones that don't we'll have to see if they maybe have a separate Python3 release, or if not we'll have to see if that's something we can contribute to the package or if we can work around not having that package. After that is done the rest of the job should be much easier.

**Comment by NdagiStanley** [comment]
@pmac That makes sense. So let's continue with that on #5080 , cool?
Having a project for this might help make the process easier. So that we have cards for specific packages and have columns for `Python 3 compatible`, `Needs contribution for porting to Python 3` and `Needs an alternative/ a work around`.

What do you think? @alexgibson thoughts?

**Pull request closed without merging**
