### PR TITLE
Use correct GB country code for affiliate attribution (Issue #11212)

### PR DESCRIPTION
**Pull request by alexgibson**
## Description
Fixes a country code typo for VPN affiliate attribution (should be `GB` instead of `UK`).

## Issue / Bugzilla link
#11212

## Testing
- [ ] Loading http://localhost:8000/en-US/products/vpn/?cjevent=09d8676b716a11ec831e01500a18050e&geo=gb should display the cookie notification.

### CODE REVIEW

**Comment by alexgibson** [comment]
@maureenlholland time for a small (and hopefully easy) r?

**Comment by maureenlholland** [comment]
Hi @alexgibson, this works as described but I'm not sure I follow the issue we're fixing

http://localhost:8000/en-US/products/vpn/?cjevent=09d8676b716a11ec831e01500a18050e&geo=uk shows the cookie banner as well for me

and the [VPN_COUNTRY_CODES settings](https://github.com/mozilla/bedrock/blob/master/bedrock/settings/base.py#L1591) shows both GB and UK

Could you give a little more context for why we need GB instead of UK on AFFILIATE_COUNTRIES settings?

**Comment by alexgibson** [comment]
@maureenlholland `UK` is not actually a [valid country code](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements), so it will default back to `US`. We should be using `GB`. I believe the old `UK` code in [VPN_COUNTRY_CODES settings](https://github.com/mozilla/bedrock/blob/master/bedrock/settings/base.py#L1591) is leftover from the legacy VPN site (prior to migration to bedrock). 

I didn't want to remove that here as it's something I think I need to research a little further, but it seems like a legacy value.

**Review by maureenlholland — APPROVED** [review]
r+ ✅ 

Nice catch!

**Comment by alexgibson** [comment]
Thanks for the review, and insightful question!

**Pull request merged**
