### PR TITLE
[fix bug 1144753] Further compress images on firefox/os

### PR DESCRIPTION
**Pull request by alexgibson**
We added some high-res images to the firefox/os page in Bug 1139350.

These have already been run through ImageOptim, but since there are quite a few images I think some further compression may be worthwhile. There are some decent savings to be had using tinyPNG.

### CODE REVIEW

**Comment by cargoworker** [comment]
Can one of the admins verify this patch?

**Comment by flodolo** [comment]
@cargoworker I'm not sure why you're doing it, but please stop commenting every single PR like this, you're spamming a lot of people. 

Each pull request will be reviewed in due time, don't add comments if you don't have anything to add related to the pull request.

**Comment by alexgibson** [comment]
I'm not sure @cargoworker is a real person, probably a bot someone has created. But I agree this particular comment is both a bit unhelpful and too noisy.

**Comment by flodolo** [comment]
Yeah, I realized it after commenting and looking at his [activity](https://github.com/cargoworker?tab=repositories).

It looks like it committed to masterfirefoxos-l10n: @glogiotatidis  do you know anything about this? I see the only other repo is fork from one of yours

**Comment by glogiotatidis** [comment]
cargoworker is a bot used by Jenkins that @jgmize is working on intergrating in #2850. I'll touch base with Josh later today and discuss how we can make this work for you.

**Comment by craigcook** [comment]
Looks good, let's hope the cachebusting trick works.

**Pull request merged**
