### PR TITLE
Bug 1388150: Convert release notes to use git repo and JSON

### PR DESCRIPTION
**Pull request by pmac**
Will allow us to simplify bedrock by not installing RNA.

### CODE REVIEW

**Comment by pmac** [comment]
Blocked until some changes to Nucleus are deployed. But I wanted to get this in for some review and to run the full tests.

**Comment by pmac** [comment]
No longer blocked. Nucleus has been released with the updates and the [Jenkins job](https://ci.us-west.moz.works/view/Nucleus/job/release-notes-json-watch/) to keep the [release-notes git repo](https://github.com/mozilla/release-notes) updated is running and successfully updating the files.

**Comment by jgmize** [comment]
Nice work @pmac! The code, unit tests, etc LGTM. I didn't see any new integration tests, but I'm also not sure those are necessary. Has the latest code already been deployed to a demo for manual testing?

**Comment by pmac** [comment]
Not the latest. I'll do that now and run integration tests. I'll check the suite for RN tests as well.

**Comment by pmac** [comment]
Deployed to demo and looking good:

https://bedrock-demo-pmac.us-west.moz.works/en-US/firefox/55.0.3/releasenotes/

Integration tests passed as well:

https://ci.us-west.moz.works/blue/organizations/jenkins/bedrock_multibranch_pipeline/detail/demo%2Fpmac/32/pipeline

**Pull request merged**
