### PR TITLE
Bug 1136463 - add Private Browsing to Fx Family page

### PR DESCRIPTION
**Pull request by craigcook**
This includes a bunch of the CSS for adding iOS as well, but none of those rules will actually be applied to the page until #3396 lands. This PR needs to merge before #3396 (which will then need rebasing, of course).

### CODE REVIEW

**Comment by alexgibson** [comment]
Mozilla wordmark is cropped slightly

mozilla

**Comment by alexgibson** [comment]
Private browsing icon is also cropped slightly at smaller viewports

private-browsing

**Comment by alexgibson** [comment]
Not necessarily a blocker, but the product icons are no longer bottom aligned in IE:

ie-grrrrr

**Comment by alexgibson** [comment]
A few cropping / alignment issues but otherwise looking good :+1:

**Comment by craigcook** [comment]
I've fixed the sprite clipping problems (low-res and high-res sprites weren't matching) and the IE layout (I've been spoiled by flexbox; had to do some positioning for non-flex). Should be good to go.

**Comment by alexgibson** [comment]
Changes look good! r+ :cactus:

**Pull request merged**
