### PR TITLE
Fix Bug 1097297 - Link to other systems & languages on the Firefox Developer Edition page

### PR DESCRIPTION
**Pull request by kyoshino**
Simply use the non-simple button, maybe?

### CODE REVIEW

**Comment by pmclanahan** [comment]
This actually changes the button significantly from the original design. Should we keep the more simple button from the design and just add the "systems & languages" link instead?

@sgarrity ?

**Comment by sgarrity** [comment]
Yeah, I filed a [bug to make the title/label download customizable](https://bugzilla.mozilla.org/show_bug.cgi?id=1089725) in the real download buttons.

This PR does significantly change the appearance and text in the button. We can get the "FREE DOWNLOAD" label with the ```simple=True``` switch, but then we lose the sys/req link we want.

**Comment by pmclanahan** [comment]
Should be pretty easy to just add the link in this case and keep the `simple=True` I think.

**Comment by jpetto** [comment]
Agree with @pmclanahan that we should add a link for "Systems & Languages" next to "Privacy" and keep the `simple=True` button style.

**Comment by kyoshino** [comment]
> we should add a link for "Systems & Languages" next to "Privacy" and keep the simple=True button style.

Okay, will update the PR with that change.

**Comment by kyoshino** [comment]
I have noticed that there are the secondary links even with the simple style; they are just hidden with an inline CSS. So rather than adding duplicated links in HTML, we could just override the style only on this page. The updated PR has that change. r?

**Comment by pmclanahan** [comment]
This looks good to me and works well locally. @jpetto care to take a last look at the CSS changes?

**Comment by jpetto** [comment]
CSS looks good. The `!important` is contained within the `.download-button-simple` class, and is really just a re-work of an inline style (gasp!) removed from `download_firefox_button.html`. Checked other instances of simple download button and they're looking good (no small links).

**Pull request merged**
