### PR TITLE
Bug 907793: Fix Open Sans to be able to render Romanian

### PR DESCRIPTION
**Pull request by pascalchevrel**
The patched files are provided by Jonathan Kew, see https://bugzilla.mozilla.org/show_bug.cgi?id=907793#c19

### CODE REVIEW

**Comment by craigcook** [comment]
@pmclanahan Will we need to cachebust references in the CSS to make sure the new files are loaded?

**Comment by pmclanahan** [comment]
@craigcook I think unfortunately yes :( Should just be able to add a special comment to files that reference these files:

```css
/*! updated 2015-06-17 */
```

Something like that.

**Comment by pascalchevrel** [comment]
All the css files referencing these fonts are updated with the comment you suggested

**Comment by pmclanahan** [comment]
Looks great Pascal. r+

**Pull request merged**
