### PR TITLE
[fix bug 1157136] Remove old /whatsnew view logic & templates

### PR DESCRIPTION
**Pull request by alexgibson**
In preparation for spring campaign, I thought it was about time we remove some of our old /whatsnew view logic. This has been on my to-do list, and it seems now is probably a good time given that we are doing another /whatsnew page for FF 38.

With this PR a default base /whatsnew template gets shown to everything under FF 36, although no one should really be hitting these pages now anyway. ESR 31 is also no longer showing /whatsnew on update, as per [this comment](https://bugzilla.mozilla.org/show_bug.cgi?id=1121209#c7).

I'm leaving the templates in the repo, as we never know when we might resurrect something.

### CODE REVIEW

**Comment by alexgibson** [comment]
@pmclanahan r?

**Comment by pmclanahan** [comment]
I say remove the templates as well. Resurrecting things we've deleted is why we use version control.

**Comment by alexgibson** [comment]
Fair point @pmclanahan :+1:

**Comment by alexgibson** [comment]
@pmclanahan updated, thanks

**Comment by pmclanahan** [comment]
@alexgibson so sorry I dropped the ball on this. It's r+ from me. But due to my failure it needs a rebase. Shall I do that myself? I think it's late for you at this point.

**Comment by pmclanahan** [comment]
Oh. I know why. Because funfactory removal moved static media defs into a separate file. I'll handle it.

**Comment by pmclanahan** [comment]
Filed a new pr after a rebase.

**Comment by alexgibson** [comment]
No problem, and thanks @pmclanahan!

**Pull request closed without merging**
