### PR TITLE
Remove one-off campaign pages (Fixes #14231)

### LINKED ISSUE #14231: flashback

### PR DESCRIPTION
**Pull request by alexgibson**
## One-line summary

Removes several old campaign pages

## Issue / Bugzilla link

#14231

## Testing

- [x] http://localhost:8000/landing/firefox/fx100/ should redirect to `/firefox/`
- [x] http://localhost:8000/en-US/firefox/flashback/ should redirect to `/firefox/`
- [x] http://localhost:8000/en-US/santalocator/ should redirect to `/`.

### CODE REVIEW

**Comment by stephaniehobson** [comment]
Needs a rebase.

**Comment by alexgibson** [comment]
@stephaniehobson rebased

**Comment by reemhamz** [comment]
looks like it needs another rebase

**Comment by alexgibson** [comment]
@reemhamz rebased again, thanks

**Review by craigcook — APPROVED** [review]
`/img/mozorg/santa-locator/` can also be deleted. r+wc

So long, Panda Clause 👋

**Pull request merged**
