### PR TITLE
Fix Bug 1112277, stop using jsonp with plugincheck

### PR DESCRIPTION
**Pull request by schalkneethling**
@alexgibson r?

### CODE REVIEW

**Comment by schalkneethling** [comment]
This depends on the work that needs to be done here:
https://bugzilla.mozilla.org/show_bug.cgi?id=1112277#c20

To test this locally, change the URL in:
https://github.com/mozilla/bedrock/pull/2911/files#diff-0232b38b609901500bb2c6db6389ebefR166

to point to plugins.allizom.org as that has a * ACAO header.

**Comment by schalkneethling** [comment]
Since https://bugzilla.mozilla.org/show_bug.cgi?id=1112277#c28 both plugins stage and prod has an ACAO of '*' so, let the testing begin. @alexgibson

**Comment by alexgibson** [comment]
Locally this works for me against plugins.allizom.org, but I get an XHR error when testing against prod?

**Comment by schalkneethling** [comment]
@alexgibson What is the error? cross origin blocking?

**Comment by alexgibson** [comment]
"xhr" Object { readyState: 0, getResponseHeader: .ajax/v.getResponseHeader(), getAllResponseHeaders: .ajax/v.getAllResponseHeaders(), setRequestHeader: .ajax/v.setRequestHeader(), overrideMimeType: .ajax/v.overrideMimeType(), statusCode: .ajax/v.statusCode(), abort: .ajax/v.abort(), state: .Deferred/d.state(), always: .Deferred/d.always(), then: .Deferred/d.then(), 11 more… } plugincheck.js:272:17
    "status" "error" plugincheck.js:273:17
    "error" ""

    Syntax Error: JSON.parse: unexpected end of line data at line 1 column 1 of the JSON data

**Comment by schalkneethling** [comment]
@alexgibson ok, so this really works now on prod and stage ;)
see: https://bugzilla.mozilla.org/show_bug.cgi?id=1112277#c32

**Comment by alexgibson** [comment]
@schalkneethling - this is working for me locally now against prod r+ 

Good to merge?

**Comment by schalkneethling** [comment]
Indeed, let's merge!

**Pull request merged**
