### PR TITLE
WIP: firefox/enterprise/sla (#6779)

### PR DESCRIPTION
**Pull request by amychurchwell**
## Description
Current progress of /firefox/enterprise/sla

## Issue / Bugzilla link
#6779

### CODE REVIEW

**Comment by amychurchwell** [comment]
**Quick links**

- [Final SLA Copy](https://docs.google.com/document/d/1FmbbSh1V6emuaiTsR-B6uQXopeXO84BMtrvrkOli-E8/edit#)
- [Enterprise SLA.sketch.zip](https://github.com/mozilla/bedrock/files/2998063/Enterprise.SLA.sketch.zip)

**Comment by amychurchwell** [comment]
@craigcook Thank you _so much_ for picking this up while I'm gone next week. This was more time-consuming than I expected. 😓 

Current state of things:
- Severity Criteria & Examples graph has all information and basic styles. Has some padding/text weight issues.
- Sticky table of contents is not yet laid out.
- Severity Definitions based on Impact & Urgency is missing basic tables with corresponding text. (Tables aren't custom)
- Severity Matrix graph is not yet laid out.
- Support levels graph has padding/font-weight issues.

**Comment by ejregithub** [comment]
@craigcook - please ping me when you have this up on demo.

**Comment by craigcook** [comment]
Closing this in favor of https://github.com/mozilla/bedrock/pull/7084

**Pull request closed without merging**
