### PR TITLE
Fix #6179: Add Firefox Reality legal docs pages

### LINKED ISSUE #6179: New legal docs: Firefox Reality Privacy Notice and About Rights
The following two docs need to be pushed to production by Sept 18.
- About Rights: https://github.com/mozilla/legal-docs/blob/master/firefox_reality_about_rights/en-US.md
- Privacy Notice: https://github.com/mozilla/legal-docs/blob/master/firefox_reality_privacy_notice/en-US.md

### PR DESCRIPTION
**Pull request by pmac**
Also pull latest legal-docs repo master.

### CODE REVIEW

**Comment by pmac** [comment]
I'm not sure. It seems sometimes we don't. There are a few privacy pages that are not linked on the main page and are (I assume) in-product links only.

**Comment by pmac** [comment]
I'll ask in the bug.

**Comment by pmac** [comment]
[Asked](https://bugzilla.mozilla.org/show_bug.cgi?id=1491425#c8)

**Comment by alexgibson** [comment]
> I'm not sure. It seems sometimes we don't. There are a few privacy pages that are not linked on the main page and are (I assume) in-product links only.

Yeah - my hunch is that people generally seem to forget about it, which is why I'm sending a gentle reminder :) From an SEO perspective, if these pages aren't linked to from anywhere they are essentially non-discoverable.

**Comment by stephaniehobson** [comment]
I think I remember seeing release date for a logo for this in the new system.

**Comment by alexgibson** [comment]
We do get quite a lot of organic traffic to these pages (at least as far as /privacy/ goes). Adding these things to the index is only a few lines of code. Unless there's a really good reason not to do it, I'd say let's just save ourselves some work in the future? But I'll leave this up to you.

**Comment by pmac** [comment]
Added a link from the main /privacy/ page to the Firefox Reality policy. I think we're good for now. We can pick up the new logo in a followup.

**Pull request merged**
