### PR TITLE
Fix Bug 939470 - mozilla.org tells user it has up-to-date Firefox when it doesn't

### PR DESCRIPTION
**Pull request by kyoshino**
Now it works as expected. Please push this to any available test server so we can confirm the new behaviour. But I'm still wondering how to add tests for the `_getFirefoxDetails` method. Any ideas...?

### CODE REVIEW

**Comment by alexgibson** [comment]
Thanks for taking a look at this big @kyoshino! I haven't really dug into the code yet, but is there a technical reason why all this code needs to move into (what was) `site.js`? JS in the head is render blocking, so we should try and be extra diligent about moving more code here if it may not be strictly required?

**Comment by kyoshino** [comment]
Thanks @alexgibson! I forgot the fact `site.js` was in `<head>`. I think merging environment detection code into one single namespace makes sense, but yes, the Firefox part can/should be loaded separately only on requited pages. Will revise the PR tomorrow and fix tests as well.

**Comment by alexgibson** [comment]
Thanks @kyoshino - I appreciate the work you put in so far! I think we should leave site.js intact, and only make additions to it that effect initial page rendering (e.g layout specific CSS classes). Functions like the Firefox ones should remain in global.js. Doesn't need to be part of this PR, but eventually I'd like to move the Firefox functions to their own module that we can load explicitly when needed.

**Comment by kyoshino** [comment]
Okay, let's reorganize the Firefox functions in a separate PR. Will revise this shortly.

**Comment by kyoshino** [comment]
Alright, the new `getFirefoxDetails` method just does the right thing.

**Comment by kyoshino** [comment]
Okay, as we talked on Vidyo today, let's discuss this further with wider stakeholders on the bug or mailing list.

Technically this does the right thing, so how about testing it on non-`/firefox/new/` pages using GA events, so we can analyse how many users are hitting the fallback code?

**Comment by alexgibson** [comment]
@kyoshino - I'd be fine with creating a new function for this, which we can use as-and-when we choose on specific pages? I still think we should probably limit the event firing to only users whom we know are on a non-up-to-date ESR release version. If this is a way to unblock this PR, then let's go with that for now, while we decide how to handle /firefox/new/ :+1:

**Comment by kyoshino** [comment]
As I said, this bug is not limited to ESR, but exists with all minor updates. Currently we don't have any data so some GA testing might be good anyway. I'll file a separate bug and PR to add the new function with GA events except for /firefox/new/.

**Comment by alexgibson** [comment]
Ok @kyoshino that sounds good. I understand about the minor point release, I keep forgetting as this bug started out with ESR in mind :+1:

**Comment by kyoshino** [comment]
Will send a new PR once the decision for /firefox/new/ is made.

**Pull request closed without merging**
