### PR TITLE
Fix Bug 1118339 - Update https://www.mozilla.org/en-US/firefox/channel/#aurora for Android ARM links to reflect new FTP directory changes

### PR DESCRIPTION
**Pull request by kyoshino**
This needs to be merged this Friday, January 16. Do not merge before that, or links will be broken.

### CODE REVIEW

**Comment by kyoshino** [comment]
Asked in the bug when the change will happen on FTP.

**Comment by kyoshino** [comment]
@rnewman says in the bug that the new directory structure is already in effect on FTP, so we can merge this today.

**Comment by jgmize** [comment]
FYI this is still blocked, but not due to FTP changes or the code itself: I'm still getting 404s for both the [Android Gingerbread](https://ftp.mozilla.org/pub/mozilla.org/mobile/nightly/latest-mozilla-aurora-android-api-9/fennec-36.0a2.multi.android-arm.apk) and  [Android Honeycomb+ ARMv7](
https://ftp.mozilla.org/pub/mozilla.org/mobile/nightly/latest-mozilla-aurora-android-api-11/fennec-36.0a2.multi.android-arm.apk) buttons locally after updating product details because product details still points at version 36.0a2 as the latest, but 37.0a2 is the version in the new directories.

**Comment by jgmize** [comment]
r+, but we'll need to coordinate changing product-details with pushing this code to production so I'm waiting to merge.

**Comment by jgmize** [comment]
@lmandel is updating product details now.

**Pull request merged**
