### PR TITLE
[bug 1378137] Fix lazy-image placeholder color on /firefox/features/

### PR DESCRIPTION
**Pull request by alexgibson**
Minor visual regression from #4960

### CODE REVIEW

**Comment by jpetto** [comment]
D'oh! Should have caught this during review.

**Comment by jpetto** [comment]
Need to update [on the new developer page](https://github.com/mozilla/bedrock/blob/master/media/css/mozorg/developer/index.scss#L137) as well?

**Comment by alexgibson** [comment]
It's only a subtle thing, I totally missed it too

**Comment by alexgibson** [comment]
> Need to update on the new developer page as well?

Good catch, updated!

**Pull request merged**
