### PR TITLE
Add Community section to release notes

### LINKED ISSUE #10531: Add "Community" subcategory on release notes pages and nucleus
From [bug 1725337](https://bugzilla.mozilla.org/show_bug.cgi?id=1725337):

We have a request from UX/comms to add a new "Community" category for release notes.

The icon would be:

```xml
<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
<circle cx="12" cy="6" r="3" stroke="black" stroke-width="2"/>
<path d="M18 18.3939C18 19.2969 17.8255 19.8131 17.6196 20.1198C17.4253 20.4092 17.1326 20.6175 16.658 20.7623C16.1604 20.914 15.5185 20.9782 14.7041 20.995C14.2126 21.0051 13.7162 20.9984 13.1818 20.9913C12.8099 20.9863 12.4197 20.981 12 20.981C11.5803 20.981 11.1901 20.9863 10.8182 20.9913C10.2838 20.9984 9.78736 21.0051 9.2959 20.995C8.48146 20.9782 7.83961 20.914 7.34197 20.7623C6.86735 20.6175 6.57467 20.4092 6.38039 20.1198C6.17453 19.8131 6 19.2969 6 18.3939C6 14.8104 8.73717 12 12 12C15.2628 12 18 14.8104 18 18.3939Z" stroke="black" stroke-width="2"/>
</svg>
```

The new category should be called "Community Contributions" and should come in order after "Unresolved," at the end.

### PR DESCRIPTION
**Pull request by pmac**
Fix #10531

### CODE REVIEW

**Comment by pmac** [comment]
I tested this locally by adding some [community tagged notes to Firefox 92 release in a branch on my fork of the release-notes repo](https://github.com/pmac/release-notes/commit/41a6a0ca60c3f3ea414e1599cc4171a80c702865). Then I updated my local settings in my .env file to add this:

```env
RELEASE_NOTES_REPO=https://github.com/pmac/release-notes.git
RELEASE_NOTES_BRANCH=community-notes
```

Then ran `./manage.py update_release_notes` and looked at the results:

Screen Shot 2021-09-30 at 15 13 41

**Review by nathan-barrett — APPROVED** [review]
r+

**Comment by reemhamz** [comment]
Question, why does the JSON file [here](https://github.com/pmac/release-notes/commit/41a6a0ca60c3f3ea414e1599cc4171a80c702865) have 3 equivalent note values, which is showing in the image you pasted?

**Comment by pmac** [comment]
> Question, why does the JSON file [here](https://github.com/pmac/release-notes/commit/41a6a0ca60c3f3ea414e1599cc4171a80c702865) have 3 equivalent note values, which is showing in the image you pasted?

Because I was too lazy to write different notes for the testing example and just wanted something to show up so I could make sure the basic look would be okay.

**Comment by pmac** [comment]
Thanks for taking a look y'all 🍰

**Pull request merged**
