### PR TITLE
Convert NodeList to array for compatibility

### PR DESCRIPTION
**Pull request by dougmellon**
## Description
The forEach() method of the NodeList interface calls the callback given in parameter once for each value pair in the list, in insertion order. While more modern browsers support forEach on a NodeList, older ones only allow it on arrays. To solve this, I converted the original NodeList to an array than iterated through that new array.

## Issue / Bugzilla link
[Type error on /firefox/new/ in older Edge browsers #9644](https://github.com/mozilla/bedrock/issues/9644)

## Testing
fix bug #9644

### CODE REVIEW

**Comment by dougmellon** [comment]
Second ever pull request so if there are any issues, please feel free to let me know and I will correct them.

**Review by alexgibson — CHANGES_REQUESTED** [review]
Thanks for the pull request!

The code here looks good, but testing in Edge it doesn't look like the animations actually work there. I think the best course of action is probably to opt older Edge browsers out of this code path altogether on line 141, instead of the changes you've made here:

```javascript
// check for support
if(supportsInsersectionObserver && window.NodeList && NodeList.prototype.forEach) {

}
```

**Comment by dougmellon** [comment]
@alexgibson I believe I made the correct changes. Please let me know if there are any further issues with it and I will gladly adjust them.

**Comment by alexgibson** [comment]
Merged in https://github.com/mozilla/bedrock/commit/5a7793bfe8f6dab828acef1daa5832179015534b, thanks @dougmellon! 💯

**Pull request closed without merging**
