### PR TITLE
Moves mustache out of the bundle and into the page

### PR DESCRIPTION
**Pull request by schalkneethling**
@alexgibson @pmclanahan r?

### CODE REVIEW

**Comment by kyoshino** [comment]
Can we use the [minified version](https://github.com/janl/mustache.js/blob/master/mustache.min.js) instead?

**Comment by kyoshino** [comment]
Or I was thinking the order of the files. `mozilla-share-cta.js` should probably be after `mustache.js`.

**Comment by pmclanahan** [comment]
You might be right @kyoshino. Might work if mustache is first.

**Comment by schalkneethling** [comment]
aha, ok. let's move mustache before mozilla-share

**Pull request merged**
