### PR TITLE
Tweak granian config - set workers to 1

### PR DESCRIPTION
**Pull request by robhudson**
I went through the Granian [documentation](https://github.com/emmett-framework/granian?tab=readme-ov-file#processes-and-threads) regarding processes and threads, and it seems that the recommended approach for our deploy configuration is to set the number of workers to 1 and let Kubernetes handle the scaling of containers. The default number of threads is 1, which the documentation states is fine for the vast majority of applications. It suggests increasing the number of threads only for applications dealing with several concurrently opened websockets, which is not our case.

Granian "workers" are processes holding a dedicated Python interpreter that will run the application. The recommendation is to match the number of workers to the number of CPU cores for the best starting point. However, for containerized environments like Kubernetes, the suggestion is to have 1 worker per container and scale the containers using the relevant orchestrator (in our case, Kubernetes).

### CODE REVIEW

**Comment by pmac** [comment]
Is it not useful to be able to tweak this without a deployment? We could change the default to 1 maybe, or just update the config as it rolls out. Thoughts?

**Comment by robhudson** [comment]
Yeah, if we think we want to adjust this, defaulting to 1 and adjusting `WSGI_NUM_WORKERS` sounds better. I'll update.

**Review by stevejalim — APPROVED** [review]
R+

But also wondering if we should set backpressure now as well?

**Review by pmac — APPROVED** [review]
🧑‍🏭

**Pull request merged**
