### PR TITLE
[fix bug 1231171] Implement Firefox Accounts signup page

### PR DESCRIPTION
**Pull request by alexgibson**

### CODE REVIEW

**Comment by alexgibson** [comment]
@jpetto r?

**Comment by flodolo** [comment]
Any detail on what this page is, and what's the l10n impact?

**Comment by alexgibson** [comment]
@flodolo - it's just for a 2 day test, no l10n required on this one. Thanks

**Comment by jpetto** [comment]
Working as expected locally. As previously noted, demo4 has an issue, but we believe this is due to an FxA change. Should verify all is well on stage just before prod push.

r+!

**Pull request merged**
