### PR TITLE
fixed Styling and link issues on Firefox Developer page

### PR DESCRIPTION
**Pull request by Ayushsunny**
## Description
Fixing of Styling and link issues on Firefox Developer firstrun and Dev Edition whatsnew page.

## Issue / Bugzilla link
#11281

## Testing
Screenshot 2022-03-07 at 14-14-35 Firefox Developer Edition

### CODE REVIEW

**Comment by Ayushsunny** [comment]
@craigcook Review.

Also i found this and it seems to be aligned wrong. if you think the same should i amend the changes with this commit too?
Screenshot 2022-03-07 at 14-40-28 Firefox Developer Edition

**Review by craigcook — CHANGES_REQUESTED** [review]
Sorry, this isn't quite the right solution. These sections of the page use the "Split" component from our design system but are not importing the styling for that component. The way to fix it is to import that styling by adding the `protocol-split` CSS bundle to the `page_css` block, [as I explained on the issue](https://github.com/mozilla/bedrock/issues/11281#issuecomment-1060070048).

**Comment by Ayushsunny** [comment]
Could you check now? @craigcook

**Review by craigcook — APPROVED** [review]
Looks good! Thanks for the fix!

**Pull request merged**
