### PR TITLE
Port Transparency Report pages to Protocol (Fixes #7530)

### LINKED ISSUE #7530: Port Transparency Report pages to Protocol
## Description

The Transparency Report pages are using Pebbles.
https://www.mozilla.org/about/policy/transparency/

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Transparency Report pages are updated in production using Protocol.

#### Tasks
- [ ] Update templates.

### PR DESCRIPTION
**Pull request by amychurchwell**
## Description
Updated Transparency Report templates to use Protocol.

## Issue / Bugzilla link
#7530 

## Testing
http://localhost:8000/about/policy/transparency/
All templates under /about/policy/transparency/ are no longer using Pebbles.

### CODE REVIEW

**Comment by alexgibson** [comment]
At smallest screen sizes, the title overflows the edge of the viewport ever so slightly:

image

**Comment by alexgibson** [comment]
Would it be more closely aligned with the current design if we made the whole page use the narrow column layout, instead of just the top section?

image

**Comment by alexgibson** [comment]
Visually, it feels like the three nav buttons could sit inside the narrow column margins, rather than float outside in their own space?

image

**Comment by amychurchwell** [comment]
> The page title also still runs wider than the screen.

Struggling to reproduce this bug, what width is it? I can say that padding that is probably causing that is coming from `mzp-l-content`

**Comment by alexgibson** [comment]
> Struggling to reproduce this bug, what width is it?

Using Firefox, resize the browser window to it's smallest width (320px, which is the smallest phones go). I don't thik this needs to be a blocker though

**Pull request merged**
