### PR TITLE
(#6480) Automate image compression

### PR DESCRIPTION
**Pull request by amychurchwell**
## Description
Rough draft of image compression.

## Issue / Bugzilla link
#6480

### CODE REVIEW

**Comment by amychurchwell** [comment]
Adding WIP label to explore putting these tasks on a git hook

**Comment by stephaniehobson** [comment]
🤩

**Comment by amychurchwell** [comment]
Per conversation in https://github.com/mozilla/bedrock/pull/7243 reopening and going to see about setting up [ghooks](https://www.npmjs.com/package/ghooks) w/ @stephaniehobson

**Comment by alexgibson** [comment]
I'm all in favor of the gulp workflow proposed here, but it looks like https://github.com/mozilla/bedrock/pull/7243 is a bit further on than this, seeing as it works on staged files. As we discussed yesterday, we're going to close this PR in favor of https://github.com/mozilla/bedrock/pull/7243 - but let's revisit using Gulp for this if we decide there's a need.

Thanks, @amychurchwell!

**Pull request closed without merging**
