### PR TITLE
Fixed 'Remote' job filtering

### PR DESCRIPTION
**Pull request by Ayushsunny**
## Description
Fixing of Remote job filtering like now when we'll select Remote US, the Remote will also be included and for all the specific Remote location.

## Issue / Bugzilla link
#11112

## Testing

https://user-images.githubusercontent.com/73520373/149544200-48637a42-63c2-4b92-8338-57f1e0218d24.mp4

### CODE REVIEW

**Comment by Ayushsunny** [comment]
@alexgibson Review

**Review by alexgibson — CHANGES_REQUESTED** [review]
Please add some tests, thanks

**Comment by Ayushsunny** [comment]
> Please add some tests, thanks

Hey Alex,
I'm sorry I have no idea about what to do in tests and in which file?
so need your help here, please.

**Comment by alexgibson** [comment]
Tests for this file can be found here: https://github.com/mozilla/bedrock/blob/master/tests/unit/spec/careers/filters.js

thanks again!

**Comment by Ayushsunny** [comment]
@alexgibson

**Review by alexgibson — APPROVED** [review]
Thanks!

**Pull request merged**
