### PR TITLE
Drop 1st class support for IE9 (Fixes #7559)

### LINKED ISSUE #7559: Drop 1st class browser support for IE9
## Description

We have the [go-ahead](https://github.com/mozilla/bedrock/issues/7389) to drop 1st class JS & CSS support for IE9. It can be served the same universal CSS & JS bundle as IE8, on the condition that we make an excpetion for the /firefox page.

For the /firefox page, we need to deliver some enhanced (but not necessarily 1st class) CSS, to at least style the main CTA.

Note: IE10 doesn't support conditional comments, so we'll need to cover that separately in https://github.com/mozilla/bedrock/issues/7391.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] IE9 is served the universal CSS and JS bundles for legacy browsers.
- [x] The /firefox page is served enhanced CSS on IE9.

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] This browser support change has been evaluated in https://github.com/mozilla/bedrock/issues/7389, so risk should hopefully be minimal.

#### Tasks
- [x] Update conditional comments to include IE9 in legacy browser treatment.
- [x] Add IE9 specific styles for /firefox.
- [x] Ensure downloads still function as expected in IE9.
- [x] Remove any [IE9 specific polyfills](https://github.com/mozilla/bedrock/blob/master/bedrock/base/templates/base-pebbles.html#L106-L108).

### PR DESCRIPTION
**Pull request by alexgibson**
## Description
- Serve IE9 universal CSS & JS bundle. Exclude from page specific CSS & JS.
- Add some IE9 specific styles for the /firefox page.

## Issue / Bugzilla link
#7559

## Testing
Demo: https://www-demo1.allizom.org/en-US/firefox/

- [x] Downloads still work in IE9.
- [x] IE9 gets the basic stylesheet for all pages with the following exceptions:
  - [x] The `/firefox/new/` page continues to get 1st class CSS.
  - [x] The `/firefox/download/thanks/` page continues to get 1st class CSS.
  - [x] The `/firefox` page gets 1st class CSS for the top hero section of the page only.

Successful test run: https://ci.vpn1.moz.works/blue/organizations/jenkins/bedrock_multibranch_pipeline/detail/run-integration-tests/362/pipeline

### CODE REVIEW

**Comment by stephaniehobson** [comment]
This is already looking great :)

**Comment by alexgibson** [comment]
Ok, I think this is ready for code review.

**Comment by Errolyn** [comment]
we are going to have one more person look over this to make sure I didn't miss anything.

**Comment by alexgibson** [comment]
Rebased after #7697 and #7712 merged.

**Comment by alexgibson** [comment]
It would be really great to try and get this merged soon if someone has time to take a second look

**Pull request merged**
