### PR TITLE
Django 1.11

### PR DESCRIPTION
**Pull request by SmileyChris**
Here we go! Similar to the kitsune PR, I've only upgraded packages where necessary to minimise the altered surface area.

The biggest change that needs scrutiny is the replacement of the `UnlabeledTableCellRadios` and `SideRadios` radio field renderers, replaced with new template widgets.

### CODE REVIEW

**Comment by jpetto** [comment]
[Integration tests are passing!](https://ci.vpn1.moz.works/blue/organizations/jenkins/bedrock_multibranch_pipeline/detail/run-integration-tests/257/pipeline/) 🎉

**Comment by jpetto** [comment]
I don't see any issues with the new radio button renderers. 😀

**Comment by SmileyChris** [comment]
Cool, yeah i did some manual testing too and it seemed to all be fine.

Wanted to check from your end - my worst fears were that there could have
been some JS that would treat it slightly different...

**Comment by pmac** [comment]
Does need a rebase on master, but that looks like it'll be pretty easy.

**Comment by jpetto** [comment]
Integration tests are [still passing](https://ci.vpn1.moz.works/blue/organizations/jenkins/bedrock_multibranch_pipeline/detail/run-integration-tests/303/pipeline/) after another rebase.

**Comment by jpetto** [comment]
Commits were merged in #7135, closing.

**Pull request closed without merging**
