### PR TITLE
Add ADRs to Sphinx docs

### PR DESCRIPTION
**Pull request by pmac**
* Install Sphinx markdown deps
* Configure Sphinx with markdown support
* Switch to RTD Sphinx theme for local too
* Fix a bunch of Sphinx warnings for docs
* Separate docs deps into a requirements file for RTD to use

### CODE REVIEW

**Comment by pmac** [comment]
@metadave @jgmize we talked about doing this, and I discovered it's not that hard. This should do it 🙌

**Comment by metadave** [comment]
💯💯💯

**Comment by jgmize** [comment]
I pulled this down locally to test and ran into a couple of issues:

```bash
$ make docs
```
```
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
```

This was an easily resolved local issue, but we may want to add a note to our docs on how to resolve it:
```bash
$ xcode-select --install
```
```
xcode-select: note: install requested for command line developer tools
```

The second issue is specific to this PR:
```bash
$ make docs
```
```
/usr/local/bin/docker-compose run app make -C docs/ clean html
Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"make\": executable file not found in $PATH": unknown
make: *** [docs] Error 1
```

**Comment by jgmize** [comment]
This rendered the content exactly as I'd expect it locally, but we have some warnings about docs not included in any toctree that we should probably follow up on in a later PR:

```
$ make docs
/usr/local/bin/docker-compose run app make -C docs/ clean html
make: Entering directory '/app/docs'
rm -rf _build/*
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v1.8.3
making output directory...
loading intersphinx inventory from http://docs.python.org/objects.inv...
intersphinx inventory has moved: http://docs.python.org/objects.inv -> https://docs.python.org/3/objects.inv
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 24 source files that are out of date
updating environment: 24 added, 0 changed, 0 removed
/venv/lib/python2.7/site-packages/recommonmark/parser.py:65: UserWarning: Container node skipped: type=document
  warn("Container node skipped: type={0}".format(mdnode.t))
reading sources... [100%] uitour
looking for now-outdated files... none found
pickling environment... done
checking consistency... /app/docs/firefox-accounts-iframe.rst: WARNING: document isn't included in any toctree
/app/docs/mozilla-accordion.rst: WARNING: document isn't included in any toctree
/app/docs/mozilla-lazy-load.rst: WARNING: document isn't included in any toctree
/app/docs/mozilla-notification-banner.rst: WARNING: document isn't included in any toctree
/app/docs/mozilla-pager.rst: WARNING: document isn't included in any toctree
done
preparing documents... done
writing output... [100%] uitour
generating indices... genindex
writing additional pages... search
copying static files... done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 5 warnings.

The HTML pages are in _build/html.

Build finished. The HTML pages are in _build/html.
make: Leaving directory '/app/docs'
```

**Pull request merged**
