### PR TITLE
Issue #5395

### PR DESCRIPTION
**Pull request by harshitakalsi5**
## Description
top padding changed to 40 px from 25 px
heading changed
## Issue / Bugzilla link
#5395

### CODE REVIEW

**Comment by alexgibson** [comment]
Thanks for the PR @harshitakalsi5 - I'm not entirely clear what this is fixing, as the file you're changing seems entirely unrelated to `#5395`. Did you test these changes locally?

**Comment by harshitakalsi5** [comment]
Thank You for Acknowleging @alexgibson but I could not test these changes as the webpages were dynamic hence could not get any git pages. Neither did netbeans work

**Comment by alexgibson** [comment]
@harshitakalsi5 Ok, before submitting a pull request it may be worth taking some time to get bedrock up and running so that you can test your changes.

The install docs are here: http://bedrock.readthedocs.io/en/latest/install.html

It may also be worth reading our contributing guidelines: http://bedrock.readthedocs.io/en/latest/contribute.html

**Comment by alexgibson** [comment]
I'm going to close this pull request for now, but feel free to reopen or create a new one once you have the site running locally. Any questions please feel free to drop into #www on IRC. Thanks!

**Pull request closed without merging**
