### PR TITLE
Fix eslint 'no-useless-escape' errors. (#7747) #7752

### PR DESCRIPTION
**Pull request by Shivansh2407**
## Description
Fix eslint 'no-useless-escape' errors. (#7747) #7752

### CODE REVIEW

**Comment by amychurchwell** [comment]
@Shivansh2407 this PR is a dupe of: https://github.com/mozilla/bedrock/pull/7752
Please update your original PR. Thank you!

**Comment by Shivansh2407** [comment]
If it is possible to close #7752 so please close it and reopen #7838 to review the changes.
Thanks

**Comment by Shivansh2407** [comment]
@amychurchwell Please let me know soon

**Comment by amychurchwell** [comment]
@Shivansh2407 closed original PR in favor of this one. In the future, please update the original pull request with any additional commits needed. Thank you. 🙂

**Comment by Shivansh2407** [comment]
Ok .... Thanks will keep in mind next time...Please review it and let me know the changes (if any).

**Comment by Shivansh2407** [comment]
Thanks @amychurchwell .

**Pull request merged**
