### PR TITLE
Update legal docs for Firefox Lite (Fixes #8315)

### LINKED ISSUE #8315: Review/Merge/Push Firefox Lite Privacy Notice update (for adding YouTube DATA API)
similar to #8228, we got Firefox Lite's privacy notice updated & localized (except zh-CN, which will be handled separately), and would like to reflect those changes to the web pages:

URL inventory = https://www.mozilla.org/privacy/firefox-lite/
Content available at https://github.com/mozilla/legal-docs/tree/master/firefox_lite_privacy_notice

And the expected publish due day is Dec. 19 PCT time.

### PR DESCRIPTION
**Pull request by alexgibson**
https://github.com/mozilla/bedrock/issues/8315

### CODE REVIEW

**Comment by amychurchwell** [comment]
I feel confused why we are staging the change to the legal docs in this way in bedrock?
Is it because this should be live **on** Dec. 19?
> And the expected publish due day is Dec. 19 PCT time.

I thought the md files within mozilla/legal-docs were consumed by bedrock without a front-end dev task?

**Comment by alexgibson** [comment]
@amychurchwell this is the way legal docs are handled in bedrock. I believe this can go live any time as it’s already public. The due date is a date this needs to be live by.

**Comment by chianger** [comment]
hey @alexgibson  i saw this PR merged two days ago on bedrock, but still don’t see it live on production (https://www.mozilla.org/en-US/privacy/firefox-lite/)
Can we have it publish soon? I’m also curious about the process/leadtime between merging into bedrock and production

**Comment by alexgibson** [comment]
@chianger this went live in our push this morning https://www.mozilla.org/en-US/privacy/firefox-lite/

**Pull request merged**
