### PR TITLE
Import DNT helper via NPM (Fixes #11475)

### LINKED ISSUE #11475: Publish common libs as NPM packages
## Description

We have a few common libraries in bedrock that either have their source code in an external repo, or live in bedrock but are used from time to time in other projects we work on. Making these packages available to import via NPM would help ease project maintenance (as opposed to copying over files manually). 

- Traffic Cop ([external repo](https://github.com/mozilla/trafficcop/))
- Mozilla Cookie Helper  ([bedrock source](https://github.com/mozilla/bedrock/blob/master/media/js/base/mozilla-cookie-helper.js))
- DNT Helper ([bedrock source](https://github.com/mozilla/bedrock/blob/master/media/js/base/dnt-helper.js))

Each lib would need to be exportable both as a global and in CommonJS/ES module format. We could split each lib into separate issues if it makes things easier.

---

#### Success Criteria
- [ ] Common libs are available as NPM packages and imported into bedrock.

### PR DESCRIPTION
**Pull request by alexgibson**
## One-line summary

Removes bedrock DNT helper (and associated tests) in favour of the canonical NPM library: https://github.com/mozmeao/dnt-helper

## Issue / Bugzilla link

#11475

## Testing

http://localhost:8000/en-US/

- [x] `window.Mozilla.dntEnabled()` should still be a globally callable function.
- [x] Should still return `true` or `false` depending on browser DNT setting.

Demo: https://www-demo3.allizom.org/en-US/

- [x] GA script should load with DNT disabled
- [ ] GA script should not load with DNT enabled

### CODE REVIEW

**Comment by nathan-barrett** [comment]
What's the best way to check that GA isn't being loaded? I see the GTM snippet being requested in the Network tab and `window.dataLayer` has three objects in it. Not sure if I'm checking the right things on demo3 - But I checked with DNT both on and off

**Review by nathan-barrett — COMMENTED** [review]
Everything looks good here, but want to wait to merge until I make sure that GTM is being blocked still when DNT is turned on

**Comment by alexgibson** [comment]
@nathan-barrett can you verify the above works for you ok? ^

**Comment by nathan-barrett** [comment]
Working for me, thx @alexgibson

**Review by nathan-barrett — APPROVED** [review]

**Pull request merged**
