### PR TITLE
Add new product FQDNs to Web Bounty Eligible sites

### PR DESCRIPTION
**Pull request by claudijd**
## Description
This is an update of the eligible web properties for new product initiatives

## Testing
Verify that formatting rendered properly for the new sites added.

## Required Reviewers
@moz-jvehent @bhourigan @april

### CODE REVIEW

**Comment by bhourigan** [comment]
I approve the additions to Pocket's bug bounty program.

**Comment by alexgibson** [comment]
Hey just checking in here, as this PR has been open for a while now. 

Whilst this hasn't been reviewed by a bedrock commiter yet, there are a several (external) reviewers listed above tha have not yet commented. Is this something we should leave off our radar until everyone has chimed in?

**Comment by claudijd** [comment]
@alexgibson yes, I will follow up with individual reviewers as a prompt to review.  Some newer domains hadn't been added when this was posted, which have since gone live.

**Comment by jvehent** [comment]
cc @g-k who's a better reviewer than me for bounty topics.

**Comment by claudijd** [comment]
@alexgibson looks like we have a consensus on the reviews.  Feel free to merge when ready.

**Pull request merged**
