### PR TITLE
Update references to bedrock git default branch to main

### LINKED ISSUE #9894: Epic: Rename Git Repo Branches To 'main'
## Description

Using the new name of 'main' for the primary branch in our repos. Work includes doing the rename, locking down the old branch name, and ensuring the pipeline(s) continue to work after the rename.

Related jira story:
https://jira.mozilla.com/browse/SE-1401

Github information:
https://github.com/github/renaming

---

#### Issues
- [ ] bedrock
- [ ] www-config
- [ ] (Fill in this list)

### PR DESCRIPTION
**Pull request by pmac**
Fix #9894

### CODE REVIEW

**Comment by robhudson** [comment]
Looks good.

Should we change the default arg branch name in `bedrock/utils/git.py`?

**Comment by pmac** [comment]
> Should we change the default arg branch name in `bedrock/utils/git.py`?

Good catch. I'll update.

**Comment by robhudson** [comment]
Also master is referenced in the `setup.cfg`. Although with the current requirements workflow I'm not sure if we use paul-mclendahand anymore?

**Comment by pmac** [comment]
> Also master is referenced in the `setup.cfg`. Although with the current requirements workflow I'm not sure if we use paul-mclendahand anymore?

I updated it anyway

**Comment by robhudson** [comment]
Another one: `lib/l10n_utils/management/commands/open_ftl_pr.py`

**Review by robhudson — APPROVED** [review]
r+ for what's here now and with passing tests.

**Comment by pmac** [comment]
> Another one: `lib/l10n_utils/management/commands/open_ftl_pr.py`

I updated the message, but for opening the PR the [l10n repo](https://github.com/mozilla-l10n/www-l10n/) still uses `master` as the default for now.

**Comment by pmac** [comment]
Latest update includes specifying a branch name in settings for all git repos. The Sitemaps and L10n were lacking.

**Pull request merged**
