### PR TITLE
[fix bug 1209992] Update /firefox/push FAQ page

### PR DESCRIPTION
**Pull request by alexgibson**

### CODE REVIEW

**Comment by alexgibson** [comment]
Strings are not yet final, awaiting some feedback in the bug due to inconsistencies in the copy doc.

**Comment by alexgibson** [comment]
Ok strings are final as per @ckprice in [the bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1209992#c23)

@flodolo r?

**Comment by flodolo** [comment]
Looks good, r+

**Comment by alexgibson** [comment]
more changes coming :/

**Comment by ckprice** [comment]
r+ on checking the copy against the bug!

**Pull request merged**
