### PR TITLE
Bug 1649400 - Change nightly like to point to org.mozilla.fenix

### PR DESCRIPTION
**Pull request by JohanLorenzo**
## Description

Full context: https://docs.google.com/document/d/1lG6q7C94xk3ihJKQWTuMeN_lLXpKtg-oC43pj0CwZkw/edit

## Issue / Bugzilla link

https://bugzilla.mozilla.org/show_bug.cgi?id=1649400

### CODE REVIEW

**Comment by JohanLorenzo** [comment]
Thanks for calling this out @alexgibson! I remember @lundjordan, @MihaiTabara, and I were discussing about these product-details link and we tried to actually reach them with bedrock. I remember it was quite a journey to find them. Do we know how many users get our Android builds thanks to these links? 

For the record, there's some significant work for Releng to actually get the product details links updated.

**Comment by alexgibson** [comment]
@JohanLorenzo right now I think all this has done is updated the URL in our schema.org meta data. It hasn't manifested as a visible change on our product pages (like the ones linked above), so to do this properly I think the link would need updating in product details.

**Comment by JohanLorenzo** [comment]
I agree, the update needs to happen in product-details 🙂 Just to know the impact of these links, do you know how often do people hit them, @alexgibson?

**Comment by alexgibson** [comment]
I'll see if I can DM you on Slack re: the above

**Pull request merged**
