### PR TITLE
Fix dependabot.yaml

### PR DESCRIPTION
**Pull request by alexgibson**
## One-line summary

Attempts to fix https://github.com/mozilla/bedrock/pull/14834/checks?check_run_id=28146270934

### CODE REVIEW

**Comment by alexgibson** [comment]
self r+

**Comment by janbrasna** [comment]
inconsequential r+ 😇

I've seen it but was too slow to verify it would work anyways:/ TL;DR dependabot validator checks on PRs before merging are still quite random, they [seem to suffer from super flaky triggering](https://t.ly/yTqA0#/dependabot/dependabot-core/issues/4605) :( and you only get see the results [after](https://github.com/mozilla/bedrock/pull/14903/checks) merging to [main](https://github.com/mozilla/bedrock/runs/28145789268).

**Comment by alexgibson** [comment]
Yeah, perhaps we should have a dependabot validator action (but maybe having that run all the time might be overkill)

**Comment by janbrasna** [comment]
That's super easy via just:

```yaml
on:
  pull_request:
    paths:
      - '.github/dependabot.yml'
```

_(that basically won't even get triggered / start running at all if not matching the glob)_

but the problem is, there's currently no real validator:/ even the schema is [only unofficial](https://t.ly/JS9Im#/dependabot/dependabot-core/issues/1927) — that's why I usually have to work first on the default branch of a fork to see the checks (or action runs), and only then branch it off for proposing.

That's why they have an implicit check appearing whenever the file is touched, but seem to be fighting some race condition effectively making the PR trigger completely random:/

**Comment by janbrasna** [comment]
(For the laughs, dependabot yaml validation kicked in [for a completely unrelated PR](https://github.com/mozilla/bedrock/runs/29112287763) just by rebasing 🙈💣… Magic.)

**Pull request merged**
