### PR TITLE
Update root store policy to 2.9 [fix bug #1851326]

### PR DESCRIPTION
**Pull request by craigcook**
## One-line summary
Publishes the latest version of our CA root store policy.

## Issue / Bugzilla link
https://bugzilla.mozilla.org/show_bug.cgi?id=1851326

## Testing
http://localhost:8000/en-US/about/governance/policies/security-group/certs/policy/

Compare to https://github.com/mozilla/pkipolicy/blob/2.9/rootstore/policy.md

### CODE REVIEW

**Comment by craigcook** [comment]
There may be a few more updates coming so marking this Do Not Merge for the moment.

**Review by BenWilson-Mozilla — COMMENTED** [review]
Looks good to me.

**Comment by craigcook** [comment]
No further updates after all, this is ready for review 👍

**Review by stephaniehobson — APPROVED** [review]
R+ 🐻‍❄️

**Pull request merged**
