### PR TITLE
Migrate Mozilla VPN download page to bedrock (Fixes #11659)

### LINKED ISSUE #11659: Migrate Mozilla VPN download page to bedrock
## Description

The product team would like the VPN download page to move to bedrock.

Implementation details are being ironed out in https://mozilla-hub.atlassian.net/browse/PSP-400

---

#### Success Criteria
- [x] Download page is migrated to bedrock.
- [x] Download goals are set up in GA.
- [x] Downloads are blocked in countries specified by legal
- [x] Strings are ready for L10n.
- [x] GA events / goals are in place.

### PR DESCRIPTION
**Pull request by alexgibson**
## One-line summary

Migrates Mozilla VPN download page to bedrock.

## Significant changes and points to review

- We have a legal requirement to block downloads in certain countries. I added tests for this, but an extra pair of eyes would be good.
- If a locale has translated the bedrock VPN download page, then the landing page will link directly to it.
- If a locale has not yet translated the bedrock download page, then we will continue to link to the existing vpn.mozilla.org download page for that locale.

## Issue / Bugzilla link

#11659

## Screenshots

image

## Checklist

If relevant:

- [x] Tests added

## Testing

- [x] http://localhost:8000/en-US/products/vpn/download/ shows download links for each platform
- [x] http://localhost:8000/en-US/products/vpn/download/?geo=cn should display a "Sorry, Mozilla VPN is not available for download in your country." message.

Successful test run: https://gitlab.com/mozmeao/www-config/-/pipelines/547683048

### CODE REVIEW

**Comment by alexgibson** [comment]
This is ready for code review

**Review by maureenlholland — CHANGES_REQUESTED** [review]
This looks great 🎉 

Well-tested, well-structured, the only issue I could find was a missing string.

**Comment by alexgibson** [comment]
Thanks @maureenlholland, updated!

**Review by maureenlholland — APPROVED** [review]
r+

**Pull request merged**
