### PR TITLE
Refresh: Add CTA pencil banner

### PR DESCRIPTION
**Pull request by reemhamz**
## One-line summary
This pencil banner, which is to be added to all the pages that'll be using the new navigation (https://github.com/mozilla/bedrock/pull/14966), will be replacing the nav CTAs we currently have on www.mozilla.org.

This is currently a WIP 'til the new nav PR gets merged. The placements of files and imports will be updated and refined then, as well. For now, I just did what I could to get the banner showing, which will hopefully reduce whatever integration we need to get done until the new nav descends upon us ✨ 

> [!NOTE]
> Copy for the Firefox pencil banner is currently just placeholder

## Issue / Bugzilla link
Fixes https://github.com/mozilla/bedrock/issues/15095

## Testing
Make sure your `.env` file has the following:

```
SWITCH_M24_HOME=True
SWITCH_M24_ABOUT=True
```

http://localhost:8000/en-US/

### CODE REVIEW

**Comment by reemhamz** [comment]
Converting this back to a draft since work on this is paused

**Comment by stephaniehobson** [comment]
@reemhamz Let's simplify this to just the donate CTA (no Firefox CTA or logic) and open it up for review. I want to make sure we have it merged and are testing it with the new nav :)

**Comment by reemhamz** [comment]
Oh no, I messed up a rebase 🤦🏼 attempting to fix

**Comment by reemhamz** [comment]
Okay, closing this in favor of https://github.com/mozilla/bedrock/pull/15272

**Pull request closed without merging**
