### PR TITLE
Bug 1182225 - change release notes frontend

### PR DESCRIPTION
**Pull request by craigcook**
Moving this to a clean working branch to finish up. This pull request replaces #3216 and #3233.

### CODE REVIEW

**Comment by malena** [comment]
Will be working on this PR :)

**Comment by yglazko** [comment]
Hi Malena! Please let me know if I can help you in anyway or answer any questions. I am on IRC as 'yglazko' and should have my LDAP credentials again by next Monday :)

**Comment by malena** [comment]
Thanks @yglazko! Will do :)

**Comment by malena** [comment]
This is now in a new PR https://github.com/mozilla/bedrock/pull/3581

**Pull request closed without merging**
