### PR TITLE
Update resp_img() helper to support absolute URLs (Fixes #12625)

### LINKED ISSUE #12625: Allow absolute images in resp_img helper
## Description

Contentful images come from their own CDN and [we set their sources as absolute paths](https://github.com/mozilla/bedrock/blob/main/bedrock/contentful/api.py#L123). If we want to use the new `resp_img` helper with Contentful, we need it to work with absolute paths first.

---

#### Success Criteria
- [x] Update `resp_img` to allow absolute paths
- [x] Update `resp_img` tests to confirm new behaviour

### PR DESCRIPTION
**Pull request by alexgibson**
## One-line summary

Updates `resp_img()` helper to support absolute image URLs.

## Issue / Bugzilla link

#12625

## Testing

I added tests but please give this a try locally as well.

### CODE REVIEW

**Review by maureenlholland — CHANGES_REQUESTED** [review]
Tested locally via Contentful Split components on homepage. Suggested change based on allowing use of `resp_img` from Contentful `api.py` in addition to a Jinja template.

Allow ctx to be optional argument
`def resp_img(ctx={}, url=None, srcset=None, sizes=None, optional_attributes=None)`

`Problem with connectHomepage:58YIvwDmzSDjtvpSqstDcL -> <class 'TypeError'>: resp_img() missing 1 required positional argument: 'ctx'`
Making everything optional doesn't feel great but I don't know if there's another way around this if context is only available in templates

✅ the absolute path functionality is working perfectly
Screen Shot 2023-01-24 at 6 04 28 PM

**Comment by alexgibson** [comment]
@maureenlholland updated, thanks

**Comment by alexgibson** [comment]
Oh wait, let me do the same for `picture()` whilst I'm here

**Comment by alexgibson** [comment]
Ok, should be ready

**Review by maureenlholland — APPROVED** [review]
Good thinking on picture update too! Everything works locally from api.py 💯 

This is actually very exciting. Looking forward to simplifying my Contentful branch 🎉  Thanks!

**Pull request merged**
