### PR TITLE
[fix bug 1187246] Remove scroll tracking from Mozilla.org home page

### PR DESCRIPTION
**Pull request by alexgibson**
Scroll tracking does nothing of benefit that is user facing and adds around 10kb (uncompressed) to the JS bundle. We have enough data on this already. Got [approval in the bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1187246#c2) to remove this :+1:

### CODE REVIEW

**Comment by schalkneethling** [comment]
w00t! Not sure but assuming someone more familiar with the tracking bits needs to give this an overview. Looks good to me though. r+

**Comment by alexgibson** [comment]
Thanks @schalkneethling - @jpetto quick r for a second pair of eyes?

**Comment by jpetto** [comment]
Looks good to me. Happy to :zap: extra page weight!

**Comment by jpetto** [comment]
Gareth has requested to put this on a demo prior to merge/push to make sure GTM wont throw errors.

**Comment by alexgibson** [comment]
All we're doing is removing calls to GTM here, but sure :+1:

**Comment by jpetto** [comment]
Gareth confirmed we're good on demo5. Merge time! :clock10:

**Pull request merged**
