### PR TITLE
Remove now-404ing link to a webinar from the H2 2021 Transparency Report page

### LINKED ISSUE #11256: Broken link on H2 2021 Transparency Report
## Description

On https://www.mozilla.org/en-US/about/policy/transparency/jul-dec-2021/ the hyperlink in the phrase 
> a [webinar](https://event.webinarjam.com/register/135/2zmv8i8z) on Lean Data Practice

is 404ing. Maybe it's expired/been archived now the event has passed.

We may need to either remove it, or link to different page.

Source: https://github.com/mozilla/bedrock/blob/master/bedrock/mozorg/templates/mozorg/about/policy/transparency/jul-dec-2021.html#L243

### PR DESCRIPTION
**Pull request by stevejalim**
The H2-22 Transparency Report page contained a link to a webinar, but that had started 404ing. This changeset switches it to a TY recording of the page (hat-tip to @reemhamz for finding it!)

## Issue / Bugzilla link

Resolves #11256 

## Testing

* pull locally 
* `make run-prod`
* visit  localhost:8000/en-US/about/policy/transparency/jul-dec-2021/ and confirm there is no link to the webinar

### CODE REVIEW

**Review by reemhamz — APPROVED** [review]
Good lookin' out here! However, should we probably link the webinar here? I found [this video](https://www.youtube.com/watch?v=GH2sjPmlxnM), which was referenced in the [Afrilabs tweet ](https://twitter.com/AfriLabs/status/1481335153964236800)regarding the subject. r+wc (if we do the wc)

**Comment by pmac** [comment]
We should check with the owners of this content before removing this link IMO.

**Comment by stevejalim** [comment]
@pmac dnazer said to remove it - https://github.com/mozilla/bedrock/issues/11256#issuecomment-1054601916

**Comment by stevejalim** [comment]
@reemhamz @pmac Swapped webinar link for YT video

**Comment by pmac** [comment]
Ah! Thanks for that. I should have checked in the issue 🤦‍♂️ Thanks for the fix!

**Review by reemhamz — APPROVED** [review]
r+! 🚀 Thanks steve

**Pull request merged**
