### PR TITLE
Update firefox/all Android tests

### PR DESCRIPTION
**Pull request by alexgibson**
Fixes: https://gitlab.com/mozmeao/www-config/-/jobs/751098290

Looks like this info changed in product details

### CODE REVIEW

**Comment by pmac** [comment]
I think we should fix the details instead actually. It looks like the issue is that the version has been removed from `mobile_details` and we're basing the string on the version:

https://github.com/mozilla/bedrock/blob/5e35c6434b85dc0c2767c30608f557d51b738272/bedrock/firefox/firefox_details.py#L379

So I think we should change that to just always say `4.1` since we're definitely greater 56 but it's not reported.

**Comment by alexgibson** [comment]
Huh, ok nice find!

**Comment by alexgibson** [comment]
@pmac updated

**Review by pmac — APPROVED** [review]
✅

**Pull request merged**
