### PR TITLE
[fix bug 1238248] Decommission /firefox/push page

### PR DESCRIPTION
**Pull request by alexgibson**

### CODE REVIEW

**Comment by alexgibson** [comment]
Going to add a do-not-merge tag to this just for now, will confirm when this is good to be removed.

**Comment by alexgibson** [comment]
I think we are safe to review/merge this, as the new SUMO article is actively localized now, and the in-product link is already bypassing mozorg anyway (see bug for discussion).

**Comment by jpetto** [comment]
Code all looks good, but can/should we remove the [entry from `firefox/urls.py`](https://github.com/alexgibson/bedrock/blob/bug-1238248-remove-firefox-push-page/bedrock/firefox/urls.py#L108)?

**Comment by alexgibson** [comment]
> Code all looks good, but can/should we remove the entry from firefox/urls.py?

Good catch, removed the URL thanks.

**Comment by jpetto** [comment]
:briefcase: r+!

**Pull request merged**
