### PR TITLE
Add "Donate" link to 404 pages

### LINKED ISSUE #14209: Add CTA to 404 page: Donate.
The 404 page includes three links that give users a opening to explore the site. MoFo would like us to add a 4th - Donate. A link to https://foundation.mozilla.org/en/donate/ can be used for now.

I think we need to be a little careful to use wording that makes it clear the donation is for MoFo.

### PR DESCRIPTION
**Pull request by janbrasna**
## One-line summary

Adds new "Donate" link to CTAs displayed for 404 error pages.

## Significant changes and points to review

- also removes "Explore" item as per #14209
- removes now unused Fluent string for "Explore" CTA
- adds a new string to localize the "Donate" CTA with no fallback currently present
- doesn't use `donate_url()` as the requested URL has different `?form` param and no tags as per https://github.com/mozilla/bedrock/issues/14209#issuecomment-1965308185
- references "heart" icon (used in Protocol as "Give" CTA etc.) as `"default-browser"`, so in case the metaphor changes upstream in future this CTA might also change its icon meaning;)

## Issue / Bugzilla link

Resolves #14209

## Testing

`run-prod` with `DEBUG=False`:
http://localhost:8000/en-US/foo/bar/404/
http://localhost:8000/en-US/careers/position/foo/404/

### CODE REVIEW

**Review by alexgibson — APPROVED** [review]
Thanks @janbrasna the new link looks as expected based on what I see in the issue r+

I did notice one other request in the original issue that is not directly related to the donate link: "Change Firefox family logo for Firefox browser logo in header". Is that something you have time for here as well? No problem if not, just let me know and I can merge this.

Thanks for your efforts!

**Comment by janbrasna** [comment]
@alexgibson I've noticed it, but unlike the other tasks it was not really defined (since it's a generic 404 for all the mozorg pages, incl. other FF products not just the browser i.e. wanted to reconfirm the intent behind that) and was also never brought up in the mockups — so I didn't want the possible discussion delaying the main feature.

Together with removing the "Explore" item, placing "Donate" last, and using the most recent copy from MoFo Digital Engagement, I believe this checks all the other boxes and can be merged (maybe pending owners' ack https://github.com/mozilla/bedrock/issues/14209#issuecomment-2024937669) as-is, and I'll follow up with a proper issue to understand the branding change (and make a separate PR for it eventually…)

**Comment by alexgibson** [comment]
@janbrasna sounds good, I'll hold off merging this until we can a reply to confirm on copy / screenshot.

**Comment by janbrasna** [comment]
@alexgibson Oh I get the branding issue now… But I guess that is blocked by:
- https://github.com/mozilla/protocol-assets/issues/86
- https://github.com/mozilla/protocol/issues/857
that the 404 header uses.

In other words @stephaniehobson would like to see the logo with violet globe ("browser", not the hollow "family"), but still only say "Firefox", right? Currently this can only be changed to show the browser logo only with "Firefox Browser" wordmark in various positions, or without any wordmark at all, as provided by [`protocol_assets`](https://github.com/mozilla/protocol-assets/tree/main/logos/firefox).

Anyhoo the logos are not part of the 404s, it extends `base-error.html` so when time comes, it is to be changed there…

**Comment by alexgibson** [comment]
Looks like copy is confirmed here so we're good to merge 👍

**Pull request merged**
