### PR TITLE
(no bug) Update legal-docs

### PR DESCRIPTION
**Pull request by kyoshino**
## Description

Update the legal-docs submodule to [update Firefox Privacy Notice for Firefox 56](https://groups.google.com/d/topic/mozilla.dev.l10n.web/2nXkv-vzoQw/discussion) shipping today (Friday) at [9am PST](https://bugzilla.mozilla.org/show_bug.cgi?id=1403784#c1) as per @peiying2's request. DO NOT MERGE until https://github.com/mozilla/legal-docs/pull/943 is included. **This needs to be pushed to production today**.

## Issue / Bugzilla link

No bug.

## Testing

Check the Notice page in some locales, and make sure everything looks good. I've already checked the pages locally.

### CODE REVIEW

**Comment by schalkneethling** [comment]
@kyoshino We should also just be sure that the pull request that was merged regarding the firefox-cliqz policy notice is not included. While the notice will display, the formatting will be completely wrong. @see https://github.com/mozilla/legal-docs/pull/934#issuecomment-332770401

It is most likely not part of this, but just wanted to make a note of the above.

**Comment by kyoshino** [comment]
Doh, then we have to cherry pick the commits on legal-docs? Will figure out how.

**Comment by kyoshino** [comment]
Hmm, it's probably better to merge this as is. @schalkneethling can you do it? I don't want to introduce any side effects by using `git cherry-pick`. With https://github.com/mozilla/legal-docs/pull/943 excluded, we'll see some glitches and copy weirdness on the Japanese localized page but it's not completely broken.

**Comment by kyoshino** [comment]
Err, no, the cliqz policy page will be broken then :(

**Comment by kyoshino** [comment]
Okay, I've simply removed the last commit for the cliqz privacy notice. Should be safe to get this merged once the tests passed.

**Pull request merged**
