### PR TITLE
Fix bug 1206021: Upgrade django-pipeline

### PR DESCRIPTION
**Pull request by pmclanahan**
The latest version does error on a broken import in .less files.

I also found and fixed (because it errored) another broken import that
doesn't appear to have been affecting the site.

### CODE REVIEW

**Comment by pmclanahan** [comment]
@jpetto @alexgibson @schalkneethling this should fix it. If you would attempt to break things locally and see if it does indeed break `./manage.py collectstatic`. You will probably have to ensure that your local `static` dir is empty. Best way to do that is by running the following commands:

```bash
$ cd static
$ git clean -fdx
$ cd ..
```
Then run `collectstatic` again and see if it errors where you expect.

**Comment by pmclanahan** [comment]
Another good  (possibly better) test would be to create a branch of your own based on this one, submit a PR, and see if it fails as expected. Travis does **not** cache the static directory, so it should do a full run of the assets every time.

**Comment by schalkneethling** [comment]
It works! \o/ https://sneethling.pastebin.mozilla.org/8847094

**Comment by schalkneethling** [comment]
r+ :fireworks:

**Pull request merged**
