### PR TITLE
Bug 1210368: Convert legacy infra from svn to git for locales.

### PR DESCRIPTION
**Pull request by pmclanahan**
This just changes the deployment and cron scripts. I'll need to manually
update the `locale` dir on the admin node for this to work, so please coordinate
the merging of this with me.

### CODE REVIEW

**Comment by pmclanahan** [comment]
@jgmize r?

@glogiotatidis this is just for legacy infra. Do you think you could knock out the required changes for docker tomorrow? I can take a stab at it as well, but it's nearly the end of my day. Let me know if not and I can hack on it in the morning.

**Comment by jgmize** [comment]
> This just changes the deployment and cron scripts. I'll need to manually
update the locale dir on the admin node for this to work, so please coordinate
the merging of this with me.

I think the updating of the locale dir could have been included in the update scripts by including something along the lines of the following before the `pushd locale`:

```sh
if [[ ! -e locale/.git ]]; then
    rm -rf locale
    git clone git clone https://github.com/mozilla-l10n/bedrock-l10n.git
fi
```

However, I have no objection to you doing this manually as it's a one-time operation, and this looks fine to merge as-is. r+

> @glogiotatidis this is just for legacy infra. Do you think you could knock out the required changes for docker tomorrow? [...]

I believe he already did this in #3416, which I will take a look at next.

**Comment by pmclanahan** [comment]
> I believe he already did this in #3416, which I will take a look at next.

Yes. Just saw that. WOO! Nice work Giorgos :)

**Comment by pmclanahan** [comment]
> I think the updating of the locale dir could have been included in the update scripts

I did consider that, but decided against it because, as you said, one time thing. Though now that you make it look so easy I might throw it in :)

**Comment by pmclanahan** [comment]
I added the check for the `.git` dir in deployment instead of cron since the deployment will fail in the `update_info` task if the locale dir isn't a git repo.

**Comment by jgmize** [comment]
r+, nice work.

**Pull request merged**
