### PR TITLE
Update GHA python job to ubuntu-latest

### PR DESCRIPTION
**Pull request by janbrasna**
## One-line summary

Updates python CI test runner version to JS runner version for consistency.

- [ ] ~I used an AI to write some of this code.~

## Significant changes and points to review

Since #14683 the matching version note is not true anymore. Let's try ubuntu-latest too…

## Issue / Bugzilla link

🚫🐞

### CODE REVIEW

**Review by stevejalim — APPROVED** [review]
Makes sense, but worth us pushing to `mozilla/bedrock:run-integration-tests` first. 

@janbrasna I'll do that now and add a link in the comments. If it passes, feel free to merge

**Comment by stevejalim** [comment]
@janbrasna Here's the integration-tests branch running our headless CI tests on your PR before merging https://github.com/mozilla-sre-deploy/deploy-bedrock/actions/runs/9553708817

**Comment by janbrasna** [comment]
@stevejalim 👍 Thanks. That'd be for someone with write here and access to mozilla-sre-deploy thou, but anyone just lmk if there's any issues in the runs once it finishes. Thanks.

**Comment by stevejalim** [comment]
> and access to mozilla-sre-deploy 

Not to that repo, but write access to `mozilla/bedrock`, yeap

**Pull request merged**
