### PR TITLE
Sanitize release notes markdown using bleach

### LINKED ISSUE #8957: HTML escaping issue on releasenotes content
## Description

[Tests are failing](https://gitlab.com/mozmeao/www-config/pipelines/150816732/failures) on the Firefox 77.0beta releasenotes page.

### Steps to reproduce

1.) Open https://bedrock-test.moz.works/en-US/firefox/77.0beta/releasenotes/
2.) Scroll down to the bottom of the page.

### Expected result

There should be a bottom section with a download button, like on [this page](https://bedrock-test.moz.works/en-US/firefox/76.0beta/releasenotes/):

image

### Actual result

The bottom of the page is missing, due to an HTML escaping issue with a rendered `textarea` in the release notes content. It looks like the rest of the page's HTML is rendered as a string inside the textarea.

image

### Environment

Any browser

### PR DESCRIPTION
**Pull request by pmac**
Also upgrade bleach to 0.5.1

Fix #8957

### CODE REVIEW

**Comment by alexgibson** [comment]
I took a look through a bunch of other release pages and what's in the allowed list seems good 👍

**Comment by alexgibson** [comment]
Oh, looks like circle failed with:

```
ERROR: In --require-hashes mode, all requirements must have their versions pinned with ==. These do not:
    packaging from https://files.pythonhosted.org/packages/46/19/c5ab91b1b05cfe63cccd5cfc971db9214c6dd6ced54e33c30d5af1d2bc43/packaging-20.4-py2.py3-none-any.whl#sha256=998416ba6962ae7fbd6596850b80e17859a5753ba17c32284f67bfff33784181 (from bleach==3.1.5->-r requirements/base.txt (line 145))
```

**Comment by alexgibson** [comment]
Oh hooray for tests, looks like we forgot about headings?

**Comment by pmac** [comment]
we should probably try this on a demo before merging just to spot check some notes

**Comment by alexgibson** [comment]
Yeah good plan 👍

**Pull request merged**
