### PR TITLE
Fix Bug 1139961 - Add iOS to universal download button

### PR DESCRIPTION
**Pull request by craigcook**
Props to Kohei for doing most of the work in #2955

### CODE REVIEW

**Comment by flodolo** [comment]
Removing tag since this PR doesn't actually have any new strings.

**Comment by schalkneethling** [comment]
Following on from IRC:

Setting the classes on the `html` element to: `ios x86 js non-firefox loaded` on the landing page, causes the button inside the grey bar (below the promos) to look as follows:

screen shot 2015-11-06 at 11 51 07

Note: This is how it is currently in production as well so, not introduced by this PR.

**Comment by schalkneethling** [comment]
Ran into the below whilst testing the following scenario:

I have the `firefox-ios-global` switch set to `off` and opened the landing page in the iOS simulator (set to iPhone 6S[if that makes a difference somehow, shouldn't]). With these I get the following:

screen shot 2015-11-06 at 12 29 45

**Comment by schalkneethling** [comment]
With the switch set to `on` I see the following:

screen shot 2015-11-06 at 12 35 58

**Comment by craigcook** [comment]
With the waffle switch off you should see only the coming soon message and not the button, but I'm seeing both as well. I'll work on it.

**Comment by craigcook** [comment]
Alright, I think I sorted out how to keep the button hidden when the switch is off, though it meant tacking on an extra class as a handy toggle.

**Comment by jpetto** [comment]
Closing in favor of rebased #3542.

**Pull request closed without merging**
