### PR TITLE
Update pytest-html to v3.0.0 (Fixes #9603)

### LINKED ISSUE #9603: Test jobs sometimes fail with FileExistsError
## Description

See: https://gitlab.com/mozmeao/www-config/-/jobs/812502093

```
FileExistsError: [Errno 17] File exists: '/app/tests/results/assets'
```

@glogiotatidis submitted a fix to pytest-html to address the issue: https://github.com/pytest-dev/pytest-html/pull/354

Once that fix is published in the next release, we can update bedrock's dependency to fix the problem.

### PR DESCRIPTION
**Pull request by alexgibson**
## Issue / Bugzilla link
https://github.com/mozilla/bedrock/issues/9603

## Testing
https://gitlab.com/mozmeao/www-config/-/pipelines/224270801

### CODE REVIEW

**Comment by alexgibson** [comment]
@pmac I'm seeing a dependency versioning error here:

```
ERROR: In --require-hashes mode, all requirements must have their versions pinned with ==. These do not:
    importlib-metadata>=0.12; python_version < "3.8" from https://files.pythonhosted.org/packages/4a/c3/78826cdf0f7bf2d307aa4c6922aac9bd53c5d4f0de64e7db52771e641c8f/importlib_metadata-3.1.0-py2.py3-none-any.whl#sha256=590690d61efdd716ff82c39ca9a9d4209252adfe288a4b5721181050acbd4175 (from pytest==6.1.2->-r requirements/dev.txt (line 83))
    toml from https://files.pythonhosted.org/packages/44/6f/7120676b6d73228c96e17f1f794d8ab046fc910d781c8d151120c3f1569e/toml-0.10.2-py2.py3-none-any.whl#sha256=806143ae5bfb6a3c6e736a764057db0e6a0e05e338b5630894a5f779cabb4f9b (from pytest==6.1.2->-r requirements/dev.txt (line 83))
    iniconfig from https://files.pythonhosted.org/packages/9b/dd/b3c12c6d707058fa947864b67f0c4e0c39ef8610988d7baea9578f3c48f3/iniconfig-1.1.1-py2.py3-none-any.whl#sha256=011e24c64b7f47f6ebd835bb12a743f2fbe9a26d4cecaa7f53bc4f35ee9da8b3 (from pytest==6.1.2->-r requirements/dev.txt (line 83))
```

What's the best bet to remedy this? Should I add these as explicit requirements?

**Comment by pmac** [comment]
> What's the best bet to remedy this? Should I add these as explicit requirements?

That's exactly it. All dependencies have to be listed in the requirements.txt file. You should be able to use `hashin` to add those and it should work after that.

**Comment by alexgibson** [comment]
@pmac @glogiotatidis I took a pop at fixing this, but I'm now seeing a different error in the test runs. Any ideas?

```
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/venv/lib/python3.7/site-packages/pytest_parallel/__init__.py", line 93, in run
INTERNALERROR>     run_test(self.session, item, None)
INTERNALERROR>   File "/venv/lib/python3.7/site-packages/pytest_parallel/__init__.py", line 54, in run_test
INTERNALERROR>     item.ihook.pytest_runtest_protocol(item=item, nextitem=nextitem)
INTERNALERROR>   File "/venv/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/venv/lib/python3.7/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/venv/lib/python3.7/site-packages/pluggy/manager.py", line 87, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/venv/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/venv/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/venv/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/venv/lib/python3.7/site-packages/pytest_rerunfailures.py", line 194, in pytest_runtest_protocol
INTERNALERROR>     _remove_cached_results_from_failed_fixtures(item)
INTERNALERROR>   File "/venv/lib/python3.7/site-packages/pytest_rerunfailures.py", line 135, in _remove_cached_results_from_failed_fixtures
INTERNALERROR>     result, cache_key, err = getattr(fixture_def, cached_result)
INTERNALERROR> TypeError: cannot unpack non-iterable NoneType object
INTERNALERROR> 
INTERNALERROR> The above exception was the direct cause of the following exception:
INTERNALERROR> 
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/venv/lib/python3.7/site-packages/_pytest/main.py", line 191, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/venv/lib/python3.7/site-packages/_pytest/main.py", line 247, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/venv/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/venv/lib/python3.7/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/venv/lib/python3.7/site-packages/pluggy/manager.py", line 87, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/venv/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/venv/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/venv/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/venv/lib/python3.7/site-packages/pytest_parallel/__init__.py", line 323, in pytest_runtestloop
INTERNALERROR>     six.raise_from(exc, err[1])
INTERNALERROR>   File "<string>", line 3, in raise_from
INTERNALERROR> RuntimeError: pytest-parallel got 4 errors, raising the first from Thread-2.
```

https://gitlab.com/mozmeao/www-config/-/jobs/885598529

**Comment by alexgibson** [comment]
Ok, think I've fixed this by updating `pytest-rerunfailures` 🤞

**Comment by alexgibson** [comment]
Ok, I think this is ready for review: test run is passing https://gitlab.com/mozmeao/www-config/-/pipelines/224270801

**Review by pmac — APPROVED** [review]
Nice! Looks good to me ⛄

**Pull request merged**
