### PR TITLE
Rearrange docker, bin, and script files

### PR DESCRIPTION
**Pull request by pmac**
Also remove old and unused scripts, and integrate integration test properties into the test runner script since we no longer rely on the FS to determine which tests run.

### CODE REVIEW

**Comment by pmac** [comment]
@jgmize this is the "make the location of the files sane again" PR. So it looks big, but not much has changed. It also adds a branch (**run-integration-tests**) and deis app (**bedrock-integration-tests**) for the team to use to run the integration tests against any changes they want, which I added to the docs as well.

**Comment by pmac** [comment]
Oh, and I pushed it to said branch and [all went well](https://ci.us-west.moz.works/blue/organizations/jenkins/bedrock_multibranch_pipeline/detail/run-integration-tests/1/pipeline). Just need your 👍 or 👎 on the new file locations.

```
jenkins  # dir for extra groovy files (e.g. utils.groovy)
docker
    - bin # all deployment scripts
    - envfiles # all env files used by docker run
    - dockerfiles # unchanged
bin  # many files that were in docker/jenkins moved here (all the run-*.sh e.g.)
```

**Comment by alexgibson** [comment]
Not strictly related to this PR, but I just took some time to read through the recent changes and take a look at the `Jenkins` file setup. I think even I can understand this, great work 👍

**Comment by pmac** [comment]
Thanks @alexgibson! Feel free to ask if you have any questions or suggestions.

**Pull request merged**
