### PR TITLE
Use country code for donation links/form instead of locale (Fixes #10741)

### LINKED ISSUE #10741: Improve fundraising banner currency handling
## Description

This isn't something that needs fixing for the imminent 2021 EOY banner, but could definitely be useful for next time. Currently we display currencies and donation values based on page language, using a set of [predefined options here](https://github.com/mozilla/bedrock/blob/master/bedrock/settings/base.py#L880). This has worked well enough over the years, but it assumed a currency based on page language, which isn't always correct as it makes an assumption about someone's geographical location.

Now that we have server-side geo capabilities, we could improve on this logic and pick a currency based on location, irrespective of the page language. Doing this would mean some refactoring of our existing code, and we'd also need to handle displaying the localized currency format in bedrock, as opposed to relyinh on the existing [translated string](https://github.com/mozilla/bedrock/blob/master/l10n/en/banners/fundraising.ftl).

---

#### Success Criteria
- [ ] Fundraising banner is updated to use geo-location for currency and donation value display.

### PR DESCRIPTION
**Pull request by alexgibson**
## One-line summary

Updates home page fundraising banner and `donate_url()` links to use `country_code` for currency handling instead of `locale`. This helps improve situations such as:

- I'm located in the UK but use `de` as my preferred language. I should see currency in GBP instead of EURO.
- I'm located in India but use `en-US` as my preferred language. I should see currency in INR instead of USD.
- I'm in Canada but use `fr` as my preferred language. I should see currency in CAD instead of EURO.

## Significant changes and points to review

I went through each currency we support in the fundraising banner and mapped those to countries using this helpful site: https://www.worlddata.info/currencies/. I had to add some new logic to support this mapping in `base.py`, which could use a sanity check. The list of country codes can be found here: https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements

I also added a new `prefix` donate parameter with some logic to indicate if the currency symbol should come before or after the amount.

Finally, I removed `locale` from donate.mozilla.org link. Their site can handle language negotiation fine. This removes the possibility of bedrock linking to non-existent locales on their end (which then 404).

## Issue / Bugzilla link

#10741

## Testing

Note: You can mock different countries by using the `?geo=` param in the page URL for easier testing. Here are some base tests:

- [x] http://localhost:8000/en-US/ should default to USD
- [x] http://localhost:8000/en-US/?geo=de should display EURO
- [x] http://localhost:8000/en-US/?geo=gb should display GBP
- [x] For each URL above, clicking "Dontate" should take you to https://donate.mozilla.org/ with matching pre-filled parameters.
- [x] The "Donate" link in the footer for each of the above URLs should also contain matching parameters that are pre-filled when the link is clicked.
- [x] http://localhost:8000/en-US/?geo=cn should fall back to USD for unsupported currency/country.
- [x] For the link above, the "Donate" link in the footer should contain no pre-filled parameters. Clicking through should default to whatever donate.mozilla.org decides.

### CODE REVIEW

**Comment by robhudson** [comment]
I took a quick look at the backend changes and thought they looked great.

**Comment by stevejalim** [comment]
Small note from test driving:

> The "Donate" link in the footer for each of the above URLs should also contain matching parameters that are pre-filled when the link is clicked.

If I tweak the frequency or amount of the payment in the banner at the top, that doesn't update the link at the bottom - it continues to show the default from page load (the currency is correct, of course, and the amount selected is the page-load default). I'm assuming this is all fine, yeap?

**Comment by alexgibson** [comment]
> If I tweak the frequency or amount of the payment in the banner at the top, that doesn't update the link at the bottom - it continues to show the default from page load (the currency is correct, of course, and the amount selected is the page-load default). I'm assuming this is all fine, yeap?

This would be a nice to have, but it seems unlikely as expected behaviour to me. I think it's probably fine as-is?

**Review by stevejalim — APPROVED** [review]
This is really nice. 💎 r+!

**Pull request merged**
