### PR TITLE
Unfck EU landing page updates (Fixes #9698)

### LINKED ISSUE #9698: Unfck landing page updates for German
## Description

https://www.figma.com/file/w548NlWIvHvEU0igul9U2H/UNFCK-LP-Redesign?node-id=61%3A168

### PR DESCRIPTION
**Pull request by alexgibson**
## Description
Updates to EU firefox/unfck pages:
- Update background color to give better contrast to mobile app store buttons.
- Add secondary Firefox download CTA at bottom of pages.
- Make action CTAs more button-like.
- Add "Thank you" state for existing Firefox users.
- Simplify & reorder actions.
- Remove social sharing features that have low engagement.
- Remove main navigation and replace with simple masthead.
- Copy updates.

URLs:
- http://localhost:8000/de/firefox/unfck/
- http://localhost:8000/fr/firefox/unfck/

## Issue / Bugzilla link
#9698

## Testing
Demo URLs:

- https://www-demo1.allizom.org/de/firefox/unfck/
- https://www-demo1.allizom.org/fr/firefox/unfck/

Testing:
- [x] Primary and secondary download buttons are visible to non-Firefox users.
- [x] App store buttons are visible to iOS and Android users.
- [x] Firefox "thank you" messaging is visible to Firefox users.

### CODE REVIEW

**Comment by alexgibson** [comment]
There may still be a few last tweaks to some imagery / colors to better compensate the background. Marking this as do-not-merge for now, but can still be code reviewed.

**Review by stephaniehobson — APPROVED** [review]
Solid code, just some UI questions, but no blockers. R+ 🧇 

- Facebook Container can't be installed on mobile, feels weird to promote it
- The app/play store buttons could use an active state (you can[ copy from my /all PR](https://github.com/mozilla/bedrock/pull/9662/files#diff-0c8cd41600eeadff220392bccfcc18aab4e4ccea877c4b4b5c59b19d6472d385R243))
- On mobile Firefox both the Play and App Store badges display in the secondary browser CTA spot. I would have expected it to be platform-specific badges but if they already have it then maybe it makes sense to raise awareness that we're on both mobile platforms.

**Comment by alexgibson** [comment]
> Facebook Container can't be installed on mobile, feels weird to promote it.

They want to keep this for desktop visitors, which is why it's been moved to the bottom of the list.

> The app/play store buttons could use an active state (you can copy from my /all PR)

✅ 

> On mobile Firefox both the Play and App Store badges display in the secondary browser CTA spot. I would have expected it to be platform-specific badges but if they already have it then maybe it makes sense to raise awareness that we're on both mobile platforms.

✅

**Comment by alexgibson** [comment]
@stephaniehobson I pushed another commit with some updated image assets and minor copy changes. Mind a second quick r?

**Comment by alexgibson** [comment]
Ok, this has now been design and copy approved - good to merge.

**Review by craigcook — APPROVED** [review]
Latest changes look good. I definitely like the darker background, too. r+ 🦃

**Pull request merged**
