### PR TITLE
Bug 1233015: Remove and redirect contentservices pages

### PR DESCRIPTION
**Pull request by pmclanahan**

### CODE REVIEW

**Comment by alexgibson** [comment]
Looks like we can also remove the images in `media/img/contentservices`?

**Comment by alexgibson** [comment]
Couple of tests that need removing too, but otherwise r+wc from me :beer:

**Comment by pmclanahan** [comment]
> Looks like we can also remove the images in media/img/contentservices?

good catch. done.

**Comment by pmclanahan** [comment]
Tests are green. Thanks Alex!

**Pull request merged**
