### PR TITLE
Store externalfiles data in the DB.

### PR DESCRIPTION
**Pull request by pmclanahan**
* Add model for externalfiles.
* Add simple dict cache for model instances.
* Add migration for new model.

Only thing left is to fix and add tests. I'll do that in the morning.

### CODE REVIEW

**Comment by pmclanahan** [comment]
@glogiotatidis r?

Wanted to get this to you before your morning since we're getting short on time.

**Comment by pmclanahan** [comment]
I've fixed the tests, so I think this is ready for r?

**Comment by glogiotatidis** [comment]
Apologies for the delay. I'll take a look tomorrow unless @jgmize is faster than me.

**Comment by glogiotatidis** [comment]
Great job! r+ :yum:

**Comment by jgmize** [comment]
lgtm2 :)

**Pull request merged**
