### PR TITLE
Change footer to dark theme

### PR DESCRIPTION
**Pull request by joneskj55**
## Description
This PR adds the dark theme to the nightly/ whatsnew page.
## Issue / Bugzilla link
Issue #9783
## Testing
Tested by running in browser on local machine.

### CODE REVIEW

**Review by craigcook — CHANGES_REQUESTED** [review]
Thanks for the PR! Unfortunately this sets the dark theme for the footer across the entire site. To do it on specific pages we need to pass a theme class to the include on just that page's template, like this:

```
{% block site_footer %}
  {% with theme_class='mzp-t-ink' %}
    {% include 'includes/protocol/footer/footer.html' %}
  {% endwith %}
{% endblock %}
```

Add that at the bottom of all the Nightly template files in https://github.com/mozilla/bedrock/tree/master/bedrock/firefox/templates/firefox/nightly and you should get the ink-colored footer only on those pages without impacting the rest of the site.

**Comment by joneskj55** [comment]
@craigcook Thanks! I'll knock that out and commit here. Quick question, is `mzp-t-ink` the class you want or `mzp-t-dark`? I noticed that ink is more purple and matches with that page but just want to make sure I use the correct class.

**Comment by craigcook** [comment]
> @craigcook Thanks! I'll knock that out and commit here. Quick question, is `mzp-t-ink` the class you want or `mzp-t-dark`? I noticed that ink is more purple and matches with that page but just want to make sure I use the correct class.

I think ink probably works better with the Nightly colors so let's go with that. Thanks!

**Comment by craigcook** [comment]
Oops, I misled you... looks like the language-specific templates all extend other templates, so the only files we really need to change are `firstrun.html` and `whatsnew.html` (the others will get the ink footer from those parent templates).

And I'm not sure why CircleCI failed, doesn't seem related to any of the code changes so maybe just a network issue. Maybe it'll fix itself on the next commit.

**Comment by joneskj55** [comment]
I can go ahead and update those two files and revert the language-specific ones and see if that works.

**Comment by joneskj55** [comment]
That change worked on my local machine. Also, the check passed this time. Hope this works! Fingers crossed 🤞🏾

**Comment by craigcook** [comment]
🤦 I once again misled you. Looks like the firstrun page already has the ink footer, we only need to update `whatsnew.html`. Sorry for all the back-and-forth, thanks for your patience!

**Comment by joneskj55** [comment]
Hahaha no problem, I'll change it real quick!

**Review by craigcook — APPROVED** [review]
There we go, sorry about all that. Looks great, thanks for your contribution! 🌃

**Pull request merged**
