### PR TITLE
Remove contribute.json

### LINKED ISSUE #13878: Remove contribute.json
## Description

Just noticed that https://www.mozilla.org/contribute.json could do with a bit of updating:

```
{
    "name": "Bedrock",
    "description": "The app powering www.mozilla.org.",
    "repository": {
        "url": "https://github.com/mozilla/bedrock",
        "license": "MPL2",
        "tests": "https://ci.vpn1.moz.works/blue/organizations/jenkins/bedrock_multibranch_pipeline/activity/?branch=master" <-- STALE
    },
    "participate": {
        "home": "https://wiki.mozilla.org/Webdev/GetInvolved/mozilla.org", <-- a little stale
        "docs": "http://bedrock.readthedocs.org/",
        "mailing-list": "https://www.mozilla.org/about/forums/#dev-mozilla-org", <-- STALE?
        "irc": "irc://irc.mozilla.org/#www", <-- STALE
        "irc-contacts": [  <-- STALE
            "agibson",
            "craigcook",
            "jpetto",
            "pmac",
            "kohei",
            "jgmize"
        ]
    },
    "bugs": {   <-- STALE? / should be GH now?
        "list": "https://bugzilla.mozilla.org/describecomponents.cgi?product=www.mozilla.org", 
        "report": "https://bugzilla.mozilla.org/enter_bug.cgi?product=www.mozilla.org", 
        "mentored": "https://bugzilla.mozilla.org/buglist.cgi?f1=bug_mentor&o1=isnotempty&query_format=advanced&bug_status=NEW&product=www.mozilla.org&list_id=10866041"
    },
    "urls": {
        "prod": "https://www.mozilla.org",
        "stage": "https://www.allizom.org",
        "dev": "https://www-dev.allizom.org",
        "demo1": "https://www-demo1.allizom.org",
        "demo2": "https://www-demo2.allizom.org",
        "demo3": "https://www-demo3.allizom.org",
        "demo4": "https://www-demo4.allizom.org",
        "demo5": "https://www-demo5.allizom.org"   <-- We should add demos6-9 as well, if we're showing them at all
    },
    "keywords": [
        "django",
        "html",
        "jinja2",
        "protocol",
        "python",
        "sass-css"
    ]
}

```

---

#### Success Criteria
- [ ] Contribute.json contains no stale info

### PR DESCRIPTION
**Pull request by janbrasna**
## One-line summary

Removes no-longer-maintained-standard `contribute.json` [instead](https://github.com/mozilla/bedrock/issues/13878#issuecomment-2025738150) of updating outdated info.

## Significant changes and points to review

> — _Originally posted by @janbrasna in https://github.com/mozilla/bedrock/issues/13878#issuecomment-2025738150:_
> 
> This month www.contributejson.org was taken down and the repo archived, and the scoring was also removed from Observatory:
> - https://github.com/mozilla/http-observatory/pull/526
> - https://github.com/mozilla/http-observatory-website/pull/308
> 
> So while it'd be "nice" to have all the updated content like Matrix instead of IRC, current CI info, all the envs etc., it's probably just time to remove it:/ I guess there is a placeholder for removal in #14229 epic anyways.
> 

Can this have impact in other repos given the root files and Dockerfile, anything mozmeao-related somewhere?
- e.g. [@mozmeao/www-l10n: metadata/mozorg](https://github.com/mozmeao/www-l10n/blob/e25e992bbfd41219c68db20a87dc7e765ba6543a/metadata/mozorg/contribute.json)

## Issue / Bugzilla link

Closes #13878 (refs #14229 epic)

## Testing

_(thinking if it should get a redirect, or 410 gone, or… just, nothing.)_

### CODE REVIEW

**Comment by stevejalim** [comment]
> can this have impact in other repos given the root files and Dockerfile, anything mozmeao-related somewhere?

I don't believe there's anything that automatically consumes the contribute.json from www.m.o so we should be fine to just remove it.

Also, if something DID break as a result, we should fail forward and update that thing to no longer read www.m.o's contribute.json

> (thinking if it should get a redirect, or 410 gone, or… just, nothing.)

I'd say we just let it 404 and keep things simple. A `410 Gone` would be nice, but I'm not sure it's worth the effort.

**Comment by janbrasna** [comment]
@stevejalim Thanks for double checking. Seeing the special treatment some of the root files have, I was more concerned about some steps in building and managing the images for makefile consumption and local development, as I don't have too much insight into that.
Things that might silently count with such files at @mozmeao, like www-site-checker, or here is a metadata reference: https://github.com/mozmeao/www-l10n/blob/e25e992bbfd41219c68db20a87dc7e765ba6543a/metadata/mozorg/contribute.json — I assume all these will eventually get pruned from downstream after removal here, just trying to be extra careful to point out anything that might be related.

**Comment by alexgibson** [comment]
> Things that might silently count with such files at https://github.com/mozmeao, like www-site-checker, or here is a metadata reference: https://github.com/mozmeao/www-l10n/blob/e25e992bbfd41219c68db20a87dc7e765ba6543a/metadata/mozorg/contribute.json — I assume all these will eventually get pruned from downstream after removal here, just trying to be extra careful to point out anything that might be related.

Good eye here, but I think this is unrelated to anything here. The `contribute.json` file in `www-l10n` contains metadata about [contribute.ftl](https://github.com/mozilla/bedrock/blob/main/l10n/en/mozorg/contribute.ftl), so is only related to this `contribute.json` in name only :)

**Review by alexgibson — APPROVED** [review]
r+ thanks @janbrasna

**Pull request merged**
