### PR TITLE
bug-1193839-update-nightly-firstrun-favicon

### PR DESCRIPTION
**Pull request by TheJJ100100**
@jpetto @schalkneethling Redoing pull request for bug 1193839 (Updating nightly first run favicon.)

Previous Pull Request: https://github.com/mozilla/bedrock/pull/3223

Bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1193839

### CODE REVIEW

**Comment by schalkneethling** [comment]
Ok wow, you still have a ton of commits in there ;) Now that you are on a feature branch though, it is going to be much easier to squash them. What you need to do now is:

```
git rebase -i master
```
This will open a editor of sorts and list all of your commits. Now, for all the commits except the one at the very top, change the text from `pick` to `f` (fixup). Save and quit the editor. Once that completes, do:

```
git push -f yourremote bug-1193839-update-nightly-firstrun-favicon # -f is to indicate it is a forced push
```
Thank you for all the effort you are putting into this.

**Comment by TheJJ100100** [comment]
Hi, @schalkneethling when I do "git rebase -i master" I get the message: "Nothing To Do"

**Comment by TheJJ100100** [comment]
Also, I've not really used git before.

**Comment by schalkneethling** [comment]
@TheJJ100100 just to make sure. Before you did the `rebase -i` did you check out this branch? i.e.

```
git checkout bug-1193839-update-nightly-firstrun-favicon
git rebase -i master
```

**Comment by TheJJ100100** [comment]
When I do git checkout, this is the message I get. Already on 'bug-1193839-update-nightly-firstrun-favicon'

**Comment by TheJJ100100** [comment]
Wait, master has all the same commits as master, perhaps?

**Comment by TheJJ100100** [comment]
@schalkneethling any other ideas?

**Comment by TheJJ100100** [comment]
Okay, I did something.. and now, when I do git rebase -i master, the file opens, and where all the commits should be there is just a word, "noop" @schalkneethling

**Comment by TheJJ100100** [comment]
@schalkneethling I think I've done it now. But, when I do "git push -f yourremote bug-1193839-update-nightly-firstrun-favicon" it says yourremote is not a repository. What should I replace yourremote with? Master doesn't work, and neither does bedrock.

**Comment by TheJJ100100** [comment]
I did it! @schalkneethling I just did
    
git rebase -i HEAD~4 


then I did 
    

git push -f

**Comment by schalkneethling** [comment]
r+

**Comment by TheJJ100100** [comment]
@schalkneethling I was reading https://developer.mozilla.org/en/docs/Introduction and it said something about try server access. Do I need to fix more bugs to get access to it? (Just wondering)

**Pull request merged**
