### PR TITLE
Adding cdn tests

### PR DESCRIPTION
**Pull request by duallain**
Using a cdn mark to allow skipping or only running the cdn tests
uses ssllabs to get the tls/cipher information
That can be fairly slow, so trying to ensure it only happens once per run - so caching to a json file

### CODE REVIEW

**Comment by pmac** [comment]
Similar to these tests? https://github.com/mozilla/bedrock/blob/master/test_infra/test_cdn.py

**Comment by duallain** [comment]
> Similar to these tests? https://github.com/mozilla/bedrock/blob/master/test_infra/test_cdn.py

ahh - I took most of this setup from www.firefox.com, but yes it looks like the tests overlap quite a bit :doh:

**Comment by pmac** [comment]
My apologies for not pointing them out sooner. We used them a while back when we were first looking at moving CDNs.

**Comment by duallain** [comment]
@pmac could you take a look again? I decided to migrate the tests into the functional suite - hopefully with the mark I added we can exclude the tests from most situations, but have them when we need it.  We can update docker-compose/makefiles if that helps front/backend devs to skip these tests by default.  (a pointer on that would be helpful if you happen to know the easiest way to do that)

It seemed easier to do it this way, less yaks to shave to get the tests packaged and sent to the www-config pipeline, though it was a pretty close call.

**Review by pmac — APPROVED** [review]
👍

**Pull request merged**
