### PR TITLE
Fix Bug 1193217, reduce physical and file size of images and use highres image helper

### PR DESCRIPTION
**Pull request by schalkneethling**
@alexgibson r?

### CODE REVIEW

**Comment by alexgibson** [comment]
Some image squishing at smaller viewport sizes:

image-aspect-ratio-1

image-aspect-ratio-2

**Comment by schalkneethling** [comment]
Yes, just noticed that. About to push update for it.

**Comment by alexgibson** [comment]
It's a nit pick, but maybe shorten the commit message to something a bit more descriptive e.g. `Fix Bug 1193217 Optimize images on /firefox/tiles`?

**Comment by alexgibson** [comment]
r+ :cake:

**Pull request merged**
