### PR TITLE
Remove local dev-server child-process from default gulp command

### PR DESCRIPTION
**Pull request by alexgibson**
## Description
- Removes running the local dev server as a child-process that's part of the gulp command, as it sometimes causes the heebie jeebies after a rebase.

@craigcook r?

### CODE REVIEW

**Comment by pmac** [comment]
Yeah. This didn't work nearly as well as I'd hoped :(

**Comment by alexgibson** [comment]
> Yeah. This didn't work nearly as well as I'd hoped :(

It was certainly worth a shot 👍.

**Comment by alexgibson** [comment]
@jpetto r?

**Comment by jpetto** [comment]
Should probably update the [FxA docs](https://github.com/mozilla/bedrock/blob/master/docs/firefox-accounts.rst) to reference the new preferred method, e.g. `./manage.py runserver 8111`

**Comment by alexgibson** [comment]
> Should probably update the FxA docs to reference the new preferred method, e.g. ./manage.py runserver 8111

Good spot, updated thanks.

**Comment by jpetto** [comment]
Looks good to me. r+ 👍

**Comment by RCMainak** [comment]
can't wait to give it a try :smile:

**Pull request merged**
