### PR TITLE
Remove platform fields from VPN waitlist form (Fixes #12590)

### LINKED ISSUE #12590: Remove platform interest section from VPN waitlist email form
## Description

Jira ticket: https://mozilla-hub.atlassian.net/browse/VPN-3573

---

#### Success Criteria
- [x] Platforms are removed as fields from the waitlist form
- [ ] Language field removed (TBD)

### PR DESCRIPTION
**Pull request by alexgibson**
## One-line summary

Removes the "What platforms are you interested in?" question from the VPN wait-list form.

## Issue / Bugzilla link

#12590

## Testing

http://localhost:8000/en-US/products/vpn/invite/

### CODE REVIEW

**Comment by alexgibson** [comment]
This is ready for review

**Comment by stephaniehobson** [comment]
Oh sweet, I was just thinking we could probably do this.

**Review by stephaniehobson — CHANGES_REQUESTED** [review]
The string `vpn-landing-invite-page-desc` needs an update now too. Other than that looks good.

**Comment by alexgibson** [comment]
@stephaniehobson thanks, updated

**Comment by alexgibson** [comment]
@stephaniehobson friendly ping reminder - r?

**Pull request merged**
