### PR TITLE
[fix bug 1171899] Campaign landing page - unsupported platforms link color

### PR DESCRIPTION
**Pull request by alexgibson**
* Fixes download button link color for unsupported platforms and iOS messaging.
* Also tweaks the dl button link target a little, to fill its parent container.

### CODE REVIEW

**Comment by schalkneethling** [comment]
@alexgibson How do I trigger the alternate button text? I reckon for iOS I would use the simulator or Chrome but unsupported?

**Comment by alexgibson** [comment]
> @alexgibson How do I trigger the alternate button text? I reckon for iOS I would use the simulator or Chrome but unsupported?

The simplest way is just to use the inspector, and change the class name on `<html>` from `osx` to `ios`, or `oldwin`.

**Comment by schalkneethling** [comment]
@alexgibson Ah yes, that is even simpler :) Should these just be plain text? I am wondering for the 'Sign up to learn more', could this possible be styled as a flat green button?

**Comment by schalkneethling** [comment]
I am wondering, could we do something like:

```
.oldwin .download-button .unsupported-download {
    max-width: 350px;
}
```
screen shot 2015-06-05 at 16 05 13

That way the text will be displayed on only two lines and less scrunched up.

**Comment by alexgibson** [comment]
Good suggestion :+1:

**Comment by alexgibson** [comment]
@schalkneethling updated, thanks

**Comment by schalkneethling** [comment]
r+ :melon:

**Pull request merged**
