### PR TITLE
[bug 1186485] Temporarily disable Windows 10 default CTA

### PR DESCRIPTION
**Pull request by alexgibson**

### CODE REVIEW

**Comment by alexgibson** [comment]
@jpetto r?

**Comment by alexgibson** [comment]
Added DNM tag until @ckprice gives the go-ahead.

**Comment by jpetto** [comment]
LGTM. r+ :watch:

**Comment by ckprice** [comment]
@jpetto please merge. And don't hate me if I ask to reverse this tomorrow :sob:

**Comment by alexgibson** [comment]
Looks like 40.0.2 is landing in a few hours, this might not be needed.

**Comment by ckprice** [comment]
40.0.2 landed! Sorry for the fire drill guys, and thank you so much, but I think we can close this @alexgibson

**Comment by alexgibson** [comment]
Thanks @ckprice closing

**Pull request closed without merging**
