### PR TITLE
Pass THREADS environment variable to LinkChecker script

### PR DESCRIPTION
**Pull request by davehunt**
I missed this variable. @glogiotatidis r?

### CODE REVIEW

**Comment by glogiotatidis** [comment]
BTW can you please remove the extra `/` here https://github.com/mozilla/bedrock/blob/master/bin/run-linkchecker.sh#L9

**Comment by glogiotatidis** [comment]
This looks good r+

**Comment by davehunt** [comment]
@glogiotatidis locally it seemed that I needed the extra slash. The first is a separator used by LinkChecker to indicate the start of the path, and the second allows us to reference the absolute location of the results volume.

**Comment by glogiotatidis** [comment]
> @glogiotatidis locally it seemed that I needed the extra slash. The first is a separator used by LinkChecker to indicate the start of the path, and the second allows us to reference the absolute location of the results volume.

my bad, I didn't know the LinkChecker needed that. Thanks for the explanation.

**Comment by davehunt** [comment]
Merged in https://github.com/mozilla/bedrock/commit/a3a6f4c414de53a8eea02acb5485220fc4649875

**Pull request closed without merging**
