### PR TITLE
[bug 1248040] Update GTM data attributes on firstrun and australis/fi…

### PR DESCRIPTION
**Pull request by JamesDLorence**
…rstrun tabzilla and footer, and base template navigation

Bug 1248040 - https://bugzilla.mozilla.org/show_bug.cgi?id=1248040

### CODE REVIEW

**Comment by alexgibson** [comment]
If you're adding attributes to the australis tour pages, you probably want to also update the base template here, which the firstrun template extends: https://github.com/mozilla/bedrock/blob/master/bedrock/firefox/templates/firefox/australis/fx36/tour.html

**Comment by alexgibson** [comment]
r+wc

**Comment by JamesDLorence** [comment]
I went through and added attributes to the tour.html page you pointed out. Good catch.

**Comment by alexgibson** [comment]
r+

**Pull request merged**
