### PR TITLE
Fix Bug 1180558, aligning video correctly fixes RTL

### PR DESCRIPTION
**Pull request by mermi**

### CODE REVIEW

**Comment by schalkneethling** [comment]
r+ Just needs a squash ~ git rebase -i master will do. Just pick the top most and change the rest from pick to f (fixup). Ping me on IRC if you run into any problems. Thanks!

**Comment by mermi** [comment]
I tried git rebase -i master and it doesn't work for me, I got in output:
error: could not apply 51751e0... change intro direction

When you have resolved this problem, run "git rebase --continue".
If you prefer to skip this patch, run "git rebase --skip" instead.
To check out the original branch and stop rebasing, run "git rebase --abort".

Could not apply 51751e0aba278dbfeb22ef9bae4418f366eaf4cd... change intro direction

**Comment by schalkneethling** [comment]
@mermi Alrighty, here is what I did. Do a git rebase -i master, in the resulting view, delete all of the entries except for the first line `change intro direction`, this will then rebase successfully.

After that, just do a git push -f mermi bug-1180558-about-page-rtl

Let me know if that does not work for you.

**Comment by mermi** [comment]
@schalkneethling done! Thanks.

**Comment by schalkneethling** [comment]
:cake:

**Pull request merged**
