### PR TITLE
Welcome CTA is at top and bottom

### PR DESCRIPTION
**Pull request by hoosteeno**
## Description
This PR puts the welcome CTAs at top and bottom, and modifies some vertical spacing to make the page flow well. I collaborated on it with @cgonz0 so it has been design-reviewed. 

With 2 CTAs we need to modify the FxA flow begin scripts so they can handle an array of buttons but make only a single request for flow. 

Hopefully this does not break existing macro users and does not require any changes for them.

image

### CODE REVIEW

**Comment by alexgibson** [comment]
If there are now 2 buttons on this page we might need to make sure they don't have duplicate IDs, which is used by the integration test here: https://github.com/mozilla/bedrock/blob/master/tests/pages/firefox/welcome/page1.py#L14

**Comment by craigcook** [comment]
> If there are now 2 buttons on this page we might need to make sure they don't have duplicate IDs, which is used by the integration test here: https://github.com/mozilla/bedrock/blob/master/tests/pages/firefox/welcome/page1.py#L14

I think it will also mean refactoring mozilla-monitor-button.js to apply the FxA params to multiple buttons. Right now it's assuming a single button with a unique ID, I think we can change that to either a class or a maybe an array of IDs, just something we can loop through and set the same params on each button.

**Comment by amychurchwell** [comment]
This branch may need a rebase now that https://github.com/mozilla/bedrock/pull/7869 has been merged! Also, should we make this change for welcome 2 also?

**Comment by alexgibson** [comment]
I think we already have logic in place to handle multiple buttons and ID’s https://bedrock.readthedocs.io/en/latest/firefox-accounts.html#id5

**Comment by craigcook** [comment]
> I think we already have logic in place to handle multiple buttons and ID’s https://bedrock.readthedocs.io/en/latest/firefox-accounts.html#id5

We can pass in an ID, but I think that would require firing two different button inits, which would perform the fetch twice, right? Wouldn't it be better to fetch once and apply the same parameters to all the buttons on a page? Or am I misreading mozilla-monitor-button.js?

WNP69 has two Monitor buttons but only one gets initialized. I don't think we've ever done two buttons at once.

**Comment by hoosteeno** [comment]
We have logic for multiple IDs, but unless I'm mistaken, we don't have logic to cache the fetched params. If we init the button twice, we'll cause two different flow begins; get two different flow IDs; and make too many requests. 

I am near to a fix on this.

**Comment by craigcook** [comment]
image

The top button is picking up link styles from the `.mzp-c-hero.mzp-t-dark` rule. But really we should just remove those styles and replace them with `@include light-links;` (and link colors in dark themes is something that needs to change upstream in Protocol; I jumped the gun on this page).

**Comment by amychurchwell** [comment]
Picking up this PR.

**Comment by amychurchwell** [comment]
This work is continued in #7972, closing this PR. 😄

**Pull request closed without merging**
