### PR TITLE
Syncing content with Google doc, part of the l10n hand-over

### PR DESCRIPTION
**Pull request by schalkneethling**
Syncs copy content. r? @pmclanahan @ckprice

### CODE REVIEW

**Comment by schalkneethling** [comment]
Quick question, is the content from this folder synced to the SoTW repo? If not, do we want to continue having this in the SoTW repo or, should I remove it from there?

**Comment by ckprice** [comment]
Thanks Schalk! I'll add a few comments here:

1. The canonical source of truth for content will not be these Google Documents. It will be a Google spreadsheet which is still waiting for approval from Gregory.
2. Big update from today: we will not be translating strings for the 3/31 launch.

> Quick question, is the content from this folder synced to the SoTW repo? If not, do we want to continue having this in the SoTW repo or, should I remove it from there?

I'll let @pmclanahan confirm this, but I believe we are going to be reading JSON directly from bedrock. In the future, the hope is to host the JSON on mozilla/lorax (ref [bug 1113376](https://bugzilla.mozilla.org/show_bug.cgi?id=1113376)), so it may be helpful to keep it in mozilla/lorax unless we think it will cause future confusion.

**Comment by pmclanahan** [comment]
I wouldn't put it in two places. The files in bedrock will be the canonical ones. We may move it to lorax if we get an accept-language header service setup, but even then we'd still have to develop some automated way of generating the translated files into locale directories, so they'd be much different than what's there now. 

My suggestion is to update the strings in bedrock only. We can do the work to move it all to lorax later if it seems worth it.

**Comment by schalkneethling** [comment]
@ckprice Thank you for the updated info, what does this mean for the PR? Should we merge, wait for the spreadsheet to be approved?

@pmclanahan so, should I manually copy over changes to the Lorax repo for now or, leave the files as is and just be concerned with the one's in Bedrock?

**Comment by pmclanahan** [comment]
I wouldn't bother with the files in lorax. Lorax should use the bedrock urls for the data.

**Comment by ckprice** [comment]
> @ckprice Thank you for the updated info, what does this mean for the PR? Should we merge, wait for the spreadsheet to be approved?

It looks like you've added a new structure, so I think this is worth merging even if the content is not 100% approved (meeting today with Gregory about that).

Agree with pmac that we can go ahead and delete the JSON from mozilla/lorax.

**Comment by ckprice** [comment]
jsonlint gives this an r+

**Pull request merged**
