### PR TITLE
Fix Bug 1320098 - Add Fennec Nightly to Android channel page

### PR DESCRIPTION
**Pull request by kyoshino**
## Description

I've split the Fennec Nightly addition from #4382 which has contained mutiple bug fixes. 😓 

## Bugzilla link

[Bug 1320098](https://bugzilla.mozilla.org/show_bug.cgi?id=1320098)

## Testing

The [demo server](https://bedrock-demo-channel-android-nightly.us-west.moz.works/en-US/firefox/channel/android/) will be live soon. Make sure the new Nightly section is displayed, and the download link works properly.

## Checklist
- [x] Requires l10n changes.
- [x] Related functional & integration tests passing.

### CODE REVIEW

**Comment by kyoshino** [comment]
The download links on the demo page are not working because product details are obsolete for some reason. I don't know how to clear the cache...

**Comment by kyoshino** [comment]
As @pascalchevrel pointed out on IRC, one string seems not [localized](https://github.com/mozilla-l10n/www.mozilla.org/blob/master/en-US/firefox/channel/index.lang) yet:

> Check out new Android features in their earliest stages. Enjoy at your own risk.

I've just added a l10n tag so that this can be merged without waiting for the translations.

**Comment by alexgibson** [comment]
I'll defer to @pmac for a review of the Python parts, but at a glance I don't see anything wrong. As far as the front-end changes go, this gets an r+ from me.

**Comment by pmac** [comment]
Python looks fine as well. As soon as things look good on the demo I think we can merge.

**Comment by kyoshino** [comment]
@pmac Thanks! As I said, somehow the product details are outdated on the demo server. Can you update the lib?

**Comment by kyoshino** [comment]
The p-d was updated by @pmac yesterday and the download buttons are now working. Looking good?

**Comment by alexgibson** [comment]
Demo looks good, r+ thanks @kyoshino 🌃

**Pull request merged**
