### PR TITLE
Fixes #11138: Bump Sphinx and dependencies

### LINKED ISSUE #11138: Docs build failing at RTD
## Description

The docs are failing to build properly at Read The Docs due to an issue with the docs dependencies. This is the error from the [build log](https://readthedocs.org/projects/bedrock/builds/15809685/):

```
ERROR: Cannot install -r requirements/docs.txt (line 1) and docutils==0.18.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested docutils==0.18.1
    sphinx 4.1.2 depends on docutils<0.18 and >=0.14
```

### PR DESCRIPTION
**Pull request by robhudson**

### CODE REVIEW

**Review by stevejalim — COMMENTED** [review]
Not sure how this all fits with the dockerized version, but I think docutils might also need a bump?

With python 3.8 (I currently don't have 3.7 running) when i do a local install of these requirements, I get:

```ERROR: Cannot install docutils==0.18.1 and sphinx==4.1.2 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested docutils==0.18.1
    sphinx 4.1.2 depends on docutils<0.18 and >=0.14

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict```

If I do `make docs` from Bedrock's root Makefile, it pulls down a docs container and runs it, but that's got the old 4.1.2 sphinx in it.

**Comment by robhudson** [comment]
It seems like your local install didn't get the changes in this commit? The sphinx version is 4.4 as of this commit, not 4.1.2.

`make docs` is going to pull a production image from docker hub, not one that contains these updated requirements. You have to run `make build` then `docker-compose run app make -C docs/ clean html`.

**Comment by stevejalim** [comment]
@robhudson Ah yeah, re-fetched and got more up to date commits

However, with the local install, when I run `pip install -r requirements/docs.txt --no-cache-dir`

```The conflict is caused by:
    The user requested docutils==0.18.1
    sphinx 4.4.0 depends on docutils<0.18 and >=0.14
```

however if i add the `--no-deps` flag it does install, but whether it has all that's needed is unclear

**Comment by stevejalim** [comment]
But, yeap, the dockerized version builds with Sphinx==4.4.0 👍 - nice one!

**Review by stevejalim — APPROVED** [review]
🎸

**Pull request merged**
