### PR TITLE
Fix revision.txt

### PR DESCRIPTION
**Pull request by pmac**

### CODE REVIEW

**Review by stevejalim — APPROVED** [review]
Looks like it should work, though I remember trying something like this and it still got written as an empty file. Worth a shot!

**Comment by pmac** [comment]
It worked for me locally. We'll see. Thanks!

**Comment by pmac** [comment]
💣  https://www-dev.allizom.org/revision.txt

**Comment by stevejalim** [comment]
@pmac 🎸 🎸 🎸 Nice

**Pull request merged**
