### PR TITLE
Fix Bug 1165125 - Optimize legal pages for RTL

### PR DESCRIPTION
**Pull request by kyoshino**

### CODE REVIEW

**Comment by mermi** [comment]
Hey Kyoshino,
Can you file a screen shoot please, to understand more the issue

**Comment by flodolo** [comment]
@mermi The issue is currently on https://www-dev.allizom.org/ar/about/legal/ and https://www-dev.allizom.org/ar/privacy/

**Comment by mermi** [comment]
Thank you @flodolo   it's clear now

**Comment by craigcook** [comment]
Code and pages look good to me, but I'd value a second opinion from @mermi 
Preliminary r+

**Comment by mermi** [comment]
Look Good for me too, good Work @kyoshino

**Comment by craigcook** [comment]
Thanks @mermi!

**Comment by kyoshino** [comment]
Thanks @mermi again! I'm working on a [mass refactoring](https://github.com/mozilla/bedrock/compare/master...kyoshino:css-rtl-refactoring) for a better RTL experience. Stay tuned.

**Pull request merged**
