### PR TITLE
Update wording in Nothing Personal page's metadata

### LINKED ISSUE #15355: Update the Title Tag and Meta Description of the Nothing Personal Campaign Page
Request from: Louise Morgan

## Description

Please update the Title Tag and Meta Description to these copy below. 
(https://www.mozilla.org/en-US/firefox/nothing-personal/)

Title Tag: Firefox - Nothing Personal. Just Browsing.

Meta Description: Firefox browser is fast, reliable and private. We really don't need your personal data to help you get where you need to go online.

---

#### Success Criteria
- [ ] Reviewed by Adria

### PR DESCRIPTION
**Pull request by clarapenn**
## One-line summary

Updates copy in head elements as per issue.

- [ ] I used an AI to write some of this code.

## Issue / Bugzilla link

Resolves #15355 

## Testing

Go to http://localhost:8000/en-US/firefox/nothing-personal/ and view source, looking for title and meta name="description" tags

### CODE REVIEW

**Comment by stevejalim** [comment]
Because this change is from a community contributor (who I'm mentoring) who can't push to demo servers, I've pushed it up to Demo 5 so that Adria can review

**Comment by a-kyne** [comment]
@stevejalim This is an advertising campaign landing page, so it's out of scope for SEO. Any copy changes should be approved by the campaign owner (but I'm not sure it's worth anyone's effort to change metadata that users will not see).

**Comment by alexgibson** [comment]
> (but I'm not sure it's worth anyone's effort to change metadata that users will not see)

My guess is this is for social sharing, which will often use meta data to create link previews.

**Review by alexgibson — APPROVED** [review]
r+

**Pull request merged**
