### PR TITLE
[fix bug 1243060] Redirect /firefox/tiles to sumo page

### PR DESCRIPTION
**Pull request by alexgibson**

### CODE REVIEW

**Comment by schalkneethling** [comment]
Some tiles references still in `static_media.py`
https://github.com/alexgibson/bedrock/blob/5bf3db3435ce0df92181386bdecb30b50712f7d8/bedrock/settings/static_media.py#L268

https://github.com/alexgibson/bedrock/blob/5bf3db3435ce0df92181386bdecb30b50712f7d8/bedrock/settings/static_media.py#L1188

Not sure if those are used by another page perhaps?

**Comment by schalkneethling** [comment]
Just two possible overlooked references. Other than that, all looks good, and tests/redirects/ all pass.

**Comment by alexgibson** [comment]
@schalkneethling - updated thanks.

**Comment by schalkneethling** [comment]
@flodolo is this safe to merge? I am guessing the tag is a reminder to remove the related strings for the lang files?

**Comment by flodolo** [comment]
Exactly, safe to merge. I need to remove the file completely, hence the tag.

**Comment by flodolo** [comment]
File removed in https://github.com/mozilla-l10n/www.mozilla.org/commit/88beb586ff266a248187ad1b0e963a58912096da

**Pull request merged**
