### PR TITLE
Remove exp/firefox/new/nav (#8304)

### PR DESCRIPTION
**Pull request by stephaniehobson**
## Description

- remove experiment variant of firefox/new with nav
- remove url

## Issue / Bugzilla link

See #8304

### CODE REVIEW

**Comment by stephaniehobson** [comment]
Do not merge until the experiment is shut off in convert.

**Comment by stephaniehobson** [comment]
Experiment is shut off, review away.

**Comment by alexgibson** [comment]
Is it worth adding a redirect for this URL back to the original /exp/firefox/new/ page?

**Comment by stephaniehobson** [comment]
The brand team wants to run another version of this experiment, closing this for now.

**Pull request closed without merging**
