### PR TITLE
Fix Bug 1094435 - GA event tracking for /android/

### PR DESCRIPTION
**Pull request by kyoshino**

### CODE REVIEW

**Comment by alexgibson** [comment]
Codewise this looks fine to me, thanks @kyoshino! Tested locally and all the events seem to be firing ok. 

Before merging, would it be useful to push this to a demo for gareth to verify all the labels seem correct on the GA side? Let me know and I'll be happy to do so.

**Comment by kyoshino** [comment]
Yeah, please push this to a demo server if available.

**Comment by alexgibson** [comment]
This branch is now up on demo1, thanks @kyoshino 

https://www-demo1.allizom.org/en-US/firefox/android/

**Comment by kyoshino** [comment]
Gareth gave us :+1: in the bug. Ready for ship!

**Comment by alexgibson** [comment]
Thanks @kyoshino! r+

**Pull request merged**
