### PR TITLE
bug 1068067 mozilla logo generator in bedrock

### PR DESCRIPTION
**Pull request by nthitz**
added logo to home page

minor cleanup

built version of logo for embed

### CODE REVIEW

**Comment by nthitz** [comment]
I'll note the logo-build.js file is a compiled version of the logo script and the dependencies required to run it for embedding. It is used on the homepage and anywhere else the logo will be embedded. I have a small Makefile that builds it but basically just runs this:

    cat js/logoBuildHeader.js js/d3.js js/lodash.js js/logo.js js/logoBuildFooter.js >> logo-build.js

**Comment by sgarrity** [comment]
This looks great. 

Here are a few initial high-level notes. Nick, I'm not sure which of these are appropriate for you to implement yourself, and which will require our team. I'll just get them all out for now:

 * The logo-build.js is the first time we're loading a JS file async (I think?). It is certainly appriate in this case, but we'll need to work on getting the file built with the existing build system in bedrock.

 * logo-build.js is over 500kb. It does minify down to under 150Kb though, and then gzip down to 65Kb. We'll have to ensure that it *does* indeed get minified/gzipped.
   * Note that I'm not particularly concerned with the weird of the dependencies on the logo-building tool. That's a specialized tool aimed at a specific set of users. I'm more concerned about performance of embedding the logo in high-traffic/visibility locations like the home page.
   * The largest dependency for the logo seems to be d3.js. Is it at all possible to animate the SVG without d3? (I realize this might be an absurd question)

 * We already have a jQuery version in the /lib/ dir. We should probably use this, unless you need the newer version?

 * We shouldn't use in-line JS, as we have Content Security Policy hopes and dreams

 * We should default to a static (PNG?) version of the logo and only load the fancier JS in browsers we know have the required capabilities

Also, lest we frighten any of the other web developers, the animated logo may or may not end up being used on the home page like this, depending on performance issues and further input from Sean Martell. Sean reminded us on a call the other day that the dynamic/animated aspects of the logo are important for people generating custom versions, but a static version can be used where appropriate.

**Comment by ckprice** [comment]
Thanks Steven/Nick.

Below is my recommendation on responsibility. Please review and let me know if this makes sense to you.

> The logo-build.js is the first time we're loading a JS file async (I think?). It is certainly appriate in this case, but we'll need to work on getting the file built with the existing build system in bedrock.

Nick, if you could take a stab at this it would be very much appreciated. As this is very specific to bedrock, it's understandable if you have to hand this off to us.

> logo-build.js is over 500kb. It does minify down to under 150Kb though, and then gzip down to 65Kb. We'll have to ensure that it does indeed get minified/gzipped.

I would think this is something Nick would optimize for us.

> The largest dependency for the logo seems to be d3.js. Is it at all possible to animate the SVG without d3? (I realize this might be an absurd question)

Nick, can you comment on the absurdity of this request?

> We already have a jQuery version in the /lib/ dir. We should probably use this, unless you need the newer version?

> We shouldn't use in-line JS, as we have Content Security Policy hopes and dreams

> We should default to a static (PNG?) version of the logo and only load the fancier JS in browsers we know have the required capabilities

I'm hoping these are things you can take care of Nick.

Once some of these structural items are taken care of, we will go into a much more detailed review of the code.

**Comment by nthitz** [comment]
> The logo-build.js is the first time we're loading a JS file async (I think?). It is certainly appriate in this case, but we'll need to work on getting the file built with the existing build system in bedrock.

I'll take a look into this. Are there any existing examples in bedrock of similar sorts of file concatenation going on that I could examine?

> logo-build.js is over 500kb. It does minify down to under 150Kb though, and then gzip down to 65Kb. We'll have to ensure that it does indeed get minified/gzipped.

> The largest dependency for the logo seems to be d3.js. Is it at all possible to animate the SVG without d3? (I realize this might be an absurd question)

Definitely will want to minify and gzip. I assuming there is some automated method to do this within bedrock easily?

Getting rid of d3.js completely will likely be a bit difficult. I'll investigate if there is a way to make a custom build of d3 containing only the functions that we are using. This will decrease size some for sure, but not 100% sure how much I'll be able to minimize it.

> We already have a jQuery version in the /lib/ dir. We should probably use this, unless you need the newer version?

> We shouldn't use in-line JS, as we have Content Security Policy hopes and dreams

I should be able to fix these things up.

> We should default to a static (PNG?) version of the logo and only load the fancier JS in browsers we know have the required capabilities

Agreed, but I think this deserves a bit more discussion. At the very least I can create a static PNG and include that in bedrock and fallback to it when capabilities are not available. However we may want to discuss if and when this PNG file gets updated. Can we figure out a way to generate a new PNG each week as the data is updated? Do we want to create just one static PNG fallback image or multiple? Considering the number of different combinations of options in the generator tool, it is unlikely that the static image fallback would match a user's selected options from the tool if they are embedding. Potentially could have a backend script that could create PNGs on the fly based on users embed options, but that adds quite a bit of complexity.

**Comment by sgarrity** [comment]
> I'll take a look into this. Are there any existing examples in bedrock of similar sorts of file concatenation going on that I could examine?

Bundles of CSS/LESS files can be defined in base.py. For example:
https://github.com/mozilla/bedrock/blob/master/bedrock/settings/base.py#L128

```python
MINIFY_BUNDLES = {
  'about': (
    'css/sandstone/video-resp.less',
    'css/mozorg/about-base.less',
    'css/mozorg/mosaic.less',
  )
}
```

However, these are usually included in a jinja template. For example:
https://github.com/mozilla/bedrock/blob/master/bedrock/mozorg/templates/mozorg/about.html#L12

```jinja
{{ css('about') }}
```

I'm not sure if those bundles get built only when the template is processed, or (hopefully/presumably) they get processed any time the site is updated/deployed. @pmclanahan or @jgmize can either of you confirm that?


> Agreed, but I think this deserves a bit more discussion. At the very least I can create a static PNG and include that in bedrock and fallback to it when capabilities are not available. However we may want to discuss if and when this PNG file gets updated. Can we figure out a way to generate a new PNG each week as the data is updated? Do we want to create just one static PNG fallback image or multiple? Considering the number of different combinations of options in the generator tool, it is unlikely that the static image fallback would match a user's selected options from the tool if they are embedding. Potentially could have a backend script that could create PNGs on the fly based on users embed options, but that adds quite a bit of complexity.

Building a static PNG based on regularly-updated real data would certainly be cool. That said, Sean Martell tells us that there will be a basic static version for use in places like tshirts/print that can be the most basic fall-back. I think we could rely on this for now.

That said, I would like a dynamically-updating t-shirt... can you do that?

**Comment by pmclanahan** [comment]
> That said, I would like a dynamically-updating t-shirt... can you do that?

Sign me up too please :+1:

**Comment by pmclanahan** [comment]
> I'm not sure if those bundles get built only when the template is processed, or (hopefully/presumably) they get processed any time the site is updated/deployed.

The compilation, concatenation, and minification of the bundles happens at deploy time. When you're in dev mode the bundles are rendered in HTML as a link tag per css file, and the less -> css compilation happens on the fly.

**Comment by nthitz** [comment]
Hey here is an update on progress:
- [x] slimmed down lodash & d3 dependencies quite a bit. logo-build.js is down to around 37k gzipped
- [x] removed jquery dependency
- [x] removed inline scripts
- [x] added static png fallback
- [ ] figured out a way to build logo-build.js within bedrock

I still am a bit unsure about adding `logo-build.js` as a minify build as I'm not 100% how the deploy process works. The problem is both `logoBuildHeader.js` and `logoBuildFooter.js` are not really valid javascript programs, they are just snippets from one. So in development, requesting `<script src="logoBuildHeader.js">` will be an error. However when you build them all as I did with `cat` you do get a valid JS file. If the deploy process were to be concatenate > compile > minify then it might work, but if it's compile > concatenate > minify then I'm not really sure what may happen.

Also you'll notice in `controls.js` as part of the 'embed' copy and paste section, there are hardcoded references to `50.250.207.157`. This is our webserver where we have the static assets used for embedding. Obviously these paths will need to change, but I wasn't 100% how best to do this. These assets needed for the embed `logo-build.js` and `staticLogo.png` at this time will hotlinked from a lot of places if the embed gains popularity. 

I've embedded the logo on the homepage using more or less the embed script provided by the generator tool to show how it would be used. However we could embed the logo on mozilla properties in a more bedrock way given we have that control (e.g. not with an async script)

**Comment by sgarrity** [comment]
Great improvements. Can you explain why the logo-build.js heeds to be wrapped in the header/footer? Could those be called some other say and just be normally concatenated?

Regarding the hard-coded IP address, for other cases where we need to get something from python (usually l10n-strings) into the JS, we add the string to the DOM as a data-attribute. For [example](https://github.com/mozilla/bedrock/blob/63d24a1b0273cf7f104a3c148d9e789ca8680224/bedrock/mozorg/templates/mozorg/contribute/stories-base.html#L15):

```html+jinja
{% block string_data %}
  data-more='{{_('More')}}'
  data-less='{{_('Less')}}'
{% endblock %}
````

The strings are then accessible via something like this: https://github.com/mozilla/bedrock/blob/bd766ce0714ff5d1e5ad80ec79ec9d0caae4e9f9/media/js/base/global.js#L136

**Comment by nthitz** [comment]
The main motivation for the header/footer was managing the dependencies and preventing them from writing to the global scope. Looking into how lodash and d3 actually make themselves available I don't think it ended up making a huge difference. I've deleted the header/footer and have things building without them. Also modified how both of those dependencies add themselves so they don't overwrite anything on the existing page if that object already exists.

I haven't touched those IP addresses yet as I don't think they need to be dynamic, I think we can just update them to where things will be hosted on mozilla.org once those locations are well defined.

**Comment by alexgibson** [comment]
I haven't dug into this PR, but it would be good to pass the main JS files through a linter. Seems to be mainly small things like missing semi-colons and mixed quotes, but enough for JSHint to give up with "Too many errors".

**Comment by nthitz** [comment]
Roger that, I'll go in and clean/lint stuff up!

**Comment by alexgibson** [comment]
When I run this locally and view the homepage, Firefox CPU usage is running around 60-90% when the logo is animating. This is slightly concerning, given how high traffic the home page is. 

Is there a way to bring CPU usage down (limit the frame rate perhaps?). Until now, I didn't even realize the logo was continually animating (past the initial "reveal") to be honest, it moves so slowly?

**Comment by alexgibson** [comment]
Animated / Static options in the generator seem to produce quite different results. Is this intended?

generator

**Comment by alexgibson** [comment]
Might be an idea to use some form of feature detection before the script tries to load? We should probably make it so only browsers capable of displaying the logo download the JS build file and run it.

**Comment by nthitz** [comment]
I've updated the animations to run at a much lower frame rate. This reduces CPU usage in FF quite a bit.

I feel we have gone back and forth on whether or not to use an animated version on the homepage or not. Not sure if that has been 100% decided.

Regarding the difference between the animated/static versions: if you let the animated version play out until the end of it's animation (will take a few minutes) it will end up looking like the static version. (The static version uses the most up to date data, where as the animated version animates through the past few weeks of data). A problem is that the data we are using to generate the logo has been updated since November of 2014. It's hard to analyze the output of the logo when the data is so stale. Also as a few people have noted, the static version does look odd. I'm not 100% sure that the most recent data was "correct" as it seems so anomalous from the rest of the data. @ckprice any idea when that data can be updated?

Also some small changes to dimensions/placement of the logo to prevent the shapes from clipping outside of the SVG boundary.

**Comment by nthitz** [comment]
Also as for IE: I do have checks in place to fallback to a static image if the browser is not SVG capable. Unfortunately IE chokes on part of the d3 library so probably errors out before getting to those specific checks. Not sure the best way to conditionally load the build script based on browser capabilities.

**Comment by ckprice** [comment]
> I feel we have gone back and forth on whether or not to use an animated version on the homepage or not. Not sure if that has been 100% decided.

We will want the embedded logo to animate on an m.o page. Even if it's not on the homepage out of the gate, the goal is to eventually embed it on our properties.

> Regarding the difference between the animated/static versions: if you let the animated version play out until the end of it's animation (will take a few minutes) it will end up looking like the static version. 

I will send a separate email regarding this.

>  @ckprice any idea when that data can be updated?

@pmclanahan will you please generate the most recent data using your newly built script?

**Comment by pmclanahan** [comment]
My new script isn't merged yet. We'll have it soon. After that it will
update automatically.

**Comment by jgmize** [comment]
What are the reasons for using SVG for the animations instead of canvas, given the performance issues?

**Comment by alexgibson** [comment]
> Not sure the best way to conditionally load the build script based on browser capabilities.

I was thinking we could maybe put a feature detect in the `logo-embed.js` snippet, which would only trigger the async script loading if it passes? (assuming async loading is still how the final embed code will end up working).

**Comment by nthitz** [comment]
@jgmize the motivation for SVG was mainly driven by the Mozilla 'M'. In order to get that drawn properly  at any size without aliasing SVG was desired for the pixel precision. (Our original prototype did actually use canvas, however the M didn't look so good) @pmclanahan had the thought of overlaying an SVG for the 'M' on top of a canvas with the shapes which is something I'm going to explore.

Good thoughts @alexgibson thanks! I'll try to make those modifications.

**Comment by nthitz** [comment]
Ah, another motivation for SVG for the logo is for exporting via the logo generator tool. With SVG we can export vector assets easily. With canvas, exports are limited to bitmap graphics. Theoretically could attempt both wherein the logo generator tool uses SVG, but all embeds use canvas...

**Comment by nthitz** [comment]
I've pushed a commit that will enable Canvas for the embed mode and SVG for the logo generator tool. I've also reverted the framerate back to targeting 60fps as the canvas mode should be more performant than the SVG. We can go back to a lower framerate though if it still is too much of a CPU hog.

**Comment by ckprice** [comment]
Thanks Nick! 

- The new range for the Curve Tightness displays a good looking image on both extremes.
- The clipping is much improved (I was unable to reproduce any clipping).

@alexgibson any comments on the Canvas/SVG mode enable, or `logo-embed.js` loading?

**Comment by alexgibson** [comment]
> @alexgibson any comments on the Canvas/SVG mode enable, or logo-embed.js loading?

I'm now seeing an average of around 40% CPU usage (max 50%), which is definitely an improvement :+1: . Given that the animation moves so slowly, I do wonder if we could reduce the tick rate further to save on CPU cycles, without much noticeable difference. But this is definitely a step in the right direction I think. Moving the feature detect to the embed snippet LGTM too.

This PR is also in need of a rebase against master

**Comment by ckprice** [comment]
We're not going to be merging this PR immediately, so I don't know if a rebase against master is necessary.

@pmclanahan @alexgibson what do you guys recommend for "stashing" this code and these comments until we're ready to revisit implementation.

**Comment by pmclanahan** [comment]
Should be fine where it is. We can close this PR if we want to get it out of our site for now. It's easy to reopen later if need be.

**Comment by nthitz** [comment]
I'll experiment this morning with lower framerates and see how much lower I can get CPU usage.

**Comment by nthitz** [comment]
I've updated the animations to target 24 fps. For me this causes cpu usage of ~15% after all the rest of the page has loaded. Going down to 12 fps is possible, but then the initial "popout" animation doesn't look very good so I think this is a pretty happy medium.

**Comment by alexgibson** [comment]
Closing for now and we can re-open in the future as things progress

**Pull request closed without merging**
