### PR TITLE
bug 725905: Implement schema.org for videos

### PR DESCRIPTION
**Pull request by konarkmodi**
Issued a PR for the bug 725905, as changes were described in https://github.com/mozilla/bedrock/pull/1632 .

### CODE REVIEW

**Comment by johnathenphillips** [comment]
Is this closed? I wanted to contribute  to Mozilla using skills that I already have so I selected the "mentored projects" link and found this topic on SEO. If there is work to be done I am familiar with rich markup and may be of some use. Please let me know.

**Comment by johnathenphillips** [comment]
I see that 'craigcook' has closed this bug. Is anyone willing to give me some brief guidance on how I can pick this up? Thanks.

**Comment by alexgibson** [comment]
Hi @johnathenphillips - thanks for inquiring about this bug! This PR was closed as the last person to work on it didn't quite finish off what needed doing. I see you have also commented in [bug 725905](https://bugzilla.mozilla.org/show_bug.cgi?id=725905).

I will assign the bug to you - @kyoshino has kindly linked to the [bedrock docs in the bug](https://bugzilla.mozilla.org/show_bug.cgi?id=725905#c32) to help get you started. Any question please just ask in the bug, or drop into #www on IRC and someone should be around to help.

**Comment by KipOmaha** [comment]
Last night me and john started working the videotags file in the mozorg file folder under templates.
We both decided to go with making an update to you it using the YouTube API. I'm not sure about the server markup but I added it to the iframe as well as added meta information to. I wasn't sure how to incorporate the parameter arguments for "if the video fails load" was thinking about writing a javascript for that...any thoughts, should I push the change to git?

**Comment by alexgibson** [comment]
@KipOmaha - I'm not quite sure I follow your question, or what Schema.org bug has to do with the YouTube API. But may I suggest opening a new PR if you have questions about the current code. This one has been closed for some time. Thanks

**Comment by KipOmaha** [comment]
commment 15: https://bugzilla.mozilla.org/show_bug.cgi?id=725905#c15
I was referring to one of kohei's suggestions for updating and streamlining it with the YouTube API. I will check if kohei has went ahead submitted anything for that idea.

~thanks for the response @alexgibson

**Pull request closed without merging**
