### PR TITLE
Run Karma tests on Travis CI

### PR DESCRIPTION
**Pull request by alexgibson**
Preemptively removing the `tabzilla.js` tests, which means this is now pretty trivial to run on Travis.

### CODE REVIEW

**Comment by schalkneethling** [comment]
This is looking good, can't wait for this to land :+1:

**Comment by alexgibson** [comment]
W00t - tests are green \o/

**Comment by schalkneethling** [comment]
r+ care to squish? Also, are we waiting for someone else to review or, are you happy to merge after squish?

**Comment by alexgibson** [comment]
Few things I want to update first - I'll ping you when I'm done testing, thanks

**Comment by alexgibson** [comment]
@schalkneethling - ok updated, this should be good I think :+1:

**Comment by schalkneethling** [comment]
And Travis agrees! :money_with_wings:

**Pull request merged**
