### PR TITLE
Disable admin, auth, and sessions: fix bug 1251599

### PR DESCRIPTION
**Pull request by jgmize**

### CODE REVIEW

**Comment by jgmize** [comment]
@pmclanahan r?

**Comment by pmclanahan** [comment]
Looks like waffle requires the auth app to be in `INSTALLED_APPS`, but we can remove the rest.

**Comment by pmclanahan** [comment]
Apart from that it looks good. r+wc.

**Comment by jgmize** [comment]
Restored django.contrib.auth to INSTALLED_APPS

**Comment by pmclanahan** [comment]
Tests passing. Thanks!

**Pull request merged**
