### PR TITLE
Bug 1203589 - 'Download a fresh copy' should link to firefox/all/#loc…

### PR DESCRIPTION
**Pull request by pascalchevrel**
…alecode

### CODE REVIEW

**Comment by alexgibson** [comment]
At smaller viewport sizes the localized language text could do with some padding to match the non localized text:

lang-padding

**Comment by alexgibson** [comment]
Other than one small nit, I think this is a great improvement for our visitors. Nice work @pascalchevrel!

**Comment by pascalchevrel** [comment]
Thanks @alexgibson, I have updated the PR to add padding to localized language names on smaller viewports

**Comment by alexgibson** [comment]
Ah, I almost forgot - we're currently running a performance A/B test on the /firefox/new/ page. @pascalchevrel could you please also update [this template](https://github.com/mozilla/bedrock/blob/master/bedrock/firefox/templates/firefox/new2.html) so we don't accidentally lose this change once the test is over? Thanks again.

**Comment by pascalchevrel** [comment]
new2.html updated

**Comment by alexgibson** [comment]
r+ :cake:

**Pull request merged**
