### PR TITLE
bug1138280: new redirection rule to navigate Japanese version release notes.

### PR DESCRIPTION
**Pull request by chikoski**
This pull request will add some redirect rules which naviagate users in ja-locale to Japanese version releasenotes

### CODE REVIEW

**Comment by craigcook** [comment]
We're awaiting more information from release management before we can merge this.

**Comment by cargoworker** [comment]
Can one of the admins verify this patch?

**Comment by jgmize** [comment]
While I personally would have been fine with merging this as-is, the decision has been made to close this without merging. My sincere apologies about this decision and the long delay in coming to one. If it helps, the [developer release notes](https://developer.mozilla.org/en-US/Firefox/Releases/40) do have translation support that do not require special permissions to contribute.

**Comment by jgmize** [comment]
Based on further discussion, the decision to close this PR wasn't as final as I thought. Reopening pending further discussion. Again, apologies.

**Comment by jgmize** [comment]
After further discussion with @sylvestre in IRC, we have approval to merge this after all \o/

I fixed the commit message to match our [style guidelines](http://bedrock.readthedocs.org/en/latest/contribute.html#git-commit-messages) and merged this in bcd60c1590b61d8e56f945d9e123754a5f11377b

**Pull request closed without merging**
