### PR TITLE
Bug 1132231 - fix copy for Webmaker and Hello promos

### PR DESCRIPTION
**Pull request by craigcook**
Per Matej on IRC, I messed up the copy on the Webmaker and Hello promos (small errors, but annoying, and totally my fault).

@flodolo: I am really REALLY sorry about this. If necessary I can wrap these altered strings in yet another tag, if any locales have already updated based on the strings from yesterday. Please tell me what I can do to earn your forgiveness.

### CODE REVIEW

**Comment by flodolo** [comment]
No need to do further wraps, I still haven't pushed out strings (was waiting for the menu).

**Comment by flodolo** [comment]
I'm really confused though. I'm looking at the www-dev server, and even if #2766 was merged:
* don't see a WebMaker promo in /en or /it
* Gear store has a bit promo, instead of a small one
* I see the Hello promo only on /en, not on /it

**Comment by alexgibson** [comment]
Dev issues aside, this looks fine to me r+

Ok to merge @flodolo?

**Comment by flodolo** [comment]
Yes, good to merge.

**Pull request merged**
