### PR TITLE
Fix Bug 1238851 - Decommission Persona pages

### PR DESCRIPTION
**Pull request by kyoshino**
The Privacy Policy and ToS are not included in this PR since the legal team is discussing their plan.

### CODE REVIEW

**Comment by alexgibson** [comment]
It looks like `media/img/persona/title.png` is still used on the existing privacy policy & terms of service pages.

**Comment by alexgibson** [comment]
Aside from the missing image, this looks good to me r+wc

Hopefully we can remove the remaingin privacy policy & terms of service pages soon once they figure out what to do. Thanks @kyoshino!

**Comment by kyoshino** [comment]
Thanks @alexgibson, I just moved the title image back.

**Comment by alexgibson** [comment]
Looks like there is a redirect test left in the old mcom repo that we might need to address: https://github.com/mozilla/mcom-tests/blob/master/tests/test_redirect.py#L41

Perhaps we can remove this if there is already an equivalent test in bedrock for this. I'll take a look.

**Comment by alexgibson** [comment]
The related mcom-test has been removed in favor of the updated bedrock one. r+

Thanks @kyoshino :roller_coaster:

**Pull request merged**
