### PR TITLE
Fix Bug 1169761 - Update Mozilla Websites Privacy Notice

### PR DESCRIPTION
**Pull request by kyoshino**
This should go into production before June 2nd.

### CODE REVIEW

**Comment by ckprice** [comment]
Let's get this merged for the PUSH on Monday at 2 PM PST.

**Comment by kyoshino** [comment]
I'll update this PR on Monday once another change https://github.com/mozilla/legal-docs/pull/356 is merged.

**Comment by ckprice** [comment]
Is there an update on this PR? We have a bedrock push happening at 2 PST today, and this has to be in it.

**Comment by ckprice** [comment]
> I'll update this PR on Monday once another change mozilla/legal-docs#356 for Bug 1169863 is merged.

This has been merged. Feel free to merge this PR.

**Comment by jgmize** [comment]
>>    I'll update this PR on Monday once another change mozilla/legal-docs#356 for Bug 1169863 is merged.

> This has been merged. Feel free to merge this PR.

This PR doesn't yet include that change: the commit with that change is https://github.com/mozilla/legal-docs/commit/f58ed34946907d108f44f829167de904d0675324 but this PR is https://github.com/mozilla/legal-docs/commit/dcbc323819b40575d4cc357899413350cc53ba6a

**Comment by jgmize** [comment]
Thanks @kyoshino, after a discussion with @ckprice due the timing I went ahead and merged this as-is, and I'm filing a separate PR to get the other change.

**Comment by kyoshino** [comment]
Doh, sorry & thanks @jgmize @ckprice

**Pull request merged**
