### PR TITLE
Fix bug 1132961: Add cache to twitter feeds.

### PR DESCRIPTION
**Pull request by pmclanahan**

### CODE REVIEW

**Comment by pmclanahan** [comment]
@jgmize r?

This is a result of me looking at the database tab in New Relic :/

**Comment by pmclanahan** [comment]
@jgmize bump.

**Comment by jgmize** [comment]
Nice work @pmclanahan, sorry about the delay.

**Comment by pmclanahan** [comment]
No worries. I know you're busy. Thanks for the r?.

**Pull request merged**
