### PR TITLE
Add link in footer to /more

### PR DESCRIPTION
**Pull request by rraue**
Fixes https://github.com/mozilla/bedrock/issues/9610

### CODE REVIEW

**Comment by craigcook** [comment]
This is a new string but the template is still in .lang. I think we may need to migrate the whole thing to Fluent before we can change or add any strings. 

One quick hack to get this live ASAP to at least a large portion of users (and robots) would be to make it English-only, wrapped in an `(% if LANG.startswith('en-') %}` condition.

**Comment by rraue** [comment]
@craigcook I thought releasenotes pages are only available in english anyways?!

**Comment by craigcook** [comment]
> @craigcook I thought releasenotes pages are only available in english anyways?!

Ah! Indeed they are. In that case this has no l10n impact after all so no worries.

**Review by craigcook — APPROVED** [review]
🎓

**Pull request merged**
