### PR TITLE
Revert "Skip integration tests because of bug 1513622"

### PR DESCRIPTION
**Pull request by stephaniehobson**
This reverts commit 6e558016e64cb109547f7c86dbc9ce8467762335.

### CODE REVIEW

**Comment by metadave** [comment]
@pmac is the process to skip integration tests documented anywhere?

**Comment by pmac** [comment]
We should probably not merge this until bug 1513622 is resolved. The 404s persist as of now.

**Comment by pmac** [comment]
> is the process to skip integration tests documented anywhere?

Yup https://bedrock.readthedocs.io/en/latest/pipeline.html#configuration

**Comment by alexgibson** [comment]
Could we just skip the `download` tests here, any reason to keep on skipping every test we have?

**Comment by pmac** [comment]
Alex has a great point. @stephaniehobson can you amend this to exclude the `- download` lines and we can get some tests running on deployment again?

**Comment by pmac** [comment]
I've just been told in the bug that the downloads should be working again, and in my personally testing on the page this is true. I think we can just merge this.

**Pull request merged**
