### PR TITLE
Fix Bug 1290691 - Dehardcode iOS for Firefox version in Bedrock settings

### PR DESCRIPTION
**Pull request by kyoshino**

### CODE REVIEW

**Comment by alexgibson** [comment]
Adding a blocker to this until we switch to the new product details as default.

**Comment by kyoshino** [comment]
This is no longer blocked as #4267 has been merged.

**Comment by alexgibson** [comment]
I pulled this locally but looks like I'm getting a `KeyError` for `'ios_version'` on the release notes page?

**Comment by kyoshino** [comment]
I've got the same error but it's gone after running `bin/sync_all` 🔄

**Comment by alexgibson** [comment]
I ran `bin/sync_all` again and it is indeed working, thanks @kyoshino! r+

**Pull request merged**
