### PR TITLE
Update traffic-cop lib (Fixes #9209)

### LINKED ISSUE #9209: Percentage distributions are not quite correct, some branches are being favoured.
We are using traffic cop to divide users among 4 branches, [each receiving 2.5%, totalling 10%](https://github.com/mozilla/bedrock/blob/master/media/js/firefox/welcome/welcome8-traffic-cop.js#L34-L44).

However 2 of our branches are reliably getting 50% more users enrolled than the other 2 branches. Though the total is correct at roughly 10%.
"v=image" and "v=header-text", are getting many more enrolments than the other two.

```
Total Users:
/en-US/firefox/welcome/8/ | 1,165,558(39.77%)
/de/firefox/welcome/8/ | 419,881(14.33%)
/fr/firefox/welcome/8/ | 245,646(8.38%)
/en-GB/firefox/welcome/8/ | 76,227(2.60%)
/en-CA/firefox/welcome/8/ | 17,219(0.59%)

Divided among branches:
/en-US/firefox/welcome/8/?v=header-text | 37,779(1.29%)
/en-US/firefox/welcome/8/?v=image | 37,622(1.28%)
/en-US/firefox/welcome/8/?v=text | 25,585(0.87%)
/en-US/firefox/welcome/8/?v=animation | 25,429(0.87%)
/de/firefox/welcome/8/?v=header-text | 14,016(0.48%)
/de/firefox/welcome/8/?v=image | 13,643(0.47%)
/de/firefox/welcome/8/?v=text | 9,280(0.32%)
/de/firefox/welcome/8/?v=animation | 9,180(0.31%)
/fr/firefox/welcome/8/?v=header-text |  8,168(0.28%)
/fr/firefox/welcome/8/?v=image | 7,789(0.27%)
/fr/firefox/welcome/8/?v=text | 5,370(0.18%)
/fr/firefox/welcome/8/?v=animation | 5,252(0.18%)
/en-GB/firefox/welcome/8/?v=image | 2,497(0.09%)
/en-GB/firefox/welcome/8/?v=header-text | 2,460(0.08%)
/en-GB/firefox/welcome/8/?v=text | 1,642(0.06%)
/en-GB/firefox/welcome/8/?v=animation | 1,616(0.06%)
/en-CA/firefox/welcome/8/?v=image | 599(0.02%)
/en-CA/firefox/welcome/8/?v=header-text | 563(0.02%)
/en-CA/firefox/welcome/8/?v=animation | 395(0.01%)
/en-CA/firefox/welcome/8/?v=text | 387(0.01%)
```

Could this be a `Math.random` issue? 
If it cannot be fixed, can we add this to the documentation? Letting users of traffic cop know that they should select a sample size slightly larger than desired.

### PR DESCRIPTION
**Pull request by alexgibson**
## Description
Updates bedrock's Traffic Cop lib to the latest version from https://github.com/mozilla/trafficcop

## Issue / Bugzilla link
#9209

## Testing
- [ ] Visit http://localhost:8000/en-US/firefox/welcome/8/ and verify the experiment is still serving variations as expected.

### CODE REVIEW

**Comment by ericawright** [comment]
@alexgibson thank you, will this affect the experiment immediately?

**Comment by alexgibson** [comment]
> will this affect the experiment immediately?

Once it hits production yes - is it something you'd rather hold off on until it's finished?

**Comment by ericawright** [comment]
> > will this affect the experiment immediately?
> 
> Once it hits production yes - is it something you'd rather hold off on until it's finished?

After talking with Data Science, yes, we'd rather hold off, it seems we are getting enough traffic even on the 2% branch, so in the interest of keeping things clean, could we wait until the experiment is over?

**Comment by alexgibson** [comment]
Sure, adding a do-not-merge flag 👍

**Comment by alexgibson** [comment]
@ericawright is you experiment still active? Can we merge this yet to get the lib updated?

**Comment by ericawright** [comment]
Yes, it can merge, thank you for checking!

**Review by craigcook — APPROVED** [review]
This looks good to me (matches what's upstream in https://github.com/mozilla/trafficcop/, I don't claim to fully understand all this code). I think we're OK to merge this now? I'm not aware of any currently running TC experiments.

**Comment by alexgibson** [comment]
I think this is safe to merge, thanks

**Pull request merged**
