### PR TITLE
Add brand term detection and replacement to fluent recipe migration script

### LINKED ISSUE #8612: Enhance Fluent migration script to interpolate brand names
## Description

The current Fluent migration script automatically handles things like variables when creating migration recipies, but it does not yet incorporate things like placeables for [brand names](https://github.com/mozilla/bedrock/blob/master/l10n/en/brands.ftl). These have to be done manually (see https://github.com/mozilla/bedrock/pull/8611)

We should update [fluent_recipe.py](https://github.com/mozilla/bedrock/blob/master/lib/l10n_utils/management/commands/_fluent_recipe.py#L126) to handle replacing common brand names with placeables automatically when creating recipies.

### PR DESCRIPTION
**Pull request by pmac**
Fix #8612

## Testing

I ran the following command to test:

```bash
./manage.py fluent recipe bedrock/firefox/templates/firefox/nightly_whatsnew.html
```

### CODE REVIEW

**Comment by pmac** [comment]
Ah yes. Great catch.... Perhaps we need to look for the strings in length order and remove the match from the string before checking for others. I'll try to make that happen. Thanks for the thorough explanation!

**Comment by alexgibson** [comment]
> Perhaps we need to look for the strings in length order and remove the match from the string before checking for others.

I think that might work yeah, great! 👍

**Comment by pmac** [comment]
@alexgibson I've done those updates and it seems to be working much better. Let me know what you think.

**Comment by pmac** [comment]
Doh! Should be fixed now.

**Comment by pmac** [comment]
Oh! You mentioned the docs. Forgot about that. I'll update them quickly before we merge.

**Comment by pmac** [comment]
Docs updated.

**Pull request merged**
