### PR TITLE
Pin Node to 20.8.0 in Docker

### PR DESCRIPTION
**Pull request by alexgibson**
## One-line summary

We've been running into some issues building bedrock in Docker locally on macOS (npm commands hanging indefinitely). Downgrading our node image from 10.11.1 to 10.8.0 seems to fix things for me.

This PR pins us to `node:20.8.0-slim`, and also adds some more verbose command line logging for easier debugging.

## Issue / Bugzilla link

N/A

## Testing

`make clean build`

### CODE REVIEW

**Review by stevejalim — APPROVED** [review]

**Comment by robhudson** [comment]
I tried 4 times and none ever got past the `npm run build` step. But, this is a positive change in general so I'd still be r+ on it.

**Review by robhudson — APPROVED** [review]

**Comment by alexgibson** [comment]
@robhudson i wonder if it might help if you delete some of your old containers / volumes in docker, and then try rebuilding from scratch? That’s the only thing I can think of as to why it might get stuck for you still.

**Comment by janbrasna** [comment]
There are some dependencies that don't fit in this version:

> Screenshot 2024-06-17 at 20 10 37

I don't see anything failing per se, but I'm also fighting with local build issues:/

There's now e.g. `20.14-slim` out, would it be worth trying?

**Comment by alexgibson** [comment]
Thanks for noticing this @janbrasna - I filed a new issue for it here https://github.com/mozilla/bedrock/issues/14705

**Pull request merged**
