### PR TITLE
Activate new footer for more translated locales

### PR DESCRIPTION
**Pull request by stephaniehobson**
## Description

Enable the new footer for more locales

## Issue / Bugzilla link

n/a

## Testing
- new mozilla and firefox footers available in more languages
- no errors rendering new mozilla footer, old mozilla footer, or new firefox footer

### CODE REVIEW

**Comment by stephaniehobson** [comment]
I'm not sure we should merge this until #7904 is fixed.

**Comment by craigcook** [comment]
So it turns out I was wrong (yes, really!) and this won't work anyway. footer.lang needs to be a global shared file by [adding it to the list in settings/base.py](https://github.com/mozilla/bedrock/blob/master/bedrock/settings/base.py#L234).

Then we can remove the conditional logic and start showing the new footer to all locales a bit ahead of when we expected.

**Comment by craigcook** [comment]
Also, if we're removing the conditional logic I suppose that also means we can delete the old Mozilla footer and rename things to lose the -new suffixes and just have footer/firefox.html and footer/mozilla.html ... but that's a bigger change we may want to think through and test.

**Comment by stephaniehobson** [comment]
Closing in favour of https://github.com/mozilla/bedrock/pull/7936

**Pull request closed without merging**
