### PR TITLE
Fix Bug 1214822, redirect ios users to ios product page from choose

### PR DESCRIPTION
**Pull request by schalkneethling**
@alexgibson r?

### CODE REVIEW

**Comment by alexgibson** [comment]
Should this redirect be waffled, like on the [`/new` page](https://github.com/mozilla/bedrock/blob/master/bedrock/firefox/templates/firefox/new.html#L40-L44)?

**Comment by schalkneethling** [comment]
So, the /choose page is going to be redirected to /new until campaign launch so, we probably do not need this to be waffled? Unless the iOS redirect should only become active after the global iOS launch.

**Comment by alexgibson** [comment]
The bug suggests iOS users should be redirected to `firefox/ios` until after the iOS global launch. As far as I understand this is after the campaign launch, hence why we're also using the waffle switch on `/new`. Perhaps best ask in the bug for clarification.

**Comment by schalkneethling** [comment]
@alexgibson That makes sense to me but, let me triple check.

**Comment by alexgibson** [comment]
r+

**Pull request merged**
