### PR TITLE
 Vpn cta variations #10432 

### PR DESCRIPTION
**Pull request by alexgibson**
## Description
Create a variation for the VPN page that updates the header CTA to include annual price which links directly to the payments page, and another link that scrolls down to the pricing options for the user to compare.

**Note**: Replaces https://github.com/mozilla/bedrock/pull/10432

## Issue / Bugzilla link
#10404 

## Testing

Default VPN landing page:
http://localhost:8000/en-US/products/vpn/

Variation A: No change to CTA state
http://localhost:8000/en-US/products/vpn/?entrypoint_experiment=vpn-landing-page-cta-change&entrypoint_variation=a

Variation B: Changed the CTA state to reflect what was in issue #10404 
http://localhost:8000/en-US/products/vpn/?entrypoint_experiment=vpn-landing-page-cta-change&entrypoint_variation=b

Screen Shot 2021-09-09 at 11 45 32 AM

### CODE REVIEW

**Comment by alexgibson** [comment]
@reemhamz hopefully this branch should fix things. Can you check this over to make sure everything looks ok?

**Review by reemhamz — APPROVED** [review]
Looks like it's working perfectly :)

**Comment by slightlyoffbeat** [comment]
Reem & Alex brought up concerns around messaging (stating monthly price and not the lump sum). After discussion with stakeholders, we decided to include the fact that we are fine with this if we state that this is a 12 month plan. This currently is not stated. I've reached out to Elise for advice on how to best incorporate this piece of information and will update here when we have a solution.

**Comment by slightlyoffbeat** [comment]
@reemhamz OK, here are the final changes:

Lets set up this a/b test to not trigger on any URL that contains: utm_medium=cpc

Also, to address concerns, here is the recommended changes from Elise (ignore the hashtag, should still be a dollar sign):

VPN-AB-Mockup


Changes include:
- adding an asterisks to the end of the button text
- including "*For a 12 month plan." to the copy below the button.
- setting up test to not trigger when the URL contains "utm_medium=cpc"

**Comment by reemhamz** [comment]
@slightlyoffbeat so we would just need to update the variation t hat includes the CTA update instead of creating a new variation, is that correct?

**Comment by slightlyoffbeat** [comment]
@reemhamz Correct. This is just an update to that variation. Not a new variation.

Also, Craig mentioned in Slack that he would know how to set up a test to not trigger if there are certain URL parameters if you'd like to ping him for guidance.

**Pull request merged**
