### PR TITLE
Fix Bug 1186022 - Firefox download page sends x86 build to my ARMv8 phone

### PR DESCRIPTION
**Pull request by kyoshino**

### CODE REVIEW

**Comment by kyoshino** [comment]
Tested locally with `navigator.userAgent` and `navigator.platform` provided by @bslassey in the bug.

**Comment by kyoshino** [comment]
Pushed to [demo5](https://www-demo5.allizom.org/en-US/firefox/channel/#developer) by @jpetto

**Comment by kyoshino** [comment]
Brad has confirmed that my fix on demo5 works fine.

**Comment by jgmize** [comment]
Thanks @kyoshino!

**Pull request merged**
