### PR TITLE
[fix bug 1432236] Add dev edition experiment to /firefox/new/.

### PR DESCRIPTION
**Pull request by jpetto**
## Description

Adds experiment placing a callout for Dev Edition on scenes 1 & 2 of `/firefox/new/` for en-US only.

## Issue / Bugzilla link

https://bugzilla.mozilla.org/show_bug.cgi?id=1432236

## Testing

Make sure you have DNT/tracking protection disabled.

https://bedrock-demo-jpetto.us-west.moz.works/en-US/firefox/new/

### CODE REVIEW

**Comment by stephaniehobson** [comment]
I thought they wanted to specifically target visitors from a list of dev-centric referring sites? Did that requirement get dropped?

**Comment by stephaniehobson** [comment]
Oh I see, they want to use this experiment to collect referrals rather than using 2017 data to create a list. As you were.

**Comment by jpetto** [comment]
Talked to pg and will need to add a `dataLayer` call in the Traffic Cop callback function. Will update as soon as I have that info.

**Comment by jpetto** [comment]
PG is verifying the GA stuff, but in the mean time, this should be ready for review.

**Comment by jpetto** [comment]
This is now good for final review.

**Pull request merged**
