### PR TITLE
WNP 111 for EU (Fixes #12720)

### LINKED ISSUE #12720: WNP 111 for EU
## Description

The request is to reuse the copy/layout done for 109 but translate into additional locales: es-ES, IT, pt-PT, PL, and NL. 

We'll need translated PDFs as well, presumably with strings provided via Smartling but Studio will have to create the actual PDFs once we get translations. So I think we'll need to set up some kind of web page to preview the strings for l10n even if we end up putting them into a PDF for the final product.

The design also features an image-as-text header but maybe we can recreate it with live text. Failing that, we'll at least need the translated string as alt text anyway.

Firefox 111 releases **14 March, 2023**

### PR DESCRIPTION
**Pull request by alexgibson**
## One-line summary

Adds two WNPs for FF 111 in several EU languages. One variation promotes the Firefox Translate Add-on, and the other the PDF editor feature.

## Issue / Bugzilla link

#12720

## Testing

Firefox Translate Add-on:

- [x] http://localhost:8000/de/firefox/111.0/whatsnew/
- [x] http://localhost:8000/fr/firefox/111.0/whatsnew/
- [x] http://localhost:8000/en-GB/firefox/111.0/whatsnew/
- [x] http://localhost:8000/en-US/firefox/111.0/whatsnew/?geo=gb

PDF Editor:

- [x] http://localhost:8000/es-ES/firefox/111.0/whatsnew/
- [x] http://localhost:8000/it/firefox/111.0/whatsnew/
- [x] http://localhost:8000/pl/firefox/111.0/whatsnew/
- [x] http://localhost:8000/pt-PT/firefox/111.0/whatsnew/
- [x] http://localhost:8000/nl/firefox/111.0/whatsnew/

### CODE REVIEW

**Comment by alexgibson** [comment]
This is now ready for code review. Note we're still waiting on translations for PL and PT, however code wise this should still be good for review.

**Comment by alexgibson** [comment]
Successful test run: https://gitlab.com/mozmeao/www-config/-/pipelines/798424280

**Comment by alexgibson** [comment]
Thanks @craigcook! Added a commit with some param fixes.

I'm still waiting on the updated line of copy, which might not come in until tomorrow as it's a public holiday in Berlin today. This is fine to sit until then though.

**Comment by alexgibson** [comment]
Rebased after https://github.com/mozilla/bedrock/pull/12854 merged

**Comment by alexgibson** [comment]
@craigcook updated copy is now in place, so this should be good to go. Thanks

**Review by craigcook — APPROVED** [review]
🌎 😈

**Pull request merged**
