### PR TITLE
[fix bug 1333435] /new for Firefox onboarding v2.0 experience

### PR DESCRIPTION
**Pull request by alexgibson**
## Description
- Updated /new page for on-boarding 2.0 funnelcake experiment

## Bugzilla link
https://bugzilla.mozilla.org/show_bug.cgi?id=1333435

## Testing
Demo links (both 99 and 100 versions are identical, one will feature the streamline stub installer, one won't).
- https://bedrock-demo-agibson.us-west.moz.works/en-US/firefox/new/?f=98 (control)
- https://bedrock-demo-agibson.us-west.moz.works/en-US/firefox/new/?f=99
- https://bedrock-demo-agibson.us-west.moz.works/en-US/firefox/new/?f=100

Note: the pages target a specific funnelcake build which will only be available for Windows users, so if you're testing this on a Mac then scene2 will redirect to a 404. You way want to comment out the redirect on `scene2.js` when testing locally.

## Checklist
- [ ] Requires l10n changes.
- [ ] Related functional & integration tests passing.

### CODE REVIEW

**Comment by alexgibson** [comment]
This PR still need rebasing and updating after #4597 is merged to incorporate the new modal.

**Comment by alexgibson** [comment]
OK, the icons for this might change - but this is pretty much code complete and ready for review.

**Comment by alexgibson** [comment]
Page can now be considered final, good for review / merge when ready.

**Comment by craigcook** [comment]
So traffic will be directed via optimizely, so unless someone on an incompatible platform happens to get the direct link with the query string, 404s should be uncommon.

**Pull request merged**
