### PR TITLE
Bug 1324736 firefox os participation hub decommissioning

### PR DESCRIPTION
**Pull request by alisha17**
Bug 1324736 - firefox os participation hub decommissioning

Removed the participation hub section from the page.

### CODE REVIEW

**Comment by alisha17** [comment]
I accidently created this new branch from the branch that I was working earlier on. Hence,it is showing previous branch commits as well. I am fixing the same so that this bug branches out from master.

**Comment by alexgibson** [comment]
Hi @alisha17 - it looks like you've included some commits here from your last PR by mistake. It's generally best practice to start a new branch from master for each PR. To fix this you could cherry pick your commit from this branch into a new one:

```
git checkout -b bug-1324736-firefoxos-participation-hub-decommissioning master
git cherry-pick 460f0d0679e9a8434a57930b56e3b9100ff854a3
```

**Comment by alisha17** [comment]
When I create a new branch with the cherry picked commit, should I create a new pull request for the same ?

**Comment by alexgibson** [comment]
> @alexgibson When I create a new branch with the cherry picked commit, should I create a new pull request for the same ?

Yes that should be fine, we can close this one. Thanks

**Comment by alisha17** [comment]
Created a new pull request : https://github.com/mozilla/bedrock/pull/4558 ,  so as to accommodate the commit for this bug only.

**Comment by alexgibson** [comment]
Closing in favor of #4558

**Pull request closed without merging**
