### PR TITLE
fix no-JS lang switcher (#5931)

### PR DESCRIPTION
**Pull request by Ingi-Hong**
## One-line summary

Fixes the no javascript language switcher that sits in the footer. 

## Significant changes and points to review
- added check in l10n_util render function for any a query parameter called lang. 

## Issue / Bugzilla link

#5931

## Testing

disable JS on your browser, try using the language switcher. 

Not sure what needs to be looked at to ensure this fully works

Tested on Firefox and Chrome. 

- [x] Tried switching languages on root path /
- [x] Tried switching languages on a non root path  
- [x] Tried switching from english to cn and the redirect worked. 
- [x] Tried going to non locale page (careers) and manually putting in parameters into the url -- something like localhost:8000/en-US/careers/?lang=da#. page did not break and parameters were removed on refresh.

### CODE REVIEW

**Comment by alexgibson** [comment]
Closing stale PR, please feel free to reopen should you have time to return to this. Thanks!

**Comment by Ingi-Hong** [comment]
I think at this point I was just waiting for a review

**Comment by Ingi-Hong** [comment]
Hi Alex, doesn't look like I have the permissions to reopen this PR. I think it's ready for review, if you could reopen

**Comment by alexgibson** [comment]
@Ingi-Hong re-opened. If you think this PR is ready for review, can you please update it from draft status? Thanks

**Comment by alexgibson** [comment]
@stevejalim no rush on this one, but can you please take a look here? I'm not sure if there are any downside or potential problems with this solution. The other alternative would be to only show the form if JS is enabled (which I think would be fine also fwiw).

**Comment by alexgibson** [comment]
@Ingi-Hong whilst you're waiting on review here, I noticed there are some linting errors that need fixing: https://github.com/mozilla/bedrock/actions/runs/6773261630/job/18407712116?pr=13336

**Review by stevejalim — COMMENTED** [review]
This works as-is, but I've suggested a change (to not clear the querystring) out of caution/avoiding a subtle bug in the future. 

Minor change requested, please

**Comment by alexgibson** [comment]
@Ingi-Hong - hi, are you still working on this?

**Comment by Ingi-Hong** [comment]
Hi Alex, sorry I turned off notifications for this account to test something and forgot to turn it back on. Will be taking a look at your comment.

**Review by stevejalim — COMMENTED** [review]
Thanks for making the requested change

**Review by stevejalim — APPROVED** [review]
r+ from me but would welcome a local test drive from someone else too - @alexgibson do you have headspace?

**Comment by stevejalim** [comment]
No worries @alexgibson!

@robhudson I recall you're familiar with our locale-related logic. Could you give this an r, too, with a particular eye open for gotchas of the change, please

**Comment by robhudson** [comment]
This *seems* okay at first glance. Basically anywhere we use our own `lib.l10n_utils.render` we would be able to override the chosen language for that page with a `?lang={lang}` query string parameter. Further down in the code, if that language doesn't have a matching translation, it'll redirect.

Since this is a tricky area of our codebase I'd prefer to have tests with this merge to ensure no other repercussions and to also show that this change is intentional.

**Comment by stevejalim** [comment]
Can you suggest any specific files where extra tests could be added @robhudson ?

**Comment by robhudson** [comment]
> Can you suggest any specific files where extra tests could be added @robhudson ?

The `TestRender` class in `lib/l10n_utils/tests/test_base.py` would be excellent.

**Comment by Ingi-Hong** [comment]
Let me know if you want me to squash the commits

**Comment by stevejalim** [comment]
@Ingi-Hong Are you open to adding some tests, too, please? Rob has suggested the file where they would fit:

> > Can you suggest any specific files where extra tests could be added @robhudson ?
> 
> The `TestRender` class in `lib/l10n_utils/tests/test_base.py` would be excellent.

If you need any guidance, let me know

**Comment by Ingi-Hong** [comment]
Sure, I'd be happy try. I'll take a look when I get the chance.

**Comment by alexgibson** [comment]
Closing as per https://github.com/mozilla/bedrock/issues/5931#issuecomment-2003497640

**Pull request closed without merging**
