### PR TITLE
Add a Gitter chat badge to README.md

### PR DESCRIPTION
**Pull request by gitter-badger**
### mozilla/bedrock now has a Chat Room on Gitter

@jgmize has just created a chat room. You can visit it here: [https://gitter.im/mozilla/bedrock](https://gitter.im/mozilla/bedrock?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&content=body_link).

This pull-request adds this badge to your README.md:

[Gitter](https://gitter.im/mozilla/bedrock?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge)

If my aim is a little off, please [let me know](https://github.com/gitterHQ/readme-badger/issues).

Happy chatting.

PS: [Click here](https://gitter.im/settings/badger/opt-out) if you would prefer not to receive automatic pull-requests from Gitter in future.

### CODE REVIEW

**Comment by pmclanahan** [comment]
@jgmize give Gitter some perms did ya?

**Comment by jgmize** [comment]
@pmclanahan the only perms it required were to read my email address and what organizations I was a member of. I created the mozilla/bedrock chatroom myself, and it's not submitting a PR on my behalf, unlike requires.io it uses its own credentials for that, which I like.

**Comment by pmclanahan** [comment]
nice.

**Comment by craigcook** [comment]
We're still experimenting with Gitter so it's not really time to add a badge.

**Pull request closed without merging**
