### PR TITLE
Remove and clone locale dir if not a repo in l10n_update

### PR DESCRIPTION
**Pull request by pmac**

### CODE REVIEW

**Comment by pmac** [comment]
@jgmize r?

**Comment by pmac** [comment]
Maybe we don't need this now? Still wouldn't hurt I guess to have this be the behavior of this command?

**Comment by jgmize** [comment]
I don't think we need this, but you're right that it probably wouldn't hurt to have it for local dev.

**Comment by pmac** [comment]
Agreed. Not necessary. Let's close. Thanks.

**Comment by pmac** [comment]
Reopening as we need this in order to make l10n updates work on www-dev.

**Comment by pmac** [comment]
Hmm... Can't reopen. Will open a new one I guess.

**Comment by pmac** [comment]
Opened #4385

**Pull request closed without merging**
