### PR TITLE
Fix CircleCI demo deploy data

### PR DESCRIPTION
**Pull request by pmclanahan**
* Have it run the fxos feed update
* Have it use the .bedrock-demo-env settings

### CODE REVIEW

**Comment by pmclanahan** [comment]
This fixes the product-details issues as well as the fxos feed one. I've not tried to fix the twitter feeds yet because my understanding is that those require some secrets and we don't want those in the repo. I can work around this if necessary, but I didn't think they were super important.

@alexgibson r?

**Comment by pmclanahan** [comment]
@jgmize you might be interested as well

**Comment by alexgibson** [comment]
Thanks for this @pmclanahan - I guess the Twitter feed things are not super important to have on ad-hoc demo instances. We do have functional tests for such things, but as long as we expect failures here when running the tests against demo I think that's ok. It would be a nice-to-have so we can confidently get green runs, but then if it's a more complicated thing to do then we have to weigh up the level of effort required. I would be happy to go with what we have here for now, and we could always follow up in the future if we decided to :+1:

**Comment by pmclanahan** [comment]
Let me give it a go then before we merge. I should maybe be able to add the twitter setting in Circle as a secret, and it'll use it while populating the DB. Might Just Work:tm:.

**Comment by pmclanahan** [comment]
Okay. I've added the tweets updater and added the secret to circle. So maybe it'll work. I've also pushed this branch as `demo__pmac` to origin, so we'll see in a few min whether it worked.

**Comment by alexgibson** [comment]
Seems all good on demo, so r+ from me!

https://bedrock-demo-pmac.us-west.moz.works/en-US/

**Pull request merged**
