### PR TITLE
Fix bug 1132454: Update platform_img helper for new static files.

### PR DESCRIPTION
**Pull request by pmclanahan**

### CODE REVIEW

**Comment by pmclanahan** [comment]
@jgmize @alexgibson r?

**Comment by pmclanahan** [comment]
Note that for now this assumes that every platform image has at least a file for "windows". If we need to remove that requirement we can, but for now it'll break w/o one.

**Comment by alexgibson** [comment]
I get an error when viewing the privacy tour URL (`en-US/firefox/33.1/whatsnew/?oldversion=28.0`)

`KeyError at /firefox/33.1/whatsnew/
u'data-src-windows'`

**Comment by alexgibson** [comment]
Tested locally and seems to be working as expected for me, JS looks OK. @jgmize has given the thumbs up on the Python parts. r+

**Pull request merged**
