### PR TITLE
Add a git repo utility for working with git external data

### PR DESCRIPTION
**Pull request by pmac**
* Convert l10n_update to use new git utility
* Convert update_security_advisories to use new git utility

This will support easily adding a command to update product-details from git.

### CODE REVIEW

**Comment by pmac** [comment]
@jgmize opinions? not urgent.

r?

**Comment by pmac** [comment]
@glogiotatidis I'd like your opinion as well. Perhaps I'm reinventing some wheel, but all of the git libs I've found are way over complex for what I need, or not great API-wise. I could make it a semi-useful-at-least-within-mozilla separate packed lib though if it works out.

**Comment by pmac** [comment]
I've gone ahead and added a commit to use git to update product details as well. It was pretty simple.

**Comment by pmac** [comment]
@jgmize so this should fix our "prod-details updates are broken" issue with the clock proc. I've not yet removed the data validation code from the bedrock side since it can't really hurt to do it again IMHO, but we can probably trust what's in the git repo.

I'm thinking about changing the data DB import bit to use the file diff list that the `repo.update()` call will give me instead of checking dates in the db. I'll see if I can get an update for that in here shortly.

**Comment by pmac** [comment]
Updated `update_product_details_files` command to use the modified file list returned by the git utility. I'm now writing tests for said command, and then I think we'll be ready to go.

**Comment by pmac** [comment]
Tests added. r?

**Comment by jgmize** [comment]
I wanted to test this in a demo env, so I pushed this to the demo__git-utils branch on this repo. CircleCI ran into the following error during the [build](https://circleci.com/gh/mozilla/bedrock/2464):
```
./manage.py update_product_details --database bedrock
Updating thunderbird_history_major_releases.json from server
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/product_details/management/commands/update_product_details.py", line 64, in handle
    self.download_directory()
  File "/usr/local/lib/python2.7/dist-packages/product_details/management/commands/update_product_details.py", line 81, in download_directory
    if not self.download_json_file(urljoin(dir, json_file)):
  File "/usr/local/lib/python2.7/dist-packages/product_details/management/commands/update_product_details.py", line 171, in download_json_file
    self._storage.update(json_file, resp.text, resp.headers.get('Last-Modified'))
  File "/usr/local/lib/python2.7/dist-packages/product_details/storage.py", line 233, in update
    shutil.move(tf.name, filename)
  File "/usr/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/usr/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 13] Permission denied: u'/usr/local/lib/python2.7/dist-packages/product_details/json/thunderbird_history_major_releases.json'
make: *** [sync-all] Error 1
```

**Comment by pmac** [comment]
I've added changes to fix the PR tests and demo deployment, and [the demo](https://bedrock-demo-git-utils.us-west.moz.works/en-US/) that @jgmize was attempting to deploy has been deployed.

**Comment by jgmize** [comment]
The refactoring and additional tests look like an improvement overall, and things lgtm on the demo so far, but I haven't seen a new commit come in to verify the updating in place so I'd like to wait until that happens to fully verify functionality. Also, I believe there's a bug for switching p-d to use the git repo, so you probably want to add that to the commit that switches it, and if there are any other bugs that this work relates to you may want to add those as well, along with perhaps squashing this down to fewer commits.

**Comment by pmac** [comment]
Did some squarshing and updating of commit messages. Hopefully good to go now.

**Pull request merged**
