### PR TITLE
Fixed #9414 - Updated title/bios for Dana, Dave and Leslie

### LINKED ISSUE #9414: Leadership Page Changes
## Description

**For Leslie Gray**
Title changes to:
Head of Diversity & Inclusion and Chief of Staff, Office of the CEO

First paragraph changes to:
Leslie is Head of Diversity and Inclusion and Chief of Staff to the CEO of Mozilla Corporation. As Head of Diversity and Inclusion, Leslie is responsible for Mozilla’s global inclusion strategy and programs across our own culture, as shown in our products, and in how we build community beyond Mozilla. Leslie is also responsible for managing business operations for the Office of the CEO and supporting strategic projects on behalf of the Office of the CEO. 

**For Dave Camp**
Title changes to:
Chief, Firefox Products

First paragraph changes to:
As Chief, Firefox Products, Dave Camp is responsible for all product management, engineering, technology and operations in support of Firefox products, services and web platform.

**For Dana Bennett**
Title changes to:
SVP, People Team

First paragraph changes to:
As SVP, People Team, Dana is responsible for all aspects of Human Resources including Talent Acquisition, Learning and Development and Organizational Development.

### PR DESCRIPTION
**Pull request by maxxcrawford**
## Description

Copy updates to leadership title/bios

## Issue / Bugzilla link

#9414 

## Testing

Confirm copy from Leadership page.

## Screenshots (from local)

image

image

image

image

### CODE REVIEW

**Comment by pmac** [comment]
NIT: Git commit messages should be in active voice. Instead of "Fixed ..." it should be "Fix ...".

e.g. `Fix #9414 Update title/bios for Dana, Dave and Leslie`

**Comment by pmac** [comment]
The [Webdev Bootcamp docs](https://mozweb.readthedocs.io/) are a bit out of date, but the [Git page](https://mozweb.readthedocs.io/en/latest/reference/git_github.html) is still good.

**Review by craigcook — APPROVED** [review]
🚲

**Comment by pmac** [comment]
Okay. But I still think keeping the git log nice by following git commit message guidelines is a good thing.

**Comment by craigcook** [comment]
> Okay. But I still think keeping the git log nice by following git commit message guidelines is a good thing.

I amended the message when I merged: https://github.com/mozilla/bedrock/commit/e57dbb6461abe6b25e62a14c70b130acd472051f

**Comment by pmac** [comment]
I didn't see that! Thanks Craig ❤️

**Comment by maxxcrawford** [comment]
Thanks to both of you! Active voice from here on out.

**Pull request merged**
