### PR TITLE
[fix bug 1187467] Remove Fx 35.0.1 firstrun growth tests.

### PR DESCRIPTION
**Pull request by jpetto**

### CODE REVIEW

**Comment by alexgibson** [comment]
Ca this asset be removed too? `/media/img/firefox/australis/growth-firstrun-sprite.png`

**Comment by alexgibson** [comment]
Are any of these settings still needed? https://github.com/mozilla/bedrock/blob/master/bedrock/settings/base.py#L692-L716

**Comment by jpetto** [comment]
Good catches. :fishing_pole_and_fish: Removing both.

**Comment by alexgibson** [comment]
r+ :deciduous_tree:

**Pull request merged**
