### PR TITLE
[fix bug 1260370] Update Hello copy on /firefox/products/ page

### PR DESCRIPTION
**Pull request by alexgibson**
## Description
Updates the line of Hello copy on the /firefox/products page to better describe what the product now delivers.

## Bugzilla
https://bugzilla.mozilla.org/show_bug.cgi?id=1260370

## Checklist
- [x] Requires l10n changes.

### CODE REVIEW

**Comment by alexgibson** [comment]
CC @flodolo - do we already have this line of copy translated elsewhere?

**Comment by flodolo** [comment]
No, we don't :-\

**Comment by alexgibson** [comment]
Would it make things better if we suggested using this? `"Instantly browse any Web page with a friend."`?

**Comment by flodolo** [comment]
We would still the tag, but at least I could import the string from existing files (assuming the space available is roughly the same)

**Comment by alexgibson** [comment]
Discussed on IRC with @flodolo and we're going to keep the new string. Won't be pushed out for translation until later this week, but we're good to review/merge.

**Comment by schalkneethling** [comment]
r+ :monkey:

**Pull request merged**
