### PR TITLE
add instruction to use staging instance when testing crash-stats

### PR DESCRIPTION
**Pull request by fkiriakos07**
## One-line summary

add instruction to use staging instance when testing crash-stats.

### CODE REVIEW

**Review by dveditz — COMMENTED** [review]
I can't find a crash-reports.mozilla.org server in DNS, nor referenced in Firefox code. Is it an old name that isn't used anymore? Let's drop it.

If it _is_ used then we need to address how the staging instance applies to that server (I assume not at all from the name). for example, it might be clearer to add   "... for testing _**instead of crash-stats.mozilla.org**_."

But I suspect we just drop the crash-reports entry and then your addition makes perfect sense.

**Comment by fkiriakos07** [comment]
Thanks Dan, makes sense. if I remember correctly, when we looked at the list of sites a few months ago, we found some paths that were under crash-reports, I could be wrong though. I can try to find the owners and ask them to be sure.

**Comment by fkiriakos07** [comment]
I talked to the engineer who works on crash ingestion and he mentioned that crash-reports is the ingestion API for the reports, it is a POST endpoint, this is its documentation: https://socorro.readthedocs.io/en/latest/spec_crashreport.html

I updated the PR to include a note about using staging instance for crash-reports too

**Comment by willkg** [comment]
> I can't find a crash-reports.mozilla.org server in DNS, nor referenced in Firefox code. Is it an old name that isn't used anymore? Let's drop it.
> 
> If it _is_ used then we need to address how the staging instance applies to that server (I assume not at all from the name). for example, it might be clearer to add "... for testing _**instead of crash-stats.mozilla.org**_."
> 
> But I suspect we just drop the crash-reports entry and then your addition makes perfect sense.

Note that it's crash-reports.mozilla.COM and crash-stats.mozilla.ORG. We don't have crash-reports.mozilla.ORG in DNS because we don't use that domain.

**Review by dveditz — APPROVED** [review]
Perfect, thanks! sorry I missed the .com when looking for the crash-reports site.

**Comment by willkg** [comment]
It's very confusing. It's what happens when we have systems that have been around for many many years. :p

**Comment by fkiriakos07** [comment]
@craigcook @stevejalim this was approved, can you please take a look?

**Review by stevejalim — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
