### PR TITLE
Backend dependency updates

### PR DESCRIPTION
**Pull request by stevejalim**
Check integration tests status before merging: https://github.com/mozilla/bedrock/actions/runs/7799796878

# Prod
Handles #14163: Bump pygithub from 2.1.1 to 2.2.0
Handles #14156: Bump boto3 from 1.34.25 to 1.34.32
Handles #14164: Bump botocore from 1.34.25 to 1.34.32
Handles #14155: Bump sentry-sdk from 1.39.2 to 1.40.0
Handles #14153: Bump newrelic from 9.5.0 to 9.6.0
Handles #14165: Bump pyopenssl from 23.3.0 to 24.0.0
Handles #14151: Bump cryptography from 41.0.7 to 42.0.2

# Dev
Handles #14160: Bump ruff from 0.1.14 to 0.1.15
Handles #14149: Bump pytest-django from 4.7.0 to 4.8.0

# Docs
Handles #14154: Bump sphinx-rtd-theme from 1.3.0 to 2.0.0
Handles #14152: Bump sphinxcontrib-websupport from 1.2.4 to 1.2.7

Supdeps updated in passing:

Also, fix up minor formatting niggles in docs source

### CODE REVIEW

**Comment by robhudson** [comment]
I also have this PR if you'd like to fold it into here. I was thinking that would land before we did another round of bumps but you're too fast.

https://github.com/mozilla/bedrock/pull/14175

**Comment by stevejalim** [comment]
@robhudson Ah sorry! Shall we land this one then rebase the ruff one to keep it separate, as it contains code changes too?

**Comment by robhudson** [comment]
However makes sense. I'll approve this and you can decide what's easiest. I filed the other one last Fri after hitting similar changes in basket.

**Review by robhudson — APPROVED** [review]

**Comment by stevejalim** [comment]
Happy to take on the rebase of your ruff branch @robhudson

**Pull request merged**
