### PR TITLE
Add aurora-bars mixin.

### PR DESCRIPTION
**Pull request by jpetto**
- Use mixin on firefox family landing page.

### CODE REVIEW

**Comment by jpetto** [comment]
IE <= 9 will just get a solid background color, which I think is acceptable. I'd rather not have each page include a fallback stylesheet just for an image file of these bars for IE <= 9.

Thoughts?

**Comment by jpetto** [comment]
@alexgibson r?

**Comment by alexgibson** [comment]
I'm totally fine with IE <= 9 just having a solid background. this is what progressive enhancement is for after all :smile: 

Everything about this looks great, except for Safari, which seems to render exactly the same standard syntax very differently from every other browser :cry: 

safari

**Comment by jpetto** [comment]
After a quick test, it seems Safari has problems with `transparent` used as a color stop. Good job, Safari.

I had a little luck replacing `transparent` with `rgba(255, 255, 255, 0)`, though Safari decides to render a noticeable bit of white even with a 0% opacity.

I'll dig in deeper tomorrow.

:disappointed:

**Comment by craigcook** [comment]
> I had a little luck replacing transparent with rgba(255, 255, 255, 0), though Safari decides to render a noticeable bit of white even with a 0% opacity.

I've run into this before with transparent gradients. <code>rgba(255, 255, 255, 0)</code> is transparent white, and I think the default value for the <code>transparent</code> keyword is <code>rgba(0, 0, 0, 0)</code>, or transparent black (since "transparent" isn't really a color, it's a color with a zero alpha channel). You need to blend the opaque blue into the transparent version of itself to get a correct opaque-to-transparent gradient. I think you can use a LESS function for this: <code>fade(@auroraStartColor, 0%)</code> and it should convert hex to rgba.

**Comment by jpetto** [comment]
Excellent call @craigcook. Tried your technique and all seems well, even in Safari.

Odd that some browsers interpret `transparent` as you'd logically expect (revealing the color underneath), while Safari treats it as a 0% alpha black.

**Comment by alexgibson** [comment]
This looks great! r+ :tangerine:

**Pull request merged**
