### PR TITLE
Remove Cloud9, Vagrant and legacy PHP docs and associated files

### PR DESCRIPTION
**Pull request by alexgibson**

### CODE REVIEW

**Comment by alexgibson** [comment]
@pmclanahan or @jgmize r?

**Comment by pmclanahan** [comment]
Looks good. I'll pull and build it to check, but I don't see any obvious problems.

**Comment by pmclanahan** [comment]
Should we go ahead and reduce the "Tabzilla" page to mostly just point at the new Tabzilla repo?

**Comment by alexgibson** [comment]
> Should we go ahead and reduce the "Tabzilla" page to mostly just point at the new Tabzilla repo?

Yes, good suggestion :+1:

**Comment by pmclanahan** [comment]
Changes look good. We can follow up on Tabzilla in another PR if you'd like. r+

**Comment by alexgibson** [comment]
@pmclanahan updated the tabzilla docs to point to the new repositories. I also found a few more c9 related files which I have removed. Will defer to you if they are safe to do so.

**Comment by pmclanahan** [comment]
Looks great to me. @jgmize may have opinions on the C9 stuff.

**Comment by jgmize** [comment]
Thanks @alexgibson and @pmclanahan

**Pull request merged**
