### PR TITLE
Bug 1352335 - Add Midsommarafton to SwedishHolidays.ics

### PR DESCRIPTION
**Pull request by kewisch**

### CODE REVIEW

**Comment by davidhedlund** [comment]
Thank you!

**Comment by davidhedlund** [comment]
When will Midsommarafton be part of https://www.mozilla.org/media/caldata/SwedishHolidays.ics ?

**Comment by kewisch** [comment]
As soon as this PR is merged, plus the time for the caches to update afterwards.

**Comment by alexgibson** [comment]
> As soon as this PR is merged, plus the time for the caches to update afterwards.

After this merges it will go to https://www-dev.allizom.org/media/caldata/SwedishHolidays.ics

It will not go to prod until the next time we deploy, which will likely be Monday.

**Comment by alexgibson** [comment]
Thanks!

**Pull request merged**
