### PR TITLE
Fix #11383: Set /about/legal/firefox/ to be English-only

### LINKED ISSUE #11383: The /about/legal/firefox/ page claims to be available in many languages, but is hard-coded english
## Description

If you go to e.g. https://www.mozilla.org/de/about/legal/firefox/ you will see English. You'll also see that the list of available languages is long, but each one is just the English content. 

I believe this is because the URL definition for this page is simply this:

```python
    page("firefox", "legal/firefox.html", ftl_files=["mozorg/about/legal"]),
```

The issue is that it only has an FTL file defined that is a generic one, where there should also be one for the specific page, that will never be translated.

### PR DESCRIPTION
**Pull request by pmac**

### CODE REVIEW

**Review by nathan-barrett — APPROVED** [review]
r+, thanks for the quick fix 💪🏻

**Comment by pmac** [comment]
actually, maybe I should just remove the `ftl_files` param instead of adding this new one?

**Comment by nathan-barrett** [comment]
If it will never be translated, then yeah - that would make sense to me

**Comment by pmac** [comment]
Updated the PR to just do that instead. No need for `ftl_files` if the template is hard-coded English.

**Comment by pmac** [comment]
I don't honestly know the purpose of this page. It looks like a legal-doc but it's not handled in the legal-docs repo.

**Pull request merged**
