### PR TITLE
Update integration test dependencies

### PR DESCRIPTION
**Pull request by davehunt**
### Guidelines
Before you submit a pull request, please make sure you have done the following:

- [x] Review the guidelines for contributing to this repository (link above in GitHub ^).
- [x] All commit messages should be well written, and reference a Bugzilla bug number where applicable.

Note: If you're unsure about anything here or below, don't worry! Just fill out as much
information as you can.

## Description
Update test dependencies for the integration tests.

## Bugzilla
N/A

## Testing
Running a few of the integration tests (and verifying that Travis is happy) should be enough.

## Checklist
- [ ] Requires l10n changes.
- [ ] Related functional & integration tests passing.

### CODE REVIEW

**Comment by alexgibson** [comment]
@davehunt looks like Travis is having some trouble matching up the hashes for new dependencies? ^

**Comment by davehunt** [comment]
@alexgibson I pushed an update after using peepin to get all the hashes.

**Comment by alexgibson** [comment]
I can't seem to run tests using Chrome, has something changed? Seeing this error: https://gist.github.com/alexgibson/c38ad051211adbb5ac9a

**Comment by davehunt** [comment]
@alexgibson should be fixed in v1.2.1, which I've just released - thanks for spotting that! Patch updated for latest version now.

**Comment by alexgibson** [comment]
Works! Thanks @davehunt r+

**Pull request merged**
