### PR TITLE
[fix bug 1422080] Remove and redirect /about/partnerships page

### PR DESCRIPTION
**Pull request by alexgibson**
## Description
- Removes and redirects `/about/partnerships/` to `/contact/`.
- Converts orphaned `/about/partnerships/distribution/` page from Sandstone to Pebbles.

**Do not merge** until we get some design approval.

## Issue / Bugzilla link
https://bugzilla.mozilla.org/show_bug.cgi?id=1422080

## Testing
- [x] Make sure I didn't miss any stray links or redundant assets?
- [x] Test responsiveness of new page.

### CODE REVIEW

**Comment by alexgibson** [comment]
Ok, we finally have all the approvals needed to remove this page. This is good for review.

**Comment by stephaniehobson** [comment]
Too bad we can't get ride of `/about/partnerships/distribution/` too.

Can `bedrock/mozorg/templates/mozorg/emails/partnerships.txt` be removed? I saw the forms have been removed, it looks like this is related.

Lines 28-30 in `bedrock/mozorg/views.py` also look form related.

Can `r'^about/partnerships/contact-bizdev/',` come out of `bedrock/settings/base.py`?

`bedrock/foundation/templates/foundation/trademarks/distribution-policy.html` links to `about/partnerships`

**Comment by alexgibson** [comment]
@stephaniehobson thanks for the careful review. I added a commit with some fixes!

**Comment by stephaniehobson** [comment]
@alexgibson This is approved but I think I messed the rebase up somehow, maybe rebase locally and force push?

**Comment by alexgibson** [comment]
Thanks @stephaniehobson - a rebase & squash seemed to do the trick 👍

**Pull request merged**
