### PR TITLE
"No parser was explicitly specified" warning Fixed

### PR DESCRIPTION
**Pull request by imskr**
## Description
fixed beautifulSoup Error warning
## Issue / Bugzilla link
#7798

### CODE REVIEW

**Comment by imskr** [comment]
@alexgibson Please review the PR. I have made the changes.

**Comment by alexgibson** [comment]
When I run this change locally and try to view /privacy/firefox/ the pase errors with:

```
jinja2.exceptions.UndefinedError: 'None' has no attribute 'section'
```

**Comment by alexgibson** [comment]
The value you've set here is a different one to that suggested in the warning. Any ideas on this one @pmac? (is this a non-issue, or a bug worth fixing?)

**Comment by imskr** [comment]
@alexgibson It should fix the issue I guess according to here: https://stackoverflow.com/questions/33511544/how-to-get-rid-of-beautifulsoup-user-warning

**Comment by alexgibson** [comment]
@imskr rather than the suggested stackoverflow solution, have you tried using the parser suggested in the warning message that's linked in the issue?

**Comment by pmac** [comment]
I think we should go with `lxml` as the parser since that's what we're using now, it's already installed, and known to be working. We could experiment with `html5lib` which also is installed, but we should do that in a separate issue.

**Comment by imskr** [comment]
@pmac Is it good now?

**Pull request merged**
