### PR TITLE
Initiate new CJMS POST when issued with a 404 for unknown aic id (Fixes #11506)

### LINKED ISSUE #11506: [Affiliate marketing] 404 for cjms call and error in the console
## Description

While testing the Affiliate Marketing initiative, we came across a potential issue 
We have the:
- Uncaught (in promise) Error: Unknown aicID: 92afb117-c2d8-455d-b262-5cf6743fd3fd error in the console.
- 404 response for the cjms PUT call, where the aicID should be in the response, which is empty
see screenshots and video

### Steps to reproduce
Steps performed:
1. Accessed the affiliate link in a new profile on Firefox: https://www-dev.allizom.org/en-US/products/vpn/?cjevent=4a39c2b8bccc11ec806c00a40a18050c
2. Left profile as is until next day, to perform a subscription with the affiliate code at a later date
3. The next day, opened the profile and refreshed the page

NOTE: 
- We did use that specific cjevent (4a39c2b8bccc11ec806c00a40a18050c) for other subscriptions. Could it be that the aicID has been assigned to one of those and it is no longer valid?
- We checked the same URL on a Firefox clean profile and it works as expected. It also works on Chrome.

### Expected result
The cookie banner should be displayed.
There are no errors in the console and the cjms call is made successfully

### Actual result

The cookie banner is not displayed, there are errors in the console and the cjms put call fails with 404

### Environment

Firefox, with a separate profile.

https://user-images.githubusercontent.com/52028275/164012156-849000f0-09f9-48fa-8a9f-b1095ee7534b.mp4

error in console
APIs
cjms response

### PR DESCRIPTION
**Pull request by alexgibson**
## Description
Right now if a visitor already has an affiliate marketing cookie set, but that corresponding ID no longer exists in the CJMS database, we end up throwing an `Unknown aicID` error and the cookie banner is not shown. This scenario is possible if someone has gone on to purchase a subscription via an affiliate link (at which point the ID is archived in the CJMS database), but then that visitor goes on to revisit the landing page later (before the cookie has expired).

This change makes it so we perform another `POST` if the existing `PUT` fails with a 404, rather than throwing an error like we do currently. Or in otherwords, we treat it like a new flow entry and override the existing affiliate cookie.

## Issue / Bugzilla link
#11506

## Testing
URL: http://localhost:8000/en-US/products/vpn/?cjevent=4a39c2b8bccc11ec806c00a40a18050c

The included tests should already cover this, but manual testing is not so easy as you need a cookie with an ID that's not in the database. The easiest way I could mock this was to manually create a cookie in the console using:

```javascript
Mozilla.Cookies.setItem(
    'moz-vpn-affiliate',
    'some-unique-to-you-test-value',
    new Date(1651137894 * 1000).toUTCString(),
    '/',
    null,
    false,
    'lax'
);
```

After this, if you refresh the page you should see the `PUT` fail with a 404 followed by a successful `POST`

### CODE REVIEW

**Comment by alexgibson** [comment]
This is ready for code review.

**Comment by maureenlholland** [comment]
LGTM @alexgibson just checking my understanding of the issue:

- the repeat visit to a profile with an existing marketing affiliate cookie was failing because the aic id had been archived after a separate action and we were trying to update that value's data with a PUT request (step 4 in the docs: https://bedrock.readthedocs.io/en/latest/vpn-affiliate-attribution.html) 
- using the same url on a fresh profile in Fx or Chrome did not cause the issue because there was no existing marketing affiliate cookie and we were already generating a new cookie in those cases (step 2 in the docs)

What is the `aic id` again? Is it the affiliate marketing ID?

**Comment by alexgibson** [comment]
@maureenlholland correct on all account :)

**Review by maureenlholland — APPROVED** [review]
Nice work on the testing and comments! 404 then 200 ✅ 
Screen Shot 2022-04-26 at 11 38 48 AM

Really great work on the docs too 📚

**Pull request merged**
