### PR TITLE
Fix Bug 1188890, 1188893 - Move credits CSV and forum data file out of SVN

### PR DESCRIPTION
**Pull request by kyoshino**

### CODE REVIEW

**Comment by pmclanahan** [comment]
Umm.... the actual credits data and commits shouldn't live in bedrock I don't think. I think it should get its own repo in the mozilla org.

**Comment by pmclanahan** [comment]
Let me know if you need for me to create said repo or repos for you. @gerv would you like credits and forums to live in the same or separate repos?

**Comment by kyoshino** [comment]
Hm, yeah. Putting those on a separate repo might be better to keep the Bedrock commit log clean.

**Comment by kyoshino** [comment]
Those 2 files and commit logs are now live at https://github.com/mozilla/community-data. Will send another PR to switch the source URLs in Bedrock.

**Comment by pmclanahan** [comment]
Thanks again @kyoshino. Great work! :cake:

**Pull request closed without merging**
