### PR TITLE
Decommission FxA iframe (Fixes #6149)

### LINKED ISSUE #6149: Decommission FxA iframe
Third party cookie blocking is preventing the FxA account iframe from showing the sign-in form.

All instances of the iframe should be replaced with the iframe-less form. Then we should remove the iframe and associated code from bedrock.

- [x] /bedrock/bedrock/firefox/templates/firefox/accounts/
- [ ] /bedrock/bedrock/firefox/templates/firefox/firstrun/firstrun-quantum-a.html
- [ ] /bedrock/bedrock/firefox/templates/firefox/firstrun/firstrun-quantum-b.html
- [ ] /bedrock/bedrock/firefox/templates/firefox/firstrun/firstrun-quantum-c.html
- [ ] /bedrock/bedrock/firefox/templates/firefox/firstrun/firstrun-quantum-d.html
- [ ] /bedrock/bedrock/firefox/templates/firefox/firstrun/firstrun-quantum.html
- [ ] /bedrock/bedrock/firefox/templates/firefox/firstrun/index.html
- [ ] /bedrock/bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx60.html
- [ ] /bedrock/bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx61.html
- [ ] /bedrock/bedrock/firefox/templates/firefox/whatsnew/whatsnew-fx62.html
- [ ] /bedrock/bedrock/firefox/templates/firefox/whatsnew/whatsnew-fxa.html

- [ ] remove iframe FxA code

### PR DESCRIPTION
**Pull request by alexgibson**
## Description
- Removes FxA iframe from old /firstrun templates, and makes the `firstrun-quantum.html` template the new default for legacy versions.
- Replaces the iframe on `firstrun-quantum.html` with a CTA button linking to `/firefox/accounts/`.
- Removes all /whatsnew pages older than 63, allowing them to fallback to the default `whatsnews.html` template.
- Remove FxA iframe shared code, tests and documentation.

P1, given this is related to a security bug.

## Issue / Bugzilla link
#6149

## Testing
- [x] /whatsnew URLs should all show default template (send-to-device):
  - https://bedrock-demo-agibson.oregon-b.moz.works/firefox/whatsnew/
  - https://bedrock-demo-agibson.oregon-b.moz.works/en-US/firefox/57.0/whatsnew/
  - https://bedrock-demo-agibson.oregon-b.moz.works/en-US/firefox/58.0/whatsnew/
  - https://bedrock-demo-agibson.oregon-b.moz.works/en-US/firefox/59.0/whatsnew/
  - https://bedrock-demo-agibson.oregon-b.moz.works/en-US/firefox/60.0/whatsnew/
  - https://bedrock-demo-agibson.oregon-b.moz.works/en-US/firefox/61.0/whatsnew/
  - https://bedrock-demo-agibson.oregon-b.moz.works/en-US/firefox/62.0/whatsnew/
- [x] /firstrun URLs should all show the quantum-themed template:
  - https://bedrock-demo-agibson.oregon-b.moz.works/firefox/firstrun/
  - https://bedrock-demo-agibson.oregon-b.moz.works/en-US/firefox/56.0/firstrun/
  - https://bedrock-demo-agibson.oregon-b.moz.works/en-US/firefox/57.0/firstrun/

### CODE REVIEW

**Comment by stephaniehobson** [comment]
I tried this out in Firefox 24 and it looks great.

**Comment by alexgibson** [comment]
@stephaniehobson thanks for the review, updated 👍

**Comment by alexgibson** [comment]
> Firstrun for 39 and less seem to be forwarding to the download page.

This is expected behavior.

**Comment by shane-tomlinson** [comment]
🎆🎆🎆🎆🎆🎆🎆🎆🎆🎆🎆🎆🎆🎆🎆

I could go on all day with 🎆, but you'd get bored.

Thanks @alexgibson and @stephaniehobson.

**Pull request merged**
