### PR TITLE
Bug  1320080 newsletter icon in thai page cut off

### PR DESCRIPTION
**Pull request by alisha17**

### CODE REVIEW

**Comment by alexgibson** [comment]
It looks like you've accidentally added a whole new file here, instead of just the changes needed to fix the bug?

**Comment by alexgibson** [comment]
Ah, it seems like you've manually added this file to the `/static` directory. You should be editing the file that lives in `/media/css/mozorg/home/home.scss`.

**Comment by alexgibson** [comment]
I'd also suggest that rather than fixing this just for the home page, as more robust solution could be to apply the fix to the [newsletter component](https://github.com/mozilla/bedrock/blob/master/media/css/pebbles/components/_newsletter.scss), that is shared across many pages.

**Comment by alisha17** [comment]
Okay. I will fix it as suggested.

**Comment by alexgibson** [comment]
Thanks! Feel free to ask here or in the bug if you need any help, or drop into #www on IRC

**Comment by alexgibson** [comment]
Closing in favor of #4539

**Pull request closed without merging**
