### PR TITLE
Update 404 and 500 error pages to use Pebbles

### PR DESCRIPTION
**Pull request by alexgibson**
## Description
- Updates our 404 and 500 pages to use Pebbles
- Adds bug reporting link to 500 page (uses same copy as 404 page).
- Exposes strings in 500 page template for l10n.
- Adds download button to 500 page.

## Issue / Bugzilla link
N/A

## Testing
- Test responsiveness
- Check for typos?

### CODE REVIEW

**Comment by flodolo** [comment]
Is there a trick to reach the 500 page on purpose (for testing)?

**Comment by alexgibson** [comment]
> Is there a trick to reach the 500 page on purpose (for testing)?

You can view `/500/` locally to see the page.

**Comment by flodolo** [comment]
> You can view /500/ locally to see the page.

Locally = local install?

**Comment by alexgibson** [comment]
> Locally = local install?

Correct

**Pull request merged**
