### PR TITLE
No-op mozorg migrations and remove unused picklefield dependency

### PR DESCRIPTION
**Pull request by robhudson**

### CODE REVIEW

**Review by pmac — APPROVED** [review]
seems fine. I guess this works better than squashing?

**Comment by robhudson** [comment]
Squashing still needs the migrations to exist until deployed. I was focused on removing the dependency.

We can follow this up with a squash, then deploy, then finally remove all the migrations except the squashed ones.

**Comment by robhudson** [comment]
I will add a squashed migration into this PR. So at least that step is done.

**Review by pmac — APPROVED** [review]
💯

**Pull request merged**
