### PR TITLE
Add pontoon config for privacy/passwords.ftl (Fixes #9795)

### LINKED ISSUE #9795: en/firefox/privacy/passwords.ftl  didn't come through on www-l10n repo
## Description
[This PR](https://github.com/mozilla-l10n/www-l10n/pull/154/files) including the passwords.ftl file didn't come through to the www-l10n repo/Pontoon. 

### Expected result

Check code and recommit the file through a new PR. 

### Actual result

Land the file in the www-l10n repo and Pontoon.

### PR DESCRIPTION
**Pull request by alexgibson**
Fixes: https://github.com/mozilla/bedrock/issues/9795

### CODE REVIEW

**Comment by alexgibson** [comment]
Huh, looks like circle failed because there's a duplicate string ID in the .ftl file. I'll update to remove it.

**Review by craigcook — APPROVED** [review]
🔑

**Comment by peiying2** [comment]
@craigcook the fix doesn't automatically add locales to the file. What's the next step to trigger that?

**Comment by craigcook** [comment]
> @craigcook the fix doesn't automatically add locales to the file. What's the next step to trigger that?

I'm not sure. I think this happened before with some other file, but don't recall how that was resolved. Alas I know little about how the bedrock-to-pontoon pipeline works and must defer to @pmac

**Comment by pmac** [comment]
locales to what file? The pontoon configs? That file is manually maintained in the bedrock repo.

**Comment by pmac** [comment]
Are you saying we need a specific list of locales in the pontoon.toml file? If so we just need to add it.

**Comment by craigcook** [comment]
It should be all locales, which I thought was the default unless otherwise specified. But maybe it just didn't get pushed to pontoon and I don't know if that happens automatically or needs some other process.

**Comment by pmac** [comment]
merging the changes here should result in a PR being opened to update the file in the l10n repo. Once that merges I believe Pontoon will pick it up.

**Comment by pmac** [comment]
Looks like these changes are in here https://github.com/mozilla-l10n/www-l10n/pull/156

**Pull request merged**
