### PR TITLE
Changed favicon to https://nightly.mozilla.org/img/favicon.png

### PR DESCRIPTION
**Pull request by TheJJ100100**
Changed favicon to https://nightly.mozilla.org/img/favicon.png using

 {% block page_favicon %}{{ static('https://nightly.mozilla.org/img/favicon.png') }}{% endblock %} 

Bug is https://bugzilla.mozilla.org/show_bug.cgi?id=1193839

### CODE REVIEW

**Comment by TheJJ100100** [comment]
I cannot find a local image for https://nightly.mozilla.org/img/favicon.png is there one?

**Comment by jpetto** [comment]
Hi @TheJJ100100 - Doesn't look like we have an image in bedrock for this favicon. Can you copy the one residing at https://nightly.mozilla.org/img/favicon.png and place it in bedrock at `/media/img/firefox/favicon-nightly.png`? Then reference that file in the template?

When you're making this update, can you also update your commit message? Something like the following would be great:

`[fix bug 1193839] Update favicon for /firefox/nightly/firstrun.`

Last note for future pull requests - our convention is to make a branch for each bug being fixed instead of working directly on `master`. If you were going to make a branch for this PR, the name might look like:

`bug-1193839-update-nightly-firstrun-favicon`

Thanks!

**Comment by TheJJ100100** [comment]
Is it possible for you to add  https://nightly.mozilla.org/img/favicon.png at /media/img/firefox/favicon-nightly.png as I am unable to add the file. I will change the reference to the favicon, though.

**Comment by TheJJ100100** [comment]
Don't worry, I've added it now

**Comment by jpetto** [comment]
Looking great @TheJJ100100! Last thing to do is squash your 4 commits into a single commit. We try to keep a single commit for each PR to keep our Git history tidy.

If you're not familiar with squashing commits, you can check out [this guide](https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/) to help you out. If you run in to trouble or need assistance, just ask. :smiley:

**Comment by TheJJ100100** [comment]
@jpetto I think I squashed them (I followed the guide), but that just made more commits!

**Comment by TheJJ100100** [comment]
I think I've got it now. It's the one before the merge because I couldn't push without merging.

**Comment by schalkneethling** [comment]
Hey @TheJJ100100 

Seems like your master branch is in a bit of a pickle so, here is what I suggest. First, create a new feature branch as follows:

```
git checkout -b bug-1193839-update-nightly-firstrun-favicon
```
Now, you need to cherry pick the commit with your changes:

```
git cherry-pick 5eda8d8997718675c89b46d64da9d7a82f5296eb
```
Push this new branch to your Github repo and open a new pull request. You can then close this one and reference the new pull request here. Hope that helps but, please let me know if you run into any trouble.

Thank you for contributing to Mozilla! :cake:

**Comment by TheJJ100100** [comment]
@jpetto New pull request. (On seperate branch.)

https://github.com/mozilla/bedrock/pull/3229

**Pull request closed without merging**
