### PR TITLE
The current version of ios is 1.4, not 1.2

### PR DESCRIPTION
**Pull request by sylvestre**

### CODE REVIEW

**Comment by alexgibson** [comment]
These looks like just test fixtures - I think you may be wanting to update this setting? https://github.com/mozilla/bedrock/blob/master/bedrock/settings/base.py#L1111-L1112 (See #3770)

**Comment by sylvestre** [comment]
Of course, sorry :/

**Comment by alexgibson** [comment]
Thanks @sylvestre - this was only a very recent change :+1:

**Comment by alexgibson** [comment]
Updated product details locally and I'm seeing `/firefox/ios/1.4/releasenotes/`display correctly. 

Thanks @sylvestre r+

**Pull request merged**
