### PR TITLE
Bug 1159522. Add Klif phone Senegal.

### PR DESCRIPTION
**Pull request by jpetto**
Still waiting on purchase URL, but good for review.

### CODE REVIEW

**Comment by jpetto** [comment]
@craigcook reviewed [original PR on private repo](https://github.com/mozilla/bedrock-private/pull/71). The purchase URL for Madagascar came in, however, making this PR much simpler than the original.

**Comment by craigcook** [comment]
This has an r+ for everything but the URL, which we're still waiting on and don't have any ETA. I expect other devices will land before we get the URL for this one so we may have to rebase this branch.

**Comment by Lord-of-Darkness** [comment]
Desarrolladores y líderes de Mozilla, que son travestis culo!

Alguien debe colgar ustedes para arriba en sus propias bolas y dejar que su perro muerda su caricatura de una polla!

Posteriormente deben ponerlo tiempo que sea necesario por la garganta hasta que traga a sí mismos en el suicidio!

Ustedes Mozilla está ... Estúpido de mierda coños!
--------------------------------------------------------
Developers and leaders of Mozilla, which are shemales ass!

Someone should hang you up in your own balls and let your dog bite his caricature of a cock!

They should then put it long as needed by the throat until he swallows themselves in suicide!

You Mozilla is... Stupid fucking pussies!

**Comment by jpetto** [comment]
Closing. Changes were made in PR #3002.

**Pull request closed without merging**
