### PR TITLE
Localize the new /about page (Fixes #6828)

### LINKED ISSUE #6828: Localize the new /about/ page
## Description

The newly designed [about page](https://www.mozilla.org/en-US/about/) has never been localized. With the launch of the new German home page, we'll be linking to `/de/about/` which is old branding. Unless we're not done experimenting on it yet, we should localize it so we can remove the old page.

### Estimates

| Estimates |  |
| ------------- | ------------- |
| TL | |
| PM | |
| ENG | |
| SEO | |
| ANA | |
| DES | |
| COPY | |

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Page is exposed for translation.
- [ ] Template is behind a conditional l10n tag.

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark
- [ ] Are there any reasons not to do this?

#### Tasks
- [ ] Prepare template/view for l10n.
- [ ] Ping l10n team for string extraction.

### PR DESCRIPTION
**Pull request by alexgibson**
## Description
- Exposes the new `/about/` page for localization.

## Issue / Bugzilla link
#6828

### CODE REVIEW

**Comment by peiying2** [comment]
Yes, we can get this started.

**Comment by alexgibson** [comment]
@peiying2 have the strings for this page been extracted? Just making sure it doesn't fall through the cracks. Thanks

**Comment by peiying2** [comment]
@alexgibson let's add an l10n label please.

**Comment by alexgibson** [comment]
@peiying2 done, thank you

**Pull request merged**
