### PR TITLE
Add redirects for careers and donate

### PR DESCRIPTION
**Pull request by pmac**
I found these URLs on the back of a sticker. They should work.

### CODE REVIEW

**Comment by pmac** [comment]
@alexgibson r?

**Comment by alexgibson** [comment]
r+

**Comment by pmac** [comment]
Thanks Alex!

/me waves at fellow weekend computer warrior

**Comment by alexgibson** [comment]
/me waves back on his way to get a weekend beer 🍺

**Comment by pmac** [comment]
🍻

**Comment by pmac** [comment]
🍻

**Pull request merged**
