### PR TITLE
[fix bug 1383305] Promote Fx55 WNP experiment winner.

### PR DESCRIPTION
**Pull request by jpetto**
## Description

Promotes the winning variation from the test begun in #5009.

For all locales that do not get the Send to Device widget a QR code will now be displayed instead of the app store badges.

Two questions pending in the bug:

1. should the locales with the Send to Device widget keep the app store badges or not?
2. which QR code image should be promoted?

The above shouldn't block review though - biggest change would be deleting HTML and swapping an image. (Hoping to get this out tomorrow, hence the semi-early review ask.)

**Update**

App store badges removed for all conditions. JS complexity drastically reduced!

## Issue / Bugzilla link

https://bugzilla.mozilla.org/show_bug.cgi?id=1383305#c20

## Testing

Make sure no regressions and no files missed that could be deleted.

### CODE REVIEW

**Comment by flodolo** [comment]
Is this supposed to be localized?

**Comment by alexgibson** [comment]
Let me know if you want me to take another look should there be any updates

**Comment by flodolo** [comment]
> Is this supposed to be localized?

Never mind, it looks like it's just things moving around.

**Comment by alexgibson** [comment]
> @alexgibson Can you take a look at the second commit here? Thanks!

Changes look good to me and locales seem to be doing the right thing still. Hooray for less code!

**Comment by jpetto** [comment]
@alexgibson Squashed!

**Pull request merged**
