### PR TITLE
Add GA tracking to Fx refresh button. Bug 1027318.

### PR DESCRIPTION
**Pull request by jpetto**

### CODE REVIEW

**Comment by alexgibson** [comment]
Interestingly, I only see the event logged by GA once I click cancel on the modal dialog. I think this is because FF pauses JS when it's displayed. I'm not going to click "Refresh Firefox", but I do wonder if events will get lost in this case? (not sure what FF does)

**Comment by jpetto** [comment]
Oh, hmm. I saw the GA event in my console, but didn't notice it being paused while the dialog was open (wasn't paying close attention). I'll move the GA call before the refresh call and see what happens.

**Comment by chrismore** [comment]
Isn't this very similar to when the a download dialog box pauses the JS like the regular download buttons did before we changed the GA JS?

**Comment by jpetto** [comment]
Moving the GA call above the UITour reset call seems to have done the trick. GA happens prior to the reset/refresh dialog opening.

Labeled as do not merge, as I think we'll be adding one more bit of GA for when the refresh button is shown.

**Comment by jpetto** [comment]
We'll be adding further tracking down the road. This is now good to review/merge.

**Comment by chrismore** [comment]
+1

**Comment by alexgibson** [comment]
r+ :dizzy:

**Pull request merged**
