### PR TITLE
More docs improvements

### PR DESCRIPTION
**Pull request by pmac**
Followup from #10437:

- Fix docs formating errors and warnings from Sphinx
- Change the `make docs` command to start an auto-build-reload server using Docker:
  * `make docs` does this using Docker
  * `make livedocs` does this locally
  * `make build-docs` just builds the docs using Docker

### CODE REVIEW

**Review by maureenlholland — APPROVED** [review]
r+ 📝 ! Docker and local working great - thanks!

If we want to be squeaky clean, there is one last warning that could be addressed, but it's not a block:

`/app/docs/install.rst:236: WARNING: Explicit markup ends without a blank line; unexpected unindent.`

**Comment by pmac** [comment]
> If we want to be squeaky clean, there is one last warning that could be addressed, but it's not a block:

I know. I can't seem to find the magical incantation to make that go away. I'll poke at it a bit more. It is very annoying to leave that one warning.

**Comment by maureenlholland** [comment]
@pmac I think it just wants a blank line before the Localization heading

**Comment by pmac** [comment]
Yup. You're right. Sleep helped me. I was banging my head against this on Friday. All of the other warnings I was working on were in the contentful file, and I failed to notice that this one was in install.rst 🤦‍♂️ All fixed up now.

**Pull request merged**
