### PR TITLE
Update contribute.json.

### PR DESCRIPTION
**Pull request by pmclanahan**
Improved bugzilla URLs, added Travis-CI, and added contacts.

### CODE REVIEW

**Comment by pmclanahan** [comment]
@alexgibson @craigcook @jgmize anyone have opinions? I filed mozilla/contribute.json#61 to address the lack of a place for translation contribution URLs and contacts. I'll update again once that's decided on.

**Comment by alexgibson** [comment]
LGTM - yay for adding @kyoshino :tada:

**Comment by alexgibson** [comment]
I think we should also add @schalkneethling as an IRC contact now he's part of webprod, and the front-end code for plugincheck is also [moving into bedrock](https://github.com/mozilla/bedrock/pull/2828).

**Comment by pmclanahan** [comment]
Good point Alex. Adding now.

**Comment by craigcook** [comment]
r+ from me. @jgmize ?

**Pull request merged**
