### PR TITLE
[fix bug 1281230] Update TestFlight page title & description

### PR DESCRIPTION
**Pull request by jpetto**
## Description

Update page title & description to help users find Firefox iOS Beta.

## Bugzilla link

https://bugzilla.mozilla.org/show_bug.cgi?id=1281230

## Testing

Make sure I didn't cook any copy pasta.

## Checklist
- [x] Requires l10n changes.
- [ ] Related functional & integration tests passing.

### CODE REVIEW

**Comment by alexgibson** [comment]
Changes look good to me, r+ 🍖 

/cc @peiying2 for l10n changes.

**Comment by flodolo** [comment]
This pages is en-US only per bug 1266801, so you don't actually need the l10n_has_tag

**Comment by alexgibson** [comment]
Bah, I did not know this :( The page being en-US only probably doesn't help raise our SEO much either, but then I'm guessing this is probably for good reason.

Jon, would you like to leave this as-is, or should we follow up and remove the superfluous tags?

**Comment by alexgibson** [comment]
Opened #4296 to remove the l10n tags.

**Pull request merged**
