### PR TITLE
Bug 1121096 - Hello product page: display video for all Spanish variants

### PR DESCRIPTION
**Pull request by flodolo**
Received a request to display the video on all Spanish variants.

Not sure if a) need a bug for this b) there are smarter ways to do it

### CODE REVIEW

**Comment by flodolo** [comment]
@jpetto can you take a look and let me know if I need to file a bug for this anyway?

**Comment by jpetto** [comment]
r+ on the code. Waiting for bug to be filed/put in commit message for historical purposes. Ready to merge after that.

**Comment by flodolo** [comment]
Thanks, amended commit and added bug reference. Now waiting for Travis (sounds like an evergreen...).

**Comment by jpetto** [comment]
Thanks @flodolo!

**Pull request merged**
