### PR TITLE
Fix Bug 1125166 - Some mozilla.org-sites consider 31.4ESR to be out of date

### PR DESCRIPTION
**Pull request by kyoshino**

### CODE REVIEW

**Comment by jpetto** [comment]
@kyoshino - Can you link to confirmation (in a bug, perhaps) that `navigator.buildID` is safe and valid to use in this context?

**Comment by alexgibson** [comment]
As we're relying on UA sniffing and the property is non-standard, should we at least check for the existence of `navigator.buildID` before trying to read the value? Adding a test for this would also be good, thanks @kyoshino

**Comment by alexgibson** [comment]
Actually scratch that it's ok, since we're only checking that it does not equal a set value here. A test would still be good though?

**Comment by kyoshino** [comment]
Added tests!

**Comment by kyoshino** [comment]
Added a double-check for `navigator.buildID` and tested on Firefox 31 non-ESR, Firefox 31 ESR and Firefox 31.4.0 ESR.

**Comment by alexgibson** [comment]
Manually verified this works as expected on ESR 31.4.0, and update bar still shows for 31.0 release version. Verified buildID is correct as per https://wiki.mozilla.org/Releases/Firefox_31/Test_Plan

Test are all green, code looks good. Thanks @kyoshino! :+1:

**Comment by kyoshino** [comment]
Thanks \o/

**Pull request merged**
